In [1]:
import pandas as pd
import numpy as np

pd.options.display.max_columns = 999

pd.__version__

'3.0.6'

Lemos primeiro o CO2 de 2000–2009. Ainda não removemos nenhuma coluna.

In [2]:
co2df1 = pd.read_csv(r'owd\co2_2000_2009.csv')
co2df1.shape

(290, 6)

A dimensão indica 290 linhas e 79 colunas nos anexos usados para testar o notebook. Vamos observar apenas os primeiros registos, evitando mostrar a tabela completa.

In [3]:
co2df1.head()

   country  year iso_code  population     co2  co2_per_capita
0  Austria  2000      AUT   8012929.0  66.204           8.262
1  Austria  2001      AUT   8042233.0  70.191           8.728
2  Austria  2002      AUT   8081640.0  71.988           8.908
3  Austria  2003      AUT   8122604.0  77.412           9.530
4  Austria  2004      AUT   8173496.0  77.716           9.508

In [4]:
co2df2 = pd.read_csv(r'owd\co2_2010_2019.csv')
co2df2.shape

(290, 6)

In [5]:
co2df2.head()

   country  year iso_code  population     co2  co2_per_capita
0  Austria  2010      AUT   8365087.0  72.000           8.607
1  Austria  2011      AUT   8393272.0  69.892           8.327
2  Austria  2012      AUT   8431599.0  67.260           7.977
3  Austria  2013      AUT   8481411.0  67.759           7.989
4  Austria  2014      AUT   8547812.0  64.159           7.506

In [6]:
co2df3 = pd.read_csv(r'owd\co2_2020_2024.csv')
co2df3.shape

(145, 6)

In [7]:
co2df3.head()

   country  year iso_code  population     co2  co2_per_capita
0  Austria  2020      AUT   8921402.0  62.180           6.970
1  Austria  2021      AUT   8967053.0  65.751           7.333
2  Austria  2022      AUT   9064678.0  61.454           6.780
3  Austria  2023      AUT   9130434.0  56.909           6.233
4  Austria  2024      AUT   9120815.0  56.368           6.180

Verificamos que são todas iguais

In [8]:
assert co2df1.columns.tolist() == co2df2.columns.tolist()

In [9]:
assert co2df1.columns.tolist() == co2df3.columns.tolist()

## 2. Reunir períodos com `concat`
Os períodos contêm as mesmas variáveis e observações de anos diferentes: queremos acrescentar linhas, não fazer uma junção por chaves.

In [10]:
co2 = pd.concat([co2df1, co2df2, co2df3])#, ignore_index=True)
co2.iloc[285:295]

           country  year iso_code   population       co2  co2_per_capita
285  United States  2005      USA  295716666.0  6126.903          20.719
286  United States  2006      USA  298730208.0  6045.326          20.237
287  United States  2007      USA  301844223.0  6121.542          20.280
288  United States  2008      USA  304970325.0  5919.221          19.409
289  United States  2009      USA  308023452.0  5486.104          17.811
0          Austria  2010      AUT    8365087.0    72.000           8.607
1          Austria  2011      AUT    8393272.0    69.892           8.327
2          Austria  2012      AUT    8431599.0    67.260           7.977
3          Austria  2013      AUT    8481411.0    67.759           7.989
4          Austria  2014      AUT    8547812.0    64.159           7.506

`ignore_index=True` cria um índice numérico consecutivo. Não ordena os países e anos.

In [11]:
co2 = pd.concat([co2df1, co2df2, co2df3], ignore_index=True)
co2.iloc[285:295]

           country  year iso_code   population       co2  co2_per_capita
285  United States  2005      USA  295716666.0  6126.903          20.719
286  United States  2006      USA  298730208.0  6045.326          20.237
287  United States  2007      USA  301844223.0  6121.542          20.280
288  United States  2008      USA  304970325.0  5919.221          19.409
289  United States  2009      USA  308023452.0  5486.104          17.811
290        Austria  2010      AUT    8365087.0    72.000           8.607
291        Austria  2011      AUT    8393272.0    69.892           8.327
292        Austria  2012      AUT    8431599.0    67.260           7.977
293        Austria  2013      AUT    8481411.0    67.759           7.989
294        Austria  2014      AUT    8547812.0    64.159           7.506

In [12]:
co2.shape

(725, 6)

In [13]:
co2.iloc[575:585]

           country  year iso_code   population       co2  co2_per_capita
575  United States  2015      USA  326126496.0  5368.497          16.461
576  United States  2016      USA  329179423.0  5245.362          15.935
577  United States  2017      USA  332204657.0  5195.417          15.639
578  United States  2018      USA  335056492.0  5361.236          16.001
579  United States  2019      USA  337790069.0  5235.912          15.500
580        Austria  2020      AUT    8921402.0    62.180           6.970
581        Austria  2021      AUT    8967053.0    65.751           7.333
582        Austria  2022      AUT    9064678.0    61.454           6.780
583        Austria  2023      AUT    9130434.0    56.909           6.233
584        Austria  2024      AUT    9120815.0    56.368           6.180

Verificamos a ausência de chaves duplicadas.

In [14]:
co2.duplicated(['iso_code', 'year']).sum()

np.int64(0)

Reorganizamos por país e ano. Esta ordenação também é necessária quando queremos comparar uma concatenação com uma tabela anteriormente ordenada por estas chaves.

In [15]:
co2 = co2.sort_values(['iso_code', 'year'])#.reset_index(drop=True)
co2[15:25]

     country  year iso_code  population     co2  co2_per_capita
295  Austria  2015      AUT   8644037.0  66.358           7.677
296  Austria  2016      AUT   8737920.0  67.219           7.693
297  Austria  2017      AUT   8798779.0  69.601           7.910
298  Austria  2018      AUT   8841653.0  66.567           7.529
299  Austria  2019      AUT   8880876.0  67.951           7.651
580  Austria  2020      AUT   8921402.0  62.180           6.970
581  Austria  2021      AUT   8967053.0  65.751           7.333
582  Austria  2022      AUT   9064678.0  61.454           6.780
583  Austria  2023      AUT   9130434.0  56.909           6.233
584  Austria  2024      AUT   9120815.0  56.368           6.180

In [16]:
co2 = co2.sort_values(['iso_code', 'year']).reset_index(drop=True)
co2[15:25]

    country  year iso_code  population     co2  co2_per_capita
15  Austria  2015      AUT   8644037.0  66.358           7.677
16  Austria  2016      AUT   8737920.0  67.219           7.693
17  Austria  2017      AUT   8798779.0  69.601           7.910
18  Austria  2018      AUT   8841653.0  66.567           7.529
19  Austria  2019      AUT   8880876.0  67.951           7.651
20  Austria  2020      AUT   8921402.0  62.180           6.970
21  Austria  2021      AUT   8967053.0  65.751           7.333
22  Austria  2022      AUT   9064678.0  61.454           6.780
23  Austria  2023      AUT   9130434.0  56.909           6.233
24  Austria  2024      AUT   9120815.0  56.368           6.180

In [17]:
#co2.to_csv("co2.csv", index=False)

Podemos preservar a origem de cada parte através de `keys`. Aqui nasce um índice com dois níveis: período e linha original.

In [18]:
co2_origem = pd.concat(
    [co2df1, co2df2, co2df3],
    keys=['2000–2009', '2010–2019', '2020+'],
    names=['periodo'],
    #ignore_index=False
)#.droplevel(1)#.swaplevel(0, 1).reset_index(level=0, drop=True)
#co2_origem = co2_origem.swaplevel(0,1)

co2_origem.iloc[285:295]

                     country  year iso_code   population       co2  \
periodo
2000–2009 285  United States  2005      USA  295716666.0  6126.903
          286  United States  2006      USA  298730208.0  6045.326
          287  United States  2007      USA  301844223.0  6121.542
          288  United States  2008      USA  304970325.0  5919.221
          289  United States  2009      USA  308023452.0  5486.104
2010–2019 0          Austria  2010      AUT    8365087.0    72.000
          1          Austria  2011      AUT    8393272.0    69.892
          2          Austria  2012      AUT    8431599.0    67.260
          3          Austria  2013      AUT    8481411.0    67.759
          4          Austria  2014      AUT    8547812.0    64.159

               co2_per_capita
periodo
2000–2009 285          20.719
          286          20.237
          287          20.280
          288          19.409
          289          17.811
2010–2019 0             8.607
          1             8.327
          2             7.977
          3             7.989
          4             7.506

In [19]:
#co2_origem = co2_origem.swaplevel(0,1)#droplevel(1)
#co2_origem.head()

A seleção pelo primeiro nível recupera um período. Esta tabela serve para ilustrar proveniência; a análise principal continua a usar `co2`.

In [20]:
co2_origem.set_index('country')

               year iso_code   population       co2  co2_per_capita
country
Austria        2000      AUT    8012929.0    66.204           8.262
Austria        2001      AUT    8042233.0    70.191           8.728
Austria        2002      AUT    8081640.0    71.988           8.908
Austria        2003      AUT    8122604.0    77.412           9.530
Austria        2004      AUT    8173496.0    77.716           9.508
...             ...      ...          ...       ...             ...
United States  2020      USA  339436156.0  4689.954          13.817
United States  2021      USA  340161438.0  5020.111          14.758
United States  2022      USA  341534041.0  5055.403          14.802
United States  2023      USA  343477330.0  4918.407          14.319
United States  2024      USA  345426566.0  4904.120          14.197

[725 rows x 5 columns]

In [21]:
co2_origem = co2_origem.set_index('country', append=True)
co2_origem

                             year iso_code   population       co2  \
periodo       country
2000–2009 0   Austria        2000      AUT    8012929.0    66.204
          1   Austria        2001      AUT    8042233.0    70.191
          2   Austria        2002      AUT    8081640.0    71.988
          3   Austria        2003      AUT    8122604.0    77.412
          4   Austria        2004      AUT    8173496.0    77.716
...                           ...      ...          ...       ...
2020+     140 United States  2020      USA  339436156.0  4689.954
          141 United States  2021      USA  340161438.0  5020.111
          142 United States  2022      USA  341534041.0  5055.403
          143 United States  2023      USA  343477330.0  4918.407
          144 United States  2024      USA  345426566.0  4904.120

                             co2_per_capita
periodo       country
2000–2009 0   Austria                 8.262
          1   Austria                 8.728
          2   Austria                 8.908
          3   Austria                 9.530
          4   Austria                 9.508
...                                     ...
2020+     140 United States          13.817
          141 United States          14.758
          142 United States          14.802
          143 United States          14.319
          144 United States          14.197

[725 rows x 5 columns]

In [22]:
co2_origem.droplevel(1)

                         year iso_code   population       co2  co2_per_capita
periodo   country
2000–2009 Austria        2000      AUT    8012929.0    66.204           8.262
          Austria        2001      AUT    8042233.0    70.191           8.728
          Austria        2002      AUT    8081640.0    71.988           8.908
          Austria        2003      AUT    8122604.0    77.412           9.530
          Austria        2004      AUT    8173496.0    77.716           9.508
...                       ...      ...          ...       ...             ...
2020+     United States  2020      USA  339436156.0  4689.954          13.817
          United States  2021      USA  340161438.0  5020.111          14.758
          United States  2022      USA  341534041.0  5055.403          14.802
          United States  2023      USA  343477330.0  4918.407          14.319
          United States  2024      USA  345426566.0  4904.120          14.197

[725 rows x 5 columns]

In [23]:
co2_origem.swaplevel(0,1)

,,,year,iso_code,population,co2,co2_per_capita
,periodo,country,,,,,
0,2000–2009,Austria,2000,AUT,8012929.0,66.204,8.262
1,2000–2009,Austria,2001,AUT,8042233.0,70.191,8.728
2,2000–2009,Austria,2002,AUT,8081640.0,71.988,8.908
3,2000–2009,Austria,2003,AUT,8122604.0,77.412,9.530
4,2000–2009,Austria,2004,AUT,8173496.0,77.716,9.508
...,...,...,...,...,...,...,...
140,2020+,United States,2020,USA,339436156.0,4689.954,13.817
141,2020+,United States,2021,USA,340161438.0,5020.111,14.758
142,2020+,United States,2022,USA,341534041.0,5055.403,14.802
143,2020+,United States,2023,USA,343477330.0,4918.407,14.319
144,2020+,United States,2024,USA,345426566.0,4904.120,14.197

## 3. Ler energia: observar uma estrutura diferente
Os CSV de energia têm cinco colunas. A população é um indicador, não uma coluna repetida em cada observação.

In [24]:
endf1 = pd.read_csv(r'owd\energy_2000_2009.csv')
endf1.shape

(1160, 5)

In [25]:
endf1.head(10)

   country iso_code  year                     indicator       value
0  Austria      AUT  2000        electricity_demand_twh       58.27
1  Austria      AUT  2000  fossil_fuels_electricity_twh       16.20
2  Austria      AUT  2000    low_carbon_electricity_twh       43.44
3  Austria      AUT  2000                    population  8012929.00
4  Austria      AUT  2001        electricity_demand_twh       61.20
5  Austria      AUT  2001  fossil_fuels_electricity_twh       18.74
6  Austria      AUT  2001    low_carbon_electricity_twh       42.24
7  Austria      AUT  2001                    population  8042233.00
8  Austria      AUT  2002        electricity_demand_twh       61.33
9  Austria      AUT  2002  fossil_fuels_electricity_twh       18.73

In [26]:
endf1['indicator'].unique()

<StringArray>
[      'electricity_demand_twh', 'fossil_fuels_electricity_twh',
   'low_carbon_electricity_twh',                   'population']
Length: 4, dtype: str

In [27]:
endf2 = pd.read_csv(r'owd\energy_2010_2019.csv')
endf2.shape

(1160, 5)

In [28]:
endf3 = pd.read_csv(r'owd\energy_2020_2025.csv')
endf3.shape

(696, 5)

In [29]:
assert endf1['indicator'].unique().tolist() == endf2['indicator'].unique().tolist()
assert endf1['indicator'].unique().tolist() == endf3['indicator'].unique().tolist()

Reunimos também os períodos de energia por linhas.

In [30]:
en = pd.concat([endf1, endf2, endf3], ignore_index=True)
en.shape

(3016, 5)

In [31]:
en[1155:1165]

            country iso_code  year                     indicator         value
1155  United States      USA  2008                    population  3.049703e+08
1156  United States      USA  2009        electricity_demand_twh  3.973870e+03
1157  United States      USA  2009  fossil_fuels_electricity_twh  2.725410e+03
1158  United States      USA  2009    low_carbon_electricity_twh  1.214410e+03
1159  United States      USA  2009                    population  3.080235e+08
1160        Austria      AUT  2010        electricity_demand_twh  7.026000e+01
1161        Austria      AUT  2010  fossil_fuels_electricity_twh  2.283000e+01
1162        Austria      AUT  2010    low_carbon_electricity_twh  4.499000e+01
1163        Austria      AUT  2010                    population  8.365087e+06
1164        Austria      AUT  2011        electricity_demand_twh  7.040000e+01

A população tem unidade diferente dos restantes indicadores. É legítimo armazená-los na mesma coluna `valor`, mas não somar ou tirar médias indiscriminadamente dessa coluna. Os nomes terminados em `_twh` explicitam a unidade das medidas elétricas.

## 4. Uma necessidade concreta de `pivot`

CO2 tem uma linha por país–ano; energia tem uma por país–ano–indicador. Para combinar duas tabelas com uma linha por país–ano, transformamos os indicadores de energia em colunas.

In [32]:
energia = en.pivot(
    index=['country', 'iso_code', 'year'],
    columns='indicator',
    values='value'
)
energia.head()

indicator              electricity_demand_twh  fossil_fuels_electricity_twh  \
country iso_code year
Austria AUT      2000                   58.27                         16.20
                 2001                   61.20                         18.74
                 2002                   61.33                         18.73
                 2003                   63.58                         22.73
                 2004                   64.93                         22.23

indicator              low_carbon_electricity_twh  population
country iso_code year
Austria AUT      2000                       43.44   8012929.0
                 2001                       42.24   8042233.0
                 2002                       41.90   8081640.0
                 2003                       35.24   8122604.0
                 2004                       39.62   8173496.0

O resultado tem um índice hierárquico nas linhas. `reset_index` recupera os identificadores como colunas; retiramos também o nome do eixo das colunas, sem renomear as variáveis.

In [33]:
energia = energia.reset_index()
energia.head()

indicator,country,iso_code,year,electricity_demand_twh,fossil_fuels_electricity_twh,low_carbon_electricity_twh,population
0,Austria,AUT,2000,58.27,16.20,43.44,8012929.0
1,Austria,AUT,2001,61.20,18.74,42.24,8042233.0
2,Austria,AUT,2002,61.33,18.73,41.90,8081640.0
3,Austria,AUT,2003,63.58,22.73,35.24,8122604.0
4,Austria,AUT,2004,64.93,22.23,39.62,8173496.0

In [34]:
energia.columns

Index(['country', 'iso_code', 'year', 'electricity_demand_twh',
       'fossil_fuels_electricity_twh', 'low_carbon_electricity_twh',
       'population'],
      dtype='str', name='indicator')

In [35]:
energia.columns.name = None
energia.head()

,country,iso_code,year,electricity_demand_twh,fossil_fuels_electricity_twh,low_carbon_electricity_twh,population
0,Austria,AUT,2000,58.27,16.20,43.44,8012929.0
1,Austria,AUT,2001,61.20,18.74,42.24,8042233.0
2,Austria,AUT,2002,61.33,18.73,41.90,8081640.0
3,Austria,AUT,2003,63.58,22.73,35.24,8122604.0
4,Austria,AUT,2004,64.93,22.23,39.62,8173496.0

## 5. Junções: começar pela relação entre chaves

observamos os anos disponíveis. CO2 termina em 2024 e energia chega a 2025.

In [36]:
pd.DataFrame(
    {
        'minimo': [co2['year'].min(), energia['year'].min()],
        'maximo': [co2['year'].max(), energia['year'].max()]
    },
    index = ['CO2', 'Energia']
)

         minimo  maximo
CO2        2000    2024
Energia    2000    2025

In [37]:
co2.columns

Index(['country', 'year', 'iso_code', 'population', 'co2', 'co2_per_capita'], dtype='str')

In [38]:
energia.columns

Index(['country', 'iso_code', 'year', 'electricity_demand_twh',
       'fossil_fuels_electricity_twh', 'low_carbon_electricity_twh',
       'population'],
      dtype='str')

Vamos fazer um merge (um JOIN no contexto de Bases de Dados)...
1) Qual é a "chave primária" dos DataFrames? Será o que vamos usar para "unir" os DataFrames...
2) Só por curiosidade, os DataFrames estão normalizados? Na 3FN?

In [39]:
co2.head()

   country  year iso_code  population     co2  co2_per_capita
0  Austria  2000      AUT   8012929.0  66.204           8.262
1  Austria  2001      AUT   8042233.0  70.191           8.728
2  Austria  2002      AUT   8081640.0  71.988           8.908
3  Austria  2003      AUT   8122604.0  77.412           9.530
4  Austria  2004      AUT   8173496.0  77.716           9.508

In [40]:
energia.head()

,country,iso_code,year,electricity_demand_twh,fossil_fuels_electricity_twh,low_carbon_electricity_twh,population
0,Austria,AUT,2000,58.27,16.20,43.44,8012929.0
1,Austria,AUT,2001,61.20,18.74,42.24,8042233.0
2,Austria,AUT,2002,61.33,18.73,41.90,8081640.0
3,Austria,AUT,2003,63.58,22.73,35.24,8122604.0
4,Austria,AUT,2004,64.93,22.23,39.62,8173496.0

Confirmamos a chave

In [41]:
assert not energia.duplicated(['iso_code', 'year']).any()

Usamos código ISO e ano como chaves, não o nome do país. Uma junção externa com `indicator=True` torna visíveis as observações exclusivas de cada fonte.

In [42]:
juncao = co2.merge(
    energia,
    on=['iso_code', 'year'],
    how='outer',
    indicator=True,
)
juncao

,country_x,year,iso_code,population_x,co2,co2_per_capita,country_y,electricity_demand_twh,fossil_fuels_electricity_twh,low_carbon_electricity_twh,population_y,_merge
0,Austria,2000,AUT,8012929.0,66.204,8.262,Austria,58.27,16.20,43.44,8012929.0,both
1,Austria,2001,AUT,8042233.0,70.191,8.728,Austria,61.20,18.74,42.24,8042233.0,both
2,Austria,2002,AUT,8081640.0,71.988,8.908,Austria,61.33,18.73,41.90,8081640.0,both
3,Austria,2003,AUT,8122604.0,77.412,9.530,Austria,63.58,22.73,35.24,8122604.0,both
4,Austria,2004,AUT,8173496.0,77.716,9.508,Austria,64.93,22.23,39.62,8173496.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...
749,United States,2021,USA,340161438.0,5020.111,14.758,United States,4192.93,2512.39,1641.23,340161438.0,both
750,United States,2022,USA,341534041.0,5055.403,14.802,United States,4328.10,2557.21,1729.68,341534041.0,both
751,United States,2023,USA,343477330.0,4918.407,14.319,United States,4272.81,2514.30,1739.61,343477330.0,both
752,United States,2024,USA,345426566.0,4904.120,14.197,United States,4404.83,2552.53,1838.49,345426566.0,both
753,NaN,2025,USA,NaN,NaN,NaN,United States,4535.81,2576.21,1943.58,347275809.0,right_only

O argumento `indicator` (acima) cria uma coluna (`_merge`, ou o nome indicado no argumento), com a origem dos dados da linha

In [43]:
juncao['_merge'].value_counts()

_merge
both          725
right_only     29
left_only       0
Name: count, dtype: int64

Inspecionamos os casos presentes apenas na energia. O ano adicional explica a diferença de cobertura nos anexos, mas esta verificação é preferível a assumir que as fontes terminam no mesmo ano.

In [44]:
juncao.loc[
    juncao['_merge'] == 'right_only',
    ['iso_code', 'year', 'country_y']
].head()

    iso_code  year country_y
25       AUT  2025   Austria
51       BEL  2025   Belgium
77       BGR  2025  Bulgaria
103      CHN  2025     China
129      CYP  2025    Cyprus

Sem sufixos explícitos, pandas distinguiu as colunas comuns com `_x` e `_y`. Vamos identificar esses nomes.

In [45]:
juncao.columns.str.endswith(('_x', '_y'))

array([ True, False, False,  True, False, False,  True, False, False,
       False,  True, False])

In [46]:
#[c for c in juncao.columns if c.endswith(('_x', '_y'))]

juncao.columns[juncao.columns.str.endswith(('_x', '_y'))]

Index(['country_x', 'population_x', 'country_y', 'population_y'], dtype='str')

Refazemos a junção com sufixos informativos. As chaves aparecem uma vez; os nomes e a população aparecem nas duas versões.

In [47]:
dados = co2.merge(
    energia,
    on=['iso_code', 'year'],
    how='inner',
    suffixes=('_co2', '_energia')
)
dados

,country_co2,year,iso_code,population_co2,co2,co2_per_capita,country_energia,electricity_demand_twh,fossil_fuels_electricity_twh,low_carbon_electricity_twh,population_energia
0,Austria,2000,AUT,8012929.0,66.204,8.262,Austria,58.27,16.20,43.44,8012929.0
1,Austria,2001,AUT,8042233.0,70.191,8.728,Austria,61.20,18.74,42.24,8042233.0
2,Austria,2002,AUT,8081640.0,71.988,8.908,Austria,61.33,18.73,41.90,8081640.0
3,Austria,2003,AUT,8122604.0,77.412,9.530,Austria,63.58,22.73,35.24,8122604.0
4,Austria,2004,AUT,8173496.0,77.716,9.508,Austria,64.93,22.23,39.62,8173496.0
...,...,...,...,...,...,...,...,...,...,...,...
720,United States,2020,USA,339436156.0,4689.954,13.817,United States,4090.49,2431.90,1611.28,339436156.0
721,United States,2021,USA,340161438.0,5020.111,14.758,United States,4192.93,2512.39,1641.23,340161438.0
722,United States,2022,USA,341534041.0,5055.403,14.802,United States,4328.10,2557.21,1729.68,341534041.0
723,United States,2023,USA,343477330.0,4918.407,14.319,United States,4272.81,2514.30,1739.61,343477330.0
724,United States,2024,USA,345426566.0,4904.120,14.197,United States,4404.83,2552.53,1838.49,345426566.0

Antes de eliminar colunas repetidas, verificamos os nomes e as populações. Um mesmo nome de variável não garante valores iguais nas duas fontes.

In [48]:
comparacao_pop = dados['population_co2'] - dados['population_energia']
(comparacao_pop != 0).sum()

np.int64(0)

In [49]:
(dados['country_co2'] != dados['country_energia']).sum()

np.int64(0)

Não usamos a diferença de população para concluir que uma fonte está errada: os CSV não documentam aqui a causa.

Neste caso, como são todos iguais, podemos remover uma das colunas e renomear de acordo

In [50]:
dados = (
    dados
    .drop(['country_energia', 'population_energia'], axis=1)
    .rename({'country_co2': 'country', 'population_co2': 'population'}, axis=1)
)
dados

,country,year,iso_code,population,co2,co2_per_capita,electricity_demand_twh,fossil_fuels_electricity_twh,low_carbon_electricity_twh
0,Austria,2000,AUT,8012929.0,66.204,8.262,58.27,16.20,43.44
1,Austria,2001,AUT,8042233.0,70.191,8.728,61.20,18.74,42.24
2,Austria,2002,AUT,8081640.0,71.988,8.908,61.33,18.73,41.90
3,Austria,2003,AUT,8122604.0,77.412,9.530,63.58,22.73,35.24
4,Austria,2004,AUT,8173496.0,77.716,9.508,64.93,22.23,39.62
...,...,...,...,...,...,...,...,...,...
720,United States,2020,USA,339436156.0,4689.954,13.817,4090.49,2431.90,1611.28
721,United States,2021,USA,340161438.0,5020.111,14.758,4192.93,2512.39,1641.23
722,United States,2022,USA,341534041.0,5055.403,14.802,4328.10,2557.21,1729.68
723,United States,2023,USA,343477330.0,4918.407,14.319,4272.81,2514.30,1739.61
724,United States,2024,USA,345426566.0,4904.120,14.197,4404.83,2552.53,1838.49

## 6. Acrescentar a classificação dos blocos
Lemos a tabela auxiliar e verificamos a unicidade do código. A relação esperada é muitos registos anuais para um país na tabela de classificação.

In [51]:
paises = pd.read_csv(r'owd\paises_blocos.csv', index_col='iso_code')
paises

                 country  group
iso_code
AUT              Áustria  UE-27
BEL              Bélgica  UE-27
BGR             Bulgária  UE-27
HRV              Croácia  UE-27
CYP               Chipre  UE-27
CZE              Chéquia  UE-27
DNK            Dinamarca  UE-27
EST              Estónia  UE-27
FIN            Finlândia  UE-27
FRA               França  UE-27
DEU             Alemanha  UE-27
GRC               Grécia  UE-27
HUN              Hungria  UE-27
IRL              Irlanda  UE-27
ITA               Itália  UE-27
LVA              Letónia  UE-27
LTU             Lituânia  UE-27
LUX           Luxemburgo  UE-27
MLT                Malta  UE-27
NLD        Países Baixos  UE-27
POL              Polónia  UE-27
PRT             Portugal  UE-27
ROU              Roménia  UE-27
SVK           Eslováquia  UE-27
SVN            Eslovénia  UE-27
ESP              Espanha  UE-27
SWE               Suécia  UE-27
USA       Estados Unidos    EUA
CHN                China  China

A contagem confirma a composição definida na preparação: 27 países no bloco UE-27 e um em cada um dos outros blocos.

In [52]:
paises['group'].value_counts()

group
UE-27    27
EUA       1
China     1
Name: count, dtype: int64

Acrescentamos o nome em português e o bloco.

In [53]:
dados = dados.merge(
    paises,
    left_on='iso_code',
    right_index=True,
    how='left',
    suffixes=['_dados', '_paises']
)
#assert dados['bloco'].notna().all()
#dados[['iso_code', 'year', 'pais_pt', 'bloco']].head()
dados

,country_dados,year,iso_code,population,co2,co2_per_capita,electricity_demand_twh,fossil_fuels_electricity_twh,low_carbon_electricity_twh,country_paises,group
0,Austria,2000,AUT,8012929.0,66.204,8.262,58.27,16.20,43.44,Áustria,UE-27
1,Austria,2001,AUT,8042233.0,70.191,8.728,61.20,18.74,42.24,Áustria,UE-27
2,Austria,2002,AUT,8081640.0,71.988,8.908,61.33,18.73,41.90,Áustria,UE-27
3,Austria,2003,AUT,8122604.0,77.412,9.530,63.58,22.73,35.24,Áustria,UE-27
4,Austria,2004,AUT,8173496.0,77.716,9.508,64.93,22.23,39.62,Áustria,UE-27
...,...,...,...,...,...,...,...,...,...,...,...
720,United States,2020,USA,339436156.0,4689.954,13.817,4090.49,2431.90,1611.28,Estados Unidos,EUA
721,United States,2021,USA,340161438.0,5020.111,14.758,4192.93,2512.39,1641.23,Estados Unidos,EUA
722,United States,2022,USA,341534041.0,5055.403,14.802,4328.10,2557.21,1729.68,Estados Unidos,EUA
723,United States,2023,USA,343477330.0,4918.407,14.319,4272.81,2514.30,1739.61,Estados Unidos,EUA
724,United States,2024,USA,345426566.0,4904.120,14.197,4404.83,2552.53,1838.49,Estados Unidos,EUA

In [54]:
dados = dados.drop('country_dados', axis=1).rename({'country_paises': 'country'}, axis=1)
dados

,year,iso_code,population,co2,co2_per_capita,electricity_demand_twh,fossil_fuels_electricity_twh,low_carbon_electricity_twh,country,group
0,2000,AUT,8012929.0,66.204,8.262,58.27,16.20,43.44,Áustria,UE-27
1,2001,AUT,8042233.0,70.191,8.728,61.20,18.74,42.24,Áustria,UE-27
2,2002,AUT,8081640.0,71.988,8.908,61.33,18.73,41.90,Áustria,UE-27
3,2003,AUT,8122604.0,77.412,9.530,63.58,22.73,35.24,Áustria,UE-27
4,2004,AUT,8173496.0,77.716,9.508,64.93,22.23,39.62,Áustria,UE-27
...,...,...,...,...,...,...,...,...,...,...
720,2020,USA,339436156.0,4689.954,13.817,4090.49,2431.90,1611.28,Estados Unidos,EUA
721,2021,USA,340161438.0,5020.111,14.758,4192.93,2512.39,1641.23,Estados Unidos,EUA
722,2022,USA,341534041.0,5055.403,14.802,4328.10,2557.21,1729.68,Estados Unidos,EUA
723,2023,USA,343477330.0,4918.407,14.319,4272.81,2514.30,1739.61,Estados Unidos,EUA
724,2024,USA,345426566.0,4904.120,14.197,4404.83,2552.53,1838.49,Estados Unidos,EUA

In [55]:
order = [
    'year',
    'iso_code',
    'country',
    'group',
    'population',
    'co2',
    'co2_per_capita',
    'electricity_demand_twh',
    'fossil_fuels_electricity_twh',
    'low_carbon_electricity_twh',
]

assert sorted(order) == sorted(dados.columns.tolist())

In [56]:
dados = dados[order]
dados

,year,iso_code,country,group,population,co2,co2_per_capita,electricity_demand_twh,fossil_fuels_electricity_twh,low_carbon_electricity_twh
0,2000,AUT,Áustria,UE-27,8012929.0,66.204,8.262,58.27,16.20,43.44
1,2001,AUT,Áustria,UE-27,8042233.0,70.191,8.728,61.20,18.74,42.24
2,2002,AUT,Áustria,UE-27,8081640.0,71.988,8.908,61.33,18.73,41.90
3,2003,AUT,Áustria,UE-27,8122604.0,77.412,9.530,63.58,22.73,35.24
4,2004,AUT,Áustria,UE-27,8173496.0,77.716,9.508,64.93,22.23,39.62
...,...,...,...,...,...,...,...,...,...,...
720,2020,USA,Estados Unidos,EUA,339436156.0,4689.954,13.817,4090.49,2431.90,1611.28
721,2021,USA,Estados Unidos,EUA,340161438.0,5020.111,14.758,4192.93,2512.39,1641.23
722,2022,USA,Estados Unidos,EUA,341534041.0,5055.403,14.802,4328.10,2557.21,1729.68
723,2023,USA,Estados Unidos,EUA,343477330.0,4918.407,14.319,4272.81,2514.30,1739.61
724,2024,USA,Estados Unidos,EUA,345426566.0,4904.120,14.197,4404.83,2552.53,1838.49

## 7. `Index` e `MultiIndex`
Começamos com um índice simples na tabela de países. O código ISO identifica univocamente cada linha.

Selecionamos por etiqueta com `.loc` e por posição com `.iloc`. Não são duas formas de pedir necessariamente a mesma linha.

Na tabela anual, o país repete-se. Precisamos de país e ano para identificar cada observação.

In [57]:
#painel = dados.set_index([('','iso_code'), ('','year')]).sort_index()
painel = dados.set_index(['iso_code', 'country', 'year']).sort_index()
painel

                              group   population       co2  co2_per_capita  \
iso_code country        year
AUT      Áustria        2000  UE-27    8012929.0    66.204           8.262
                        2001  UE-27    8042233.0    70.191           8.728
                        2002  UE-27    8081640.0    71.988           8.908
                        2003  UE-27    8122604.0    77.412           9.530
                        2004  UE-27    8173496.0    77.716           9.508
...                             ...          ...       ...             ...
USA      Estados Unidos 2020    EUA  339436156.0  4689.954          13.817
                        2021    EUA  340161438.0  5020.111          14.758
                        2022    EUA  341534041.0  5055.403          14.802
                        2023    EUA  343477330.0  4918.407          14.319
                        2024    EUA  345426566.0  4904.120          14.197

                              electricity_demand_twh  \
iso_code country        year
AUT      Áustria        2000                   58.27
                        2001                   61.20
                        2002                   61.33
                        2003                   63.58
                        2004                   64.93
...                                              ...
USA      Estados Unidos 2020                 4090.49
                        2021                 4192.93
                        2022                 4328.10
                        2023                 4272.81
                        2024                 4404.83

                              fossil_fuels_electricity_twh  \
iso_code country        year
AUT      Áustria        2000                         16.20
                        2001                         18.74
                        2002                         18.73
                        2003                         22.73
                        2004                         22.23
...                                                    ...
USA      Estados Unidos 2020                       2431.90
                        2021                       2512.39
                        2022                       2557.21
                        2023                       2514.30
                        2024                       2552.53

                              low_carbon_electricity_twh
iso_code country        year
AUT      Áustria        2000                       43.44
                        2001                       42.24
                        2002                       41.90
                        2003                       35.24
                        2004                       39.62
...                                                  ...
USA      Estados Unidos 2020                     1611.28
                        2021                     1641.23
                        2022                     1729.68
                        2023                     1739.61
                        2024                     1838.49

[725 rows x 7 columns]

In [58]:
painel.index.names, painel.index.nlevels, painel.index.is_unique

(FrozenList(['iso_code', 'country', 'year']), 3, True)

Observamos os níveis e os códigos internos do índice. Os códigos representam posições nas etiquetas dos níveis, não os valores medidos.

In [59]:
painel.index.levels

FrozenList([['AUT', 'BEL', 'BGR', 'CHN', 'CYP', 'CZE', 'DEU', 'DNK', 'ESP', 'EST', 'FIN', 'FRA', 'GRC', 'HRV', 'HUN', 'IRL', 'ITA', 'LTU', 'LUX', 'LVA', 'MLT', 'NLD', 'POL', 'PRT', 'ROU', 'SVK', 'SVN', 'SWE', 'USA'], ['Alemanha', 'Bulgária', 'Bélgica', 'China', 'Chipre', 'Chéquia', 'Croácia', 'Dinamarca', 'Eslováquia', 'Eslovénia', 'Espanha', 'Estados Unidos', 'Estónia', 'Finlândia', 'França', 'Grécia', 'Hungria', 'Irlanda', 'Itália', 'Letónia', 'Lituânia', 'Luxemburgo', 'Malta', 'Países Baixos', 'Polónia', 'Portugal', 'Roménia', 'Suécia', 'Áustria'], [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]])

In [60]:
painel.index.levels[0]

Index(['AUT', 'BEL', 'BGR', 'CHN', 'CYP', 'CZE', 'DEU', 'DNK', 'ESP', 'EST',
       'FIN', 'FRA', 'GRC', 'HRV', 'HUN', 'IRL', 'ITA', 'LTU', 'LUX', 'LVA',
       'MLT', 'NLD', 'POL', 'PRT', 'ROU', 'SVK', 'SVN', 'SWE', 'USA'],
      dtype='str', name='iso_code')

In [61]:
painel.index.codes

FrozenList([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...], [28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, ...]])

In [62]:
[codigos[:30] for codigos in painel.index.codes]

[array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 1, 1, 1], dtype=int8),
 array([28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
        28, 28, 28, 28, 28, 28, 28, 28,  2,  2,  2,  2,  2], dtype=int8),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24,  0,  1,  2,  3,  4], dtype=int8)]

Uma seleção parcial pelo país devolve todos os seus anos. Selecionamos apenas duas medidas para facilitar a leitura.

In [63]:
painel.loc[['PRT'], ['co2', 'electricity_demand_twh']].head()

                           co2  electricity_demand_twh
iso_code country  year
PRT      Portugal 2000  65.504                   44.14
                  2001  65.187                   46.30
                  2002  69.583                   47.45
                  2003  64.482                   49.18
                  2004  67.302                   51.16

Um tuplo identifica uma observação. Aqui obtemos uma Series com as variáveis de Portugal em 2020.

In [64]:
painel.loc[[('PRT', 'Portugal', 2020)], ['co2', 'electricity_demand_twh']]

                           co2  electricity_demand_twh
iso_code country  year
PRT      Portugal 2020  41.738                   52.85

Uma lista de tuplos mantém o resultado em forma tabular, mesmo quando selecionamos apenas uma observação.

In [65]:
painel.columns = pd.MultiIndex.from_tuples(
    [
        ('group', ''),
        ('population', ''),
        ('CO2', 'co2'),
        ('CO2', 'co2_per_capita'),
        ('Energy', 'electricity_demand_twh'),
        ('Energy', 'fossil_fuels_electricity_twh'),
        ('Energy', 'low_carbon_electricity_twh'),
    ],
    names=['fonte', 'indicador']
)
painel

fonte                         group   population       CO2                 \
indicador                                              co2 co2_per_capita
iso_code country        year
AUT      Áustria        2000  UE-27    8012929.0    66.204          8.262
                        2001  UE-27    8042233.0    70.191          8.728
                        2002  UE-27    8081640.0    71.988          8.908
                        2003  UE-27    8122604.0    77.412          9.530
                        2004  UE-27    8173496.0    77.716          9.508
...                             ...          ...       ...            ...
USA      Estados Unidos 2020    EUA  339436156.0  4689.954         13.817
                        2021    EUA  340161438.0  5020.111         14.758
                        2022    EUA  341534041.0  5055.403         14.802
                        2023    EUA  343477330.0  4918.407         14.319
                        2024    EUA  345426566.0  4904.120         14.197

fonte                                        Energy  \
indicador                    electricity_demand_twh
iso_code country        year
AUT      Áustria        2000                  58.27
                        2001                  61.20
                        2002                  61.33
                        2003                  63.58
                        2004                  64.93
...                                             ...
USA      Estados Unidos 2020                4090.49
                        2021                4192.93
                        2022                4328.10
                        2023                4272.81
                        2024                4404.83

fonte                                                      \
indicador                    fossil_fuels_electricity_twh
iso_code country        year
AUT      Áustria        2000                        16.20
                        2001                        18.74
                        2002                        18.73
                        2003                        22.73
                        2004                        22.23
...                                                   ...
USA      Estados Unidos 2020                      2431.90
                        2021                      2512.39
                        2022                      2557.21
                        2023                      2514.30
                        2024                      2552.53

fonte
indicador                    low_carbon_electricity_twh
iso_code country        year
AUT      Áustria        2000                      43.44
                        2001                      42.24
                        2002                      41.90
                        2003                      35.24
                        2004                      39.62
...                                                 ...
USA      Estados Unidos 2020                    1611.28
                        2021                    1641.23
                        2022                    1729.68
                        2023                    1739.61
                        2024                    1838.49

[725 rows x 7 columns]

O índice ordenado permite selecionar um intervalo de anos dentro de um país. Os limites do intervalo com `.loc` estão incluídos.

In [66]:
painel.columns.names, painel.columns.nlevels, painel.columns.is_unique

(FrozenList(['fonte', 'indicador']), 2, True)

In [67]:
#ERRO

#painel.loc[['PRT', :, 2020:2022], :]

In [68]:
idx = pd.IndexSlice

painel.loc[idx['PRT', :, 2020:2022], :]

fonte                   group  population     CO2                 \
indicador                                     co2 co2_per_capita
iso_code country  year
PRT      Portugal 2020  UE-27  10370519.0  41.738          4.025
                  2021  UE-27  10390957.0  40.300          3.878
                  2022  UE-27  10417074.0  40.722          3.909

fonte                                  Energy                               \
indicador              electricity_demand_twh fossil_fuels_electricity_twh
iso_code country  year
PRT      Portugal 2020                  52.85                        21.28
                  2021                  53.97                        17.68
                  2022                  55.58                        18.72

fonte
indicador              low_carbon_electricity_twh
iso_code country  year
PRT      Portugal 2020                      30.11
                  2021                      31.54
                  2022                      27.61

In [69]:
painel.loc[ idx['PRT', :, 2020:], 'Energy']

indicador               electricity_demand_twh  fossil_fuels_electricity_twh  \
iso_code country  year
PRT      Portugal 2020                   52.85                         21.28
                  2021                   53.97                         17.68
                  2022                   55.58                         18.72
                  2023                   56.37                         11.78
                  2024                   57.74                          7.00

indicador               low_carbon_electricity_twh
iso_code country  year
PRT      Portugal 2020                       30.11
                  2021                       31.54
                  2022                       27.61
                  2023                       34.36
                  2024                       40.27

In [70]:
painel.loc[ idx['PRT', :, 2020:], idx[:, 'co2']]

fonte                      CO2
indicador                  co2
iso_code country  year
PRT      Portugal 2020  41.738
                  2021  40.300
                  2022  40.722
                  2023  37.622
                  2024  35.539

In [71]:
mascara = (
    (painel.columns.isin(['co2'], level='indicador'))
    |
    (painel.columns.get_level_values('fonte') == 'Energy')
)

painel.loc[ idx['PRT', :, 2020:], mascara ]

fonte                      CO2                 Energy  \
indicador                  co2 electricity_demand_twh
iso_code country  year
PRT      Portugal 2020  41.738                  52.85
                  2021  40.300                  53.97
                  2022  40.722                  55.58
                  2023  37.622                  56.37
                  2024  35.539                  57.74

fonte
indicador              fossil_fuels_electricity_twh low_carbon_electricity_twh
iso_code country  year
PRT      Portugal 2020                        21.28                      30.11
                  2021                        17.68                      31.54
                  2022                        18.72                      27.61
                  2023                        11.78                      34.36
                  2024                         7.00                      40.27

Com `IndexSlice`, selecionamos os mesmos anos de vários países, sem construir tuplos manualmente para todas as combinações.

In [72]:
painel.loc[idx[['PRT', 'USA', 'CHN'], :,  2020:2022], ['CO2']]

fonte                               CO2
indicador                           co2 co2_per_capita
iso_code country        year
PRT      Portugal       2020     41.738          4.025
                        2021     40.300          3.878
                        2022     40.722          3.909
USA      Estados Unidos 2020   4689.954         13.817
                        2021   5020.111         14.758
                        2022   5055.403         14.802
CHN      China          2020  10896.521          7.641
                        2021  11284.401          7.911
                        2022  11711.808          8.218

Trocamos a hierarquia para consultar primeiro o ano. `swaplevel` troca níveis; `sort_index` ordena pela nova hierarquia.

In [73]:
por_ano = painel.swaplevel('iso_code', 'year').sort_index()
por_ano.head()

fonte                   group    population       CO2                 \
indicador                                         co2 co2_per_capita
year country  iso_code
2000 Alemanha DEU       UE-27  8.179726e+07   898.976         10.990
     Bulgária BGR       UE-27  8.000519e+06    45.499          5.687
     Bélgica  BEL       UE-27  1.025172e+07   126.776         12.366
     China    CHN       China  1.269581e+09  3643.810          2.870
     Chipre   CYP       UE-27  9.476670e+05     7.107          7.499

fonte                                  Energy                               \
indicador              electricity_demand_twh fossil_fuels_electricity_twh
year country  iso_code
2000 Alemanha DEU                      572.01                       363.93
     Bulgária BGR                       35.97                        19.78
     Bélgica  BEL                       87.12                        33.58
     China    CHN                     1346.85                      1113.30
     Chipre   CYP                        3.37                         3.37

fonte
indicador              low_carbon_electricity_twh
year country  iso_code
2000 Alemanha DEU                          205.02
     Bulgária BGR                           20.81
     Bélgica  BEL                           49.21
     China    CHN                          242.30
     Chipre   CYP                            0.00

In [74]:
por_ano.loc[[2020], idx[:, 'co2']].head()

fonte                         CO2
indicador                     co2
year country  iso_code
2020 Alemanha DEU         647.177
     Bulgária BGR          36.571
     Bélgica  BEL          91.255
     China    CHN       10896.521
     Chipre   CYP           6.903

`reset_index` devolve os níveis às colunas. Verificamos que as chaves voltaram a estar disponíveis para uma futura junção.

In [75]:
sem_indice = painel.reset_index()
sem_indice

fonte     iso_code         country  year  group   population       CO2  \
indicador                                                          co2
0              AUT         Áustria  2000  UE-27    8012929.0    66.204
1              AUT         Áustria  2001  UE-27    8042233.0    70.191
2              AUT         Áustria  2002  UE-27    8081640.0    71.988
3              AUT         Áustria  2003  UE-27    8122604.0    77.412
4              AUT         Áustria  2004  UE-27    8173496.0    77.716
..             ...             ...   ...    ...          ...       ...
720            USA  Estados Unidos  2020    EUA  339436156.0  4689.954
721            USA  Estados Unidos  2021    EUA  340161438.0  5020.111
722            USA  Estados Unidos  2022    EUA  341534041.0  5055.403
723            USA  Estados Unidos  2023    EUA  343477330.0  4918.407
724            USA  Estados Unidos  2024    EUA  345426566.0  4904.120

fonte                                    Energy                               \
indicador co2_per_capita electricity_demand_twh fossil_fuels_electricity_twh
0                  8.262                  58.27                        16.20
1                  8.728                  61.20                        18.74
2                  8.908                  61.33                        18.73
3                  9.530                  63.58                        22.73
4                  9.508                  64.93                        22.23
..                   ...                    ...                          ...
720               13.817                4090.49                      2431.90
721               14.758                4192.93                      2512.39
722               14.802                4328.10                      2557.21
723               14.319                4272.81                      2514.30
724               14.197                4404.83                      2552.53

fonte
indicador low_carbon_electricity_twh
0                              43.44
1                              42.24
2                              41.90
3                              35.24
4                              39.62
..                               ...
720                          1611.28
721                          1641.23
722                          1729.68
723                          1739.61
724                          1838.49

[725 rows x 10 columns]

Pode-se fazer o mesmo com as colunas

In [76]:
sem_indice.columns

MultiIndex([(  'iso_code',                             ''),
            (   'country',                             ''),
            (      'year',                             ''),
            (     'group',                             ''),
            ('population',                             ''),
            (       'CO2',                          'co2'),
            (       'CO2',               'co2_per_capita'),
            (    'Energy',       'electricity_demand_twh'),
            (    'Energy', 'fossil_fuels_electricity_twh'),
            (    'Energy',   'low_carbon_electricity_twh')],
           names=['fonte', 'indicador'])

In [77]:
colunas = [
    indicador if indicador != '' else fonte
    for fonte, indicador in sem_indice.columns
]
colunas

['iso_code',
 'country',
 'year',
 'group',
 'population',
 'co2',
 'co2_per_capita',
 'electricity_demand_twh',
 'fossil_fuels_electricity_twh',
 'low_carbon_electricity_twh']

In [78]:
sem_indice.columns = colunas
sem_indice

,iso_code,country,year,group,population,co2,co2_per_capita,electricity_demand_twh,fossil_fuels_electricity_twh,low_carbon_electricity_twh
0,AUT,Áustria,2000,UE-27,8012929.0,66.204,8.262,58.27,16.20,43.44
1,AUT,Áustria,2001,UE-27,8042233.0,70.191,8.728,61.20,18.74,42.24
2,AUT,Áustria,2002,UE-27,8081640.0,71.988,8.908,61.33,18.73,41.90
3,AUT,Áustria,2003,UE-27,8122604.0,77.412,9.530,63.58,22.73,35.24
4,AUT,Áustria,2004,UE-27,8173496.0,77.716,9.508,64.93,22.23,39.62
...,...,...,...,...,...,...,...,...,...,...
720,USA,Estados Unidos,2020,EUA,339436156.0,4689.954,13.817,4090.49,2431.90,1611.28
721,USA,Estados Unidos,2021,EUA,340161438.0,5020.111,14.758,4192.93,2512.39,1641.23
722,USA,Estados Unidos,2022,EUA,341534041.0,5055.403,14.802,4328.10,2557.21,1729.68
723,USA,Estados Unidos,2023,EUA,343477330.0,4918.407,14.319,4272.81,2514.30,1739.61
724,USA,Estados Unidos,2024,EUA,345426566.0,4904.120,14.197,4404.83,2552.53,1838.49

In [79]:
sem_indice[['iso_code', 'year', 'co2']].head()

  iso_code  year     co2
0      AUT  2000  66.204
1      AUT  2001  70.191
2      AUT  2002  71.988
3      AUT  2003  77.412
4      AUT  2004  77.716

## 8. Uma Series hierárquica: `unstack` e `stack`
Selecionamos uma medida. O seu índice continua a ter país e ano.

In [80]:
serie_co2 = painel['CO2']
serie_co2.head()

indicador                 co2  co2_per_capita
iso_code country year
AUT      Áustria 2000  66.204           8.262
                 2001  70.191           8.728
                 2002  71.988           8.908
                 2003  77.412           9.530
                 2004  77.716           9.508

Passamos o país do índice para as colunas. Cada linha passa a representar um ano.

In [81]:
co2_por_ano = serie_co2.unstack(['iso_code', 'country'])
co2_por_ano.head()

indicador     co2                                                       \
iso_code      AUT      BEL      BGR       CHN    CYP      CZE      DEU
country   Áustria  Bélgica Bulgária     China Chipre  Chéquia Alemanha
year
2000       66.204  126.776   45.499  3643.810  7.107  127.233  898.976
2001       70.191  126.085   49.020  3724.114  6.980  127.165  915.255
2002       71.988  126.883   46.141  4098.181  7.172  123.988  898.834
2003       77.412  128.292   50.491  4835.251  7.561  127.592  894.501
2004       77.716  128.812   49.537  5210.961  7.787  128.314  876.570

indicador                                                                 \
iso_code        DNK      ESP     EST       FIN      FRA      GRC     HRV
country   Dinamarca  Espanha Estónia Finlândia   França   Grécia Croácia
year
2000         54.307  309.260  15.471    57.017  407.445  102.973  19.653
2001         55.897  311.031  15.870    62.520  411.592  105.361  20.776
2002         55.554  331.028  15.358    65.049  407.027  105.000  21.916
2003         60.645  335.539  17.251    72.658  412.989  109.067  23.226
2004         55.100  352.139  17.322    68.946  414.073  109.485  22.853

indicador                                                              \
iso_code      HUN     IRL      ITA      LTU        LUX     LVA    MLT
country   Hungria Irlanda   Itália Lituânia Luxemburgo Letónia  Malta
year
2000       58.244  45.250  469.598   11.843      8.702   7.082  2.468
2001       59.828  47.608  469.679   12.594      9.205   7.497  2.737
2002       58.842  46.081  477.136   12.666      9.978   7.520  2.747
2003       61.611  45.684  495.094   12.659     10.451   7.726  2.961
2004       59.985  46.167  500.687   13.254     11.816   7.731  2.849

indicador                                                                \
iso_code            NLD      POL      PRT      ROU        SVK       SVN
country   Países Baixos  Polónia Portugal  Roménia Eslováquia Eslovénia
year
2000            172.154  317.306   65.504   93.206     41.187    15.060
2001            177.464  313.267   65.187   98.928     43.273    16.309
2002            176.738  305.852   69.583   99.069     42.034    16.571
2003            180.169  318.733   64.482  103.707     42.359    16.278
2004            182.090  323.621   67.302  103.233     42.857    16.711

indicador                        co2_per_capita                          \
iso_code      SWE            USA            AUT     BEL      BGR    CHN
country    Suécia Estados Unidos        Áustria Bélgica Bulgária  China
year
2000       54.892       6023.158          8.262  12.366    5.687  2.870
2001       55.782       5903.562          8.728  12.257    6.183  2.912
2002       56.634       5947.819          8.908  12.279    5.869  3.185
2003       57.221       6006.440          9.530  12.364    6.470  3.735
2004       56.428       6111.545          9.508  12.360    6.392  4.002

indicador                                                                     \
iso_code     CYP     CZE      DEU       DNK     ESP     EST       FIN    FRA
country   Chipre Chéquia Alemanha Dinamarca Espanha Estónia Finlândia França
year
2000       7.499  12.429   10.990    10.170   7.539  11.074    11.015  6.850
2001       7.239  12.428   11.171    10.431   7.541  11.432    12.051  6.871
2002       7.308  12.109   10.952    10.334   7.928  11.134    12.508  6.747
2003       7.564  12.449   10.894    11.250   7.894  12.584    13.938  6.799
2004       7.650  12.504   10.678    10.195   8.145  12.712    13.187  6.769

indicador                                                                     \
iso_code      GRC     HRV     HUN     IRL    ITA      LTU        LUX     LVA
country    Grécia Croácia Hungria Irlanda Itália Lituânia Luxemburgo Letónia
year
2000        9.550   4.543   5.716  11.900  8.199    3.383     19.953   2.990
2001        9.717   4.830   5.885  12.324  8.196    3.626     20.838   3.206
2002        9.642   5.090   5.804  11.730  8.309    3.678     22.354   3.254
2003        9.989   5.393   6.095  11.441  8.575    3.707     23.129   3.375
2004       10.001   5.302   5.947  11.354  8.606    3.925     25.782   3.415

indicador                                                                     \
iso_code     MLT           NLD     POL      PRT     ROU        SVK       SVN
country    Malta Países Baixos Polónia Portugal Roménia Eslováquia Eslovénia
year
2000       6.172        10.720   8.294    6.370   4.228      7.656     7.580
2001       6.794        10.966   8.191    6.296   4.513      8.044     8.197
2002       6.774        10.851   8.000    6.682   4.551      7.816     8.321
2003       7.253        11.008   8.343    6.168   4.803      7.879     8.170
2004       6.935        11.086   8.479    6.421   4.823      7.972     8.382

indicador
iso_code     SWE            USA
country   Suécia Estados Unidos
year
2000       6.187         21.398
2001       6.270         20.767
2002       6.345         20.718
2003       6.387         20.718
2004       6.274         20.874

In [82]:
co2_por_ano.loc[2020:2022, idx[:,['PRT', 'USA', 'CHN']]]

indicador,co2,co2_per_capita,co2,co2_per_capita,co2,co2_per_capita
iso_code,PRT,PRT,USA,USA,CHN,CHN
country,Portugal,Portugal,Estados Unidos,Estados Unidos,China,China
year,,,,,,
2020,41.738,4.025,4689.954,13.817,10896.521,7.641
2021,40.300,3.878,5020.111,14.758,11284.401,7.911
2022,40.722,3.909,5055.403,14.802,11711.808,8.218

Com a nova implementação de `stack`, recuperamos o país como nível do índice sem eliminar implicitamente as combinações com valores em falta.

In [83]:
serie_reposta = co2_por_ano.stack(level=[1,2])
serie_reposta.head()

indicador                    co2  co2_per_capita
year iso_code country
2000 AUT      Áustria     66.204           8.262
     BEL      Bélgica    126.776          12.366
     BGR      Bulgária    45.499           5.687
     CHN      China     3643.810           2.870
     CYP      Chipre       7.107           7.499

O resultado está organizado por ano–país. Reordenamos os níveis e as linhas antes de comparar com a Series original. Repomos também o nome da Series, que não é automaticamente preservado por esta passagem por um DataFrame.

In [84]:
serie_reposta = serie_reposta.reorder_levels(['iso_code', 'country', 'year']).sort_index()
serie_reposta.head()

indicador                 co2  co2_per_capita
iso_code country year
AUT      Áustria 2000  66.204           8.262
                 2001  70.191           8.728
                 2002  71.988           8.908
                 2003  77.412           9.530
                 2004  77.716           9.508

## 9. `melt`: voltar a uma tabela de indicadores

Partimos de um subconjunto de três países e três anos para que a reorganização seja fácil de acompanhar.

In [85]:
dados.head()

,year,iso_code,country,group,population,co2,co2_per_capita,electricity_demand_twh,fossil_fuels_electricity_twh,low_carbon_electricity_twh
0,2000,AUT,Áustria,UE-27,8012929.0,66.204,8.262,58.27,16.20,43.44
1,2001,AUT,Áustria,UE-27,8042233.0,70.191,8.728,61.20,18.74,42.24
2,2002,AUT,Áustria,UE-27,8081640.0,71.988,8.908,61.33,18.73,41.90
3,2003,AUT,Áustria,UE-27,8122604.0,77.412,9.530,63.58,22.73,35.24
4,2004,AUT,Áustria,UE-27,8173496.0,77.716,9.508,64.93,22.23,39.62

In [86]:
pequeno = dados.loc[
    dados['iso_code'].isin(['PRT', 'USA', 'CHN']) & dados['year'].isin([2000, 2010, 2020]),
    ['iso_code', 'year', 'co2', 'electricity_demand_twh']
].reset_index(drop=True)
pequeno

  iso_code  year        co2  electricity_demand_twh
0      CHN  2000   3643.810                 1346.85
1      CHN  2010   8610.048                 4193.65
2      CHN  2020  10896.521                 7762.03
3      PRT  2000     65.504                   44.14
4      PRT  2010     52.890                   56.10
5      PRT  2020     41.738                   52.85
6      USA  2000   6023.158                 3835.86
7      USA  2010   5669.250                 4139.92
8      USA  2020   4689.954                 4090.49

Os identificadores ficam em `id_vars`; as medidas selecionadas passam a nomes de indicador e valores. As duas medidas têm unidades diferentes: a transformação não as torna comparáveis entre si.

In [87]:
longo = pequeno.melt(
    id_vars=['iso_code', 'year'],
    value_vars=['co2', 'electricity_demand_twh'],
    var_name='indicator', value_name='value'
)
longo

   iso_code  year               indicator      value
0       CHN  2000                     co2   3643.810
1       CHN  2010                     co2   8610.048
2       CHN  2020                     co2  10896.521
3       PRT  2000                     co2     65.504
4       PRT  2010                     co2     52.890
5       PRT  2020                     co2     41.738
6       USA  2000                     co2   6023.158
7       USA  2010                     co2   5669.250
8       USA  2020                     co2   4689.954
9       CHN  2000  electricity_demand_twh   1346.850
10      CHN  2010  electricity_demand_twh   4193.650
11      CHN  2020  electricity_demand_twh   7762.030
12      PRT  2000  electricity_demand_twh     44.140
13      PRT  2010  electricity_demand_twh     56.100
14      PRT  2020  electricity_demand_twh     52.850
15      USA  2000  electricity_demand_twh   3835.860
16      USA  2010  electricity_demand_twh   4139.920
17      USA  2020  electricity_demand_twh   4090.490

### O que distingue as operações?
- `pivot`: reorganiza dados a partir de colunas identificadoras; exige uma única medida por combinação de chaves.
- `melt`: transforma colunas de medidas em linhas de indicador–valor.
- `unstack`: move níveis do índice das linhas para as colunas.
- `stack`: move níveis das colunas para o índice das linhas.
- `.T`: troca os dois eixos completos.

In [88]:
dados.to_csv('energia+co2.csv', index=False)

## 14. Exercícios de consolidação
1. Repita a seleção hierárquica para Espanha em 2010–2020.
2. Coloque os anos nas linhas e apenas Portugal, China e EUA nas colunas para a procura de eletricidade.
3. Construa colunas hierárquicas com ano e indicador, por esta ordem, incluindo população.
4. Compare as duas populações por país e ano. Identifique diferenças sem atribuir uma causa que os ficheiros não documentam.
5. Inspecione as linhas exclusivas da energia em 2025. Explique por que não se deve preencher o CO₂ ausente com zero.
6. Compare `inner` e `outer` em `concat(axis=1)` usando as tabelas indexadas das duas fontes.
7. Experimente retirar um valor de um país da UE numa cópia dos dados. Confirme que a regra de cobertura impede uma soma parcial de aparecer como total do bloco.

## Síntese
Os ficheiros separados justificaram `concat`; as fontes com formatos distintos justificaram `pivot`; a relação entre fontes justificou `merge` e os sufixos. A seleção e a comparação de países/anos justificaram os índices hierárquicos. Por fim, `melt`, `stack` e `unstack` permitiram adaptar a estrutura a diferentes perguntas sem alterar os valores observados.

### Proveniência e limites
Entradas: três CSV de CO₂ em formato largo, três CSV de energia em formato longo e `paises_blocos.csv`, fornecidos com a conversa. Os nomes concretos podem conter sufixos dos anexos; a localização por prefixo trata essa diferença. Não foram obtidos novos dados da Internet. Não se afirmam tendências numéricas sem inspecionar as saídas. A agregação é uma extensão ao percurso de transformação e não substitui uma aula dedicada a regras de agregação e interpretação das unidades.