In [1]:
import pandas as pd

pd.options.display.max_columns = 999

In [2]:
URL = 'https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv'

df = pd.read_csv(URL)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Dicionário das colunas

- `PassengerID` - This is an Unique ID given to every passenger.
- `Survived` - 0 for deceased and 1 for survived
- `Pclass` - Passenger class ranging from 1 to 3
- `Name` - Passenger full name with honorifics
- `Sex` - Male or female
- `Age` - Age of the passenger
- `SibSp` - number of siblings or spouses on board related to the specific passenger
- `Parch` - number of parents or children on board related to the specific passenger
- `Ticket` - Ticket number
- `Fare` - Ticket fare
- `Cabin` - Cabin alloted to the passenger
- `Embarked` - Port of embarkation (C = Cherbourg; Q = Queenstown; S = Southampton)

In [3]:
df.shape

(891, 12)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [5]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [6]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
PassengerId,891.0,NaN,NaN,NaN,446.0,257.353842,1.0,223.5,446.0,668.5,891.0
Survived,891.0,NaN,NaN,NaN,0.383838,0.486592,0.0,0.0,0.0,1.0,1.0
Pclass,891.0,NaN,NaN,NaN,2.308642,0.836071,1.0,2.0,3.0,3.0,3.0
Name,891,891,"Braund, Mr. Owen Harris",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sex,891,2,male,577,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,714.0,NaN,NaN,NaN,29.699118,14.526497,0.42,20.125,28.0,38.0,80.0
SibSp,891.0,NaN,NaN,NaN,0.523008,1.102743,0.0,0.0,0.0,1.0,8.0
Parch,891.0,NaN,NaN,NaN,0.381594,0.806057,0.0,0.0,0.0,0.0,6.0
Ticket,891,681,347082,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fare,891.0,NaN,NaN,NaN,32.204208,49.693429,0.0,7.9104,14.4542,31.0,512.3292
Cabin,204,147,G6,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Embarked,889,3,S,644,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Valores em Falta

In [7]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
df[df.isna().any(axis=1)].loc[60:65]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
60,61,0,3,"Sirayanian, Mr. Orsen",male,22.0,0,0,2669,7.2292,NaN,C
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0000,B28,NaN
63,64,0,3,"Skoog, Master. Harald",male,4.0,3,2,347088,27.9000,NaN,S
64,65,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,27.7208,NaN,C
65,66,1,3,"Moubarek, Master. Gerios",male,NaN,1,1,2661,15.2458,NaN,C

In [9]:
df.isna().mean()*100

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [10]:
df1 = df.dropna()
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

In [11]:
df1.shape

(183, 12)

In [12]:
df1.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

## Coluna `Embarked`

tem $\approx$ 0.2% de valores em falta

In [13]:
df[df['Embarked'].isna()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,B28,NaN
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,B28,NaN

In [14]:
df2 = df.copy()

In [15]:
df2['Embarked'].unique()

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [16]:
df2['Embarked'] = df2['Embarked'].fillna('Unkown')

In [17]:
df2['Embarked'].unique()

<StringArray>
['S', 'C', 'Q', 'Unkown']
Length: 4, dtype: str

In [18]:
df = df.dropna(subset='Embarked')

In [19]:
df.shape

(889, 12)

## Coluna `Age`

In [20]:
df[df['Age'].isna()].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q

In [21]:
df['Age'].mean()

np.float64(29.64209269662921)

In [22]:
df['Age'].median()

np.float64(28.0)

In [23]:
df['Age'].mode()

0    24.0
Name: Age, dtype: float64

In [24]:
df3 = df.copy()

In [25]:
mediana = df['Age'].median()
df3['Age'] = df3['Age'].fillna(mediana)

In [26]:
df3['Age'].isna().sum()

np.int64(0)

In [27]:
df3['Age'].median(), df3['Age'].mean()

(np.float64(28.0), np.float64(29.315151856017994))

In [28]:
df.groupby('Sex')['Age'].median()

Sex
female    27.0
male      29.0
Name: Age, dtype: float64

In [29]:
df.groupby('Pclass')['Age'].median()

Pclass
1    37.0
2    29.0
3    24.0
Name: Age, dtype: float64

In [30]:
df.groupby(['Sex', 'Pclass'])['Age'].median()

Sex     Pclass
female  1         35.0
        2         28.0
        3         21.5
male    1         40.0
        2         30.0
        3         25.0
Name: Age, dtype: float64

In [31]:
median_age_pclass = df.groupby(['Sex', 'Pclass'])['Age'].transform('median')
median_age_pclass

0      25.0
1      35.0
2      21.5
3      35.0
4      25.0
       ...
886    30.0
887    35.0
888    21.5
889    40.0
890    25.0
Name: Age, Length: 889, dtype: float64

In [32]:
df['Age'] = df['Age'].fillna(median_age_pclass)

In [33]:
df['Age'].isna().sum()

np.int64(0)

In [34]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [35]:
df['Age'].median()

np.float64(26.0)

In [36]:
df.groupby(['Sex', 'Pclass'])['Age'].describe()

               count       mean        std   min    25%   50%    75%   max
Sex    Pclass
female 1        92.0  34.315217  12.751151  2.00  24.00  35.0  42.25  63.0
       2        76.0  28.703947  12.700440  2.00  22.75  28.0  36.00  57.0
       3       144.0  21.677083  10.699032  0.75  18.00  21.5  26.00  63.0
male   1       122.0  41.060820  13.771814  0.92  33.25  40.0  49.00  80.0
       2       108.0  30.678981  14.159550  0.67  23.00  30.0  36.00  70.0
       3       347.0  26.099193  10.398827  0.42  21.00  25.0  30.00  74.0

## Coluna `Cabin`

In [37]:
df.isna().mean()*100

PassengerId     0.00000
Survived        0.00000
Pclass          0.00000
Name            0.00000
Sex             0.00000
Age             0.00000
SibSp           0.00000
Parch           0.00000
Ticket          0.00000
Fare            0.00000
Cabin          77.27784
Embarked        0.00000
dtype: float64

In [38]:
df['Cabin']

0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ...
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 889, dtype: str

In [39]:
df['Cabin'].unique()

<StringArray>
[          nan,         'C85',        'C123',         'E46',          'G6',
        'C103',         'D56',          'A6', 'C23 C25 C27',         'B78',
 ...
        'B102',         'B69',         'E49',         'C47',         'D28',
         'E17',         'A24',         'C50',         'B42',        'C148']
Length: 147, dtype: str

In [40]:
df.groupby('Pclass')['Cabin'].apply(lambda x: x.isna().mean())*100

Pclass
1    18.691589
2    91.304348
3    97.556008
Name: Cabin, dtype: float64

In [41]:
df4 = df.copy()

In [42]:
df4 = df4.drop('Cabin', axis=1)
df4.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [43]:
df['HasCabin'] = df['Cabin'].notna().astype(int)
df = df.drop('Cabin', axis=1)          # df.drop(columns=['Cabin'])
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,HasCabin
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0

# Dados duplicados

In [46]:
df.duplicated().sum()

np.int64(0)

In [47]:
df.duplicated(subset='PassengerId').sum()

np.int64(0)

In [48]:
df.duplicated(subset='Ticket').sum()

np.int64(209)

In [51]:
df[df.duplicated(subset='Ticket', keep=False)].sort_values(by='Ticket').head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,HasCabin
257,258,1,1,"Cherry, Miss. Gladys",female,30.0,0,0,110152,86.5000,S,1
759,760,1,1,"Rothes, the Countess. of (Lucy Noel Martha Dye...",female,33.0,0,0,110152,86.5000,S,1
504,505,1,1,"Maioni, Miss. Roberta",female,16.0,0,0,110152,86.5000,S,1
558,559,1,1,"Taussig, Mrs. Emil (Tillie Mandelbaum)",female,39.0,1,1,110413,79.6500,S,1
585,586,1,1,"Taussig, Miss. Ruth",female,18.0,0,2,110413,79.6500,S,1
262,263,0,1,"Taussig, Mr. Emil",male,52.0,1,1,110413,79.6500,S,1
475,476,0,1,"Clifford, Mr. George Quincy",male,40.0,0,0,110465,52.0000,S,1
110,111,0,1,"Porter, Mr. Walter Chamberlain",male,47.0,0,0,110465,52.0000,S,1
523,524,1,1,"Hippach, Mrs. Louis Albert (Ida Sophia Fischer)",female,44.0,0,1,111361,57.9792,C,1
329,330,1,1,"Hippach, Miss. Jean Gertrude",female,16.0,0,1,111361,57.9792,C,1

# Coluna `Embarked`

In [53]:
df['Embarked'].unique()

<StringArray>
['S', 'C', 'Q']
Length: 3, dtype: str

In [54]:
df['Embarked'] = df['Embarked'].astype('category')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,HasCabin
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0

In [55]:
df.info()

<class 'pandas.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  889 non-null    int64
 1   Survived     889 non-null    int64
 2   Pclass       889 non-null    int64
 3   Name         889 non-null    str
 4   Sex          889 non-null    str
 5   Age          889 non-null    float64
 6   SibSp        889 non-null    int64
 7   Parch        889 non-null    int64
 8   Ticket       889 non-null    str
 9   Fare         889 non-null    float64
 10  Embarked     889 non-null    category
 11  HasCabin     889 non-null    int64
dtypes: category(1), float64(2), int64(6), str(3)
memory usage: 84.2 KB

In [56]:
df['Embarked'].cat.codes

0      2
1      0
2      2
3      2
4      2
      ..
886    2
887    2
888    2
889    0
890    1
Length: 889, dtype: int8

In [57]:
df['Embarked'].cat.categories

Index(['C', 'Q', 'S'], dtype='str')

In [58]:
ports = {'S': 'Southampton', 'C': 'Cherburg', 'Q': 'Queenstown'}
df['Embarked'] = df['Embarked'].cat.rename_categories(ports)
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,HasCabin
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Southampton,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,Cherburg,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Southampton,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,Southampton,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Southampton,0
5,6,0,3,"Moran, Mr. James",male,25.0,0,0,330877,8.4583,Queenstown,0
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,Southampton,1
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,Southampton,0
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,Southampton,0
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,Cherburg,0

In [59]:
df['Embarked'].cat.codes

0      2
1      0
2      2
3      2
4      2
      ..
886    2
887    2
888    2
889    0
890    1
Length: 889, dtype: int8

In [60]:
df['Embarked'].value_counts()

Embarked
Southampton    644
Cherburg       168
Queenstown      77
Name: count, dtype: int64

In [61]:
df['Sex'].unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [62]:
df['Sex'] = df['Sex'].str.strip().str.lower()

In [63]:
df['Sex'] = df['Sex'].replace({'male': 'Male', 'female': 'Female'})
df['Sex'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [64]:
df['Sex'] = df['Sex'].astype('category')

In [65]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,HasCabin
0,1,0,3,"Braund, Mr. Owen Harris",Male,22.0,1,0,A/5 21171,7.2500,Southampton,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Female,38.0,1,0,PC 17599,71.2833,Cherburg,1
2,3,1,3,"Heikkinen, Miss. Laina",Female,26.0,0,0,STON/O2. 3101282,7.9250,Southampton,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Female,35.0,1,0,113803,53.1000,Southampton,1
4,5,0,3,"Allen, Mr. William Henry",Male,35.0,0,0,373450,8.0500,Southampton,0

In [66]:
df['Sex'].value_counts()

Sex
Male      577
Female    312
Name: count, dtype: int64

# Outliers

In [67]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,HasCabin
count,889.000000,889.000000,889.000000,889.000000,889.000000,889.000000,889.000000,889.000000
mean,446.000000,0.382452,2.311586,29.065433,0.524184,0.382452,32.096681,0.227222
std,256.998173,0.486260,0.834700,13.270162,1.103705,0.806761,49.697504,0.419273
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000,0.000000
25%,224.000000,0.000000,2.000000,21.500000,0.000000,0.000000,7.895800,0.000000
50%,446.000000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200,0.000000
75%,668.000000,1.000000,3.000000,36.000000,1.000000,0.000000,31.000000,0.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200,1.000000

In [69]:
cols = ['Age', 'SibSp', 'Parch', 'Fare']

Q1 = df[cols].quantile(0.25)
Q1

Age      21.5000
SibSp     0.0000
Parch     0.0000
Fare      7.8958
Name: 0.25, dtype: float64

In [70]:
Q3 = df[cols].quantile(0.75)
Q3

Age      36.0
SibSp     1.0
Parch     0.0
Fare     31.0
Name: 0.75, dtype: float64

In [71]:
IQR = Q3 - Q1
IQR

Age      14.5000
SibSp     1.0000
Parch     0.0000
Fare     23.1042
dtype: float64

In [72]:
limite_inferior = Q1 - 1.5*IQR
limite_inferior

Age      -0.2500
SibSp    -1.5000
Parch     0.0000
Fare    -26.7605
dtype: float64

In [73]:
limite_superior = Q3 + 1.5*IQR
limite_superior

Age      57.7500
SibSp     2.5000
Parch     0.0000
Fare     65.6563
dtype: float64

In [78]:
col = 'SibSp'
df[df[col] < limite_inferior[col]]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Embarked, HasCabin]
Index: []

In [79]:
df[df[col] > limite_superior[col]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,HasCabin
7,8,0,3,"Palsson, Master. Gosta Leonard",Male,2.0,3,1,349909,21.0750,Southampton,0
16,17,0,3,"Rice, Master. Eugene",Male,2.0,4,1,382652,29.1250,Queenstown,0
24,25,0,3,"Palsson, Miss. Torborg Danira",Female,8.0,3,1,349909,21.0750,Southampton,0
27,28,0,1,"Fortune, Mr. Charles Alexander",Male,19.0,3,2,19950,263.0000,Southampton,1
50,51,0,3,"Panula, Master. Juha Niilo",Male,7.0,4,1,3101295,39.6875,Southampton,0
59,60,0,3,"Goodwin, Master. William Frederick",Male,11.0,5,2,CA 2144,46.9000,Southampton,0
63,64,0,3,"Skoog, Master. Harald",Male,4.0,3,2,347088,27.9000,Southampton,0
68,69,1,3,"Andersson, Miss. Erna Alexandra",Female,17.0,4,2,3101281,7.9250,Southampton,0
71,72,0,3,"Goodwin, Miss. Lillian Amy",Female,16.0,5,2,CA 2144,46.9000,Southampton,0
85,86,1,3,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...",Female,33.0,3,0,3101278,15.8500,Southampton,0
88,89,1,1,"Fortune, Miss. Mabel Helen",Female,23.0,3,2,19950,263.0000,Southampton,1
119,120,0,3,"Andersson, Miss. Ellis Anna Maria",Female,2.0,4,2,347082,31.2750,Southampton,0
159,160,0,3,"Sage, Master. Thomas Henry",Male,25.0,8,2,CA. 2343,69.5500,Southampton,0
164,165,0,3,"Panula, Master. Eino Viljami",Male,1.0,4,1,3101295,39.6875,Southampton,0
171,172,0,3,"Rice, Master. Arthur",Male,4.0,4,1,382652,29.1250,Queenstown,0
176,177,0,3,"Lefebre, Master. Henry Forbes",Male,25.0,3,1,4133,25.4667,Southampton,0
180,181,0,3,"Sage, Miss. Constance Gladys",Female,21.5,8,2,CA. 2343,69.5500,Southampton,0
182,183,0,3,"Asplund, Master. Clarence Gustaf Hugo",Male,9.0,4,2,347077,31.3875,Southampton,0
201,202,0,3,"Sage, Mr. Frederick",Male,25.0,8,2,CA. 2343,69.5500,Southampton,0
229,230,0,3,"Lefebre, Miss. Mathilde",Female,21.5,3,1,4133,25.4667,Southampton,0
233,234,1,3,"Asplund, Miss. Lillian Gertrud",Female,5.0,4,2,347077,31.3875,Southampton,0
261,262,1,3,"Asplund, Master. Edvin Rojj Felix",Male,3.0,4,2,347077,31.3875,Southampton,0
266,267,0,3,"Panula, Mr. Ernesti Arvid",Male,16.0,4,1,3101295,39.6875,Southampton,0
278,279,0,3,"Rice, Master. Eric",Male,7.0,4,1,382652,29.1250,Queenstown,0
324,325,0,3,"Sage, Mr. George John Jr",Male,25.0,8,2,CA. 2343,69.5500,Southampton,0
341,342,1,1,"Fortune, Miss. Alice Elizabeth",Female,24.0,3,2,19950,263.0000,Southampton,1
374,375,0,3,"Palsson, Miss. Stina Viola",Female,3.0,3,1,349909,21.0750,Southampton,0
386,387,0,3,"Goodwin, Master. Sidney Leonard",Male,1.0,5,2,CA 2144,46.9000,Southampton,0
409,410,0,3,"Lefebre, Miss. Ida",Female,21.5,3,1,4133,25.4667,Southampton,0
480,481,0,3,"Goodwin, Master. Harold Victor",Male,9.0,5,2,CA 2144,46.9000,Southampton,0
485,486,0,3,"Lefebre, Miss. Jeannie",Female,21.5,3,1,4133,25.4667,Southampton,0
541,542,0,3,"Andersson, Miss. Ingeborg Constanzia",Female,9.0,4,2,347082,31.2750,Southampton,0
542,543,0,3,"Andersson, Miss. Sigrid Elisabeth",Female,11.0,4,2,347082,31.2750,Southampton,0
634,635,0,3,"Skoog, Miss. Mabel",Female,9.0,3,2,347088,27.9000,Southampton,0
642,643,0,3,"Skoog, Miss. Margit Elizabeth",Female,2.0,3,2,347088,27.9000,Southampton,0
683,684,0,3,"Goodwin, Mr. Charles Edward",Male,14.0,5,2,CA 2144,46.9000,Southampton,0
686,687,0,3,"Panula, Mr. Jaako Arnold",Male,14.0,4,1,3101295,39.6875,Southampton,0
726,727,1,2,"Renouf, Mrs. Peter Henry (Lillian Jefferys)",Female,30.0,3,0,31027,21.0000,Southampton,0
787,788,0,3,"Rice, Master. George Hugh",Male,8.0,4,1,382652,29.1250,Queenstown,0
792,793,0,3,"Sage, Miss. Stella Anna",Female,21.5,8,2,CA. 2343,69.5500,Southampton,0
813,814,0,3,"Andersson, Miss. Ebba Iris Alfrida",Female,6.0,4,2,347082,31.2750,Southampton,0
819,820,0,3,"Skoog, Master. Karl Thorsten",Male,10.0,3,2,347088,27.9000,Southampton,0
824,825,0,3,"Panula, Master. Urho Abraham",Male,2.0,4,1,3101295,39.6875,Southampton,0
846,847,0,3,"Sage, Mr. Douglas Bullen",Male,25.0,8,2,CA. 2343,69.5500,Southampton,0
850,851,0,3,"Andersson, Master. Sigvard Harald Elias",Male,4.0,4,2,347082,31.2750,Southampton,0
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",Female,21.5,8,2,CA. 2343,69.5500,Southampton,0

In [80]:
df[ (df[col] < limite_inferior[col]) | (df[col] > limite_superior[col]) ]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,HasCabin
7,8,0,3,"Palsson, Master. Gosta Leonard",Male,2.0,3,1,349909,21.0750,Southampton,0
16,17,0,3,"Rice, Master. Eugene",Male,2.0,4,1,382652,29.1250,Queenstown,0
24,25,0,3,"Palsson, Miss. Torborg Danira",Female,8.0,3,1,349909,21.0750,Southampton,0
27,28,0,1,"Fortune, Mr. Charles Alexander",Male,19.0,3,2,19950,263.0000,Southampton,1
50,51,0,3,"Panula, Master. Juha Niilo",Male,7.0,4,1,3101295,39.6875,Southampton,0
59,60,0,3,"Goodwin, Master. William Frederick",Male,11.0,5,2,CA 2144,46.9000,Southampton,0
63,64,0,3,"Skoog, Master. Harald",Male,4.0,3,2,347088,27.9000,Southampton,0
68,69,1,3,"Andersson, Miss. Erna Alexandra",Female,17.0,4,2,3101281,7.9250,Southampton,0
71,72,0,3,"Goodwin, Miss. Lillian Amy",Female,16.0,5,2,CA 2144,46.9000,Southampton,0
85,86,1,3,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...",Female,33.0,3,0,3101278,15.8500,Southampton,0
88,89,1,1,"Fortune, Miss. Mabel Helen",Female,23.0,3,2,19950,263.0000,Southampton,1
119,120,0,3,"Andersson, Miss. Ellis Anna Maria",Female,2.0,4,2,347082,31.2750,Southampton,0
159,160,0,3,"Sage, Master. Thomas Henry",Male,25.0,8,2,CA. 2343,69.5500,Southampton,0
164,165,0,3,"Panula, Master. Eino Viljami",Male,1.0,4,1,3101295,39.6875,Southampton,0
171,172,0,3,"Rice, Master. Arthur",Male,4.0,4,1,382652,29.1250,Queenstown,0
176,177,0,3,"Lefebre, Master. Henry Forbes",Male,25.0,3,1,4133,25.4667,Southampton,0
180,181,0,3,"Sage, Miss. Constance Gladys",Female,21.5,8,2,CA. 2343,69.5500,Southampton,0
182,183,0,3,"Asplund, Master. Clarence Gustaf Hugo",Male,9.0,4,2,347077,31.3875,Southampton,0
201,202,0,3,"Sage, Mr. Frederick",Male,25.0,8,2,CA. 2343,69.5500,Southampton,0
229,230,0,3,"Lefebre, Miss. Mathilde",Female,21.5,3,1,4133,25.4667,Southampton,0
233,234,1,3,"Asplund, Miss. Lillian Gertrud",Female,5.0,4,2,347077,31.3875,Southampton,0
261,262,1,3,"Asplund, Master. Edvin Rojj Felix",Male,3.0,4,2,347077,31.3875,Southampton,0
266,267,0,3,"Panula, Mr. Ernesti Arvid",Male,16.0,4,1,3101295,39.6875,Southampton,0
278,279,0,3,"Rice, Master. Eric",Male,7.0,4,1,382652,29.1250,Queenstown,0
324,325,0,3,"Sage, Mr. George John Jr",Male,25.0,8,2,CA. 2343,69.5500,Southampton,0
341,342,1,1,"Fortune, Miss. Alice Elizabeth",Female,24.0,3,2,19950,263.0000,Southampton,1
374,375,0,3,"Palsson, Miss. Stina Viola",Female,3.0,3,1,349909,21.0750,Southampton,0
386,387,0,3,"Goodwin, Master. Sidney Leonard",Male,1.0,5,2,CA 2144,46.9000,Southampton,0
409,410,0,3,"Lefebre, Miss. Ida",Female,21.5,3,1,4133,25.4667,Southampton,0
480,481,0,3,"Goodwin, Master. Harold Victor",Male,9.0,5,2,CA 2144,46.9000,Southampton,0
485,486,0,3,"Lefebre, Miss. Jeannie",Female,21.5,3,1,4133,25.4667,Southampton,0
541,542,0,3,"Andersson, Miss. Ingeborg Constanzia",Female,9.0,4,2,347082,31.2750,Southampton,0
542,543,0,3,"Andersson, Miss. Sigrid Elisabeth",Female,11.0,4,2,347082,31.2750,Southampton,0
634,635,0,3,"Skoog, Miss. Mabel",Female,9.0,3,2,347088,27.9000,Southampton,0
642,643,0,3,"Skoog, Miss. Margit Elizabeth",Female,2.0,3,2,347088,27.9000,Southampton,0
683,684,0,3,"Goodwin, Mr. Charles Edward",Male,14.0,5,2,CA 2144,46.9000,Southampton,0
686,687,0,3,"Panula, Mr. Jaako Arnold",Male,14.0,4,1,3101295,39.6875,Southampton,0
726,727,1,2,"Renouf, Mrs. Peter Henry (Lillian Jefferys)",Female,30.0,3,0,31027,21.0000,Southampton,0
787,788,0,3,"Rice, Master. George Hugh",Male,8.0,4,1,382652,29.1250,Queenstown,0
792,793,0,3,"Sage, Miss. Stella Anna",Female,21.5,8,2,CA. 2343,69.5500,Southampton,0
813,814,0,3,"Andersson, Miss. Ebba Iris Alfrida",Female,6.0,4,2,347082,31.2750,Southampton,0
819,820,0,3,"Skoog, Master. Karl Thorsten",Male,10.0,3,2,347088,27.9000,Southampton,0
824,825,0,3,"Panula, Master. Urho Abraham",Male,2.0,4,1,3101295,39.6875,Southampton,0
846,847,0,3,"Sage, Mr. Douglas Bullen",Male,25.0,8,2,CA. 2343,69.5500,Southampton,0
850,851,0,3,"Andersson, Master. Sigvard Harald Elias",Male,4.0,4,2,347082,31.2750,Southampton,0
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",Female,21.5,8,2,CA. 2343,69.5500,Southampton,0

In [82]:
df[  df['Name'].str.contains('Sage')  ]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,HasCabin
159,160,0,3,"Sage, Master. Thomas Henry",Male,25.0,8,2,CA. 2343,69.55,Southampton,0
180,181,0,3,"Sage, Miss. Constance Gladys",Female,21.5,8,2,CA. 2343,69.55,Southampton,0
201,202,0,3,"Sage, Mr. Frederick",Male,25.0,8,2,CA. 2343,69.55,Southampton,0
324,325,0,3,"Sage, Mr. George John Jr",Male,25.0,8,2,CA. 2343,69.55,Southampton,0
641,642,1,1,"Sagesser, Mlle. Emma",Female,24.0,0,0,PC 17477,69.30,Cherburg,1
792,793,0,3,"Sage, Miss. Stella Anna",Female,21.5,8,2,CA. 2343,69.55,Southampton,0
846,847,0,3,"Sage, Mr. Douglas Bullen",Male,25.0,8,2,CA. 2343,69.55,Southampton,0
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",Female,21.5,8,2,CA. 2343,69.55,Southampton,0

In [83]:
df[ df['Ticket'] == 'CA. 2343' ]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,HasCabin
159,160,0,3,"Sage, Master. Thomas Henry",Male,25.0,8,2,CA. 2343,69.55,Southampton,0
180,181,0,3,"Sage, Miss. Constance Gladys",Female,21.5,8,2,CA. 2343,69.55,Southampton,0
201,202,0,3,"Sage, Mr. Frederick",Male,25.0,8,2,CA. 2343,69.55,Southampton,0
324,325,0,3,"Sage, Mr. George John Jr",Male,25.0,8,2,CA. 2343,69.55,Southampton,0
792,793,0,3,"Sage, Miss. Stella Anna",Female,21.5,8,2,CA. 2343,69.55,Southampton,0
846,847,0,3,"Sage, Mr. Douglas Bullen",Male,25.0,8,2,CA. 2343,69.55,Southampton,0
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",Female,21.5,8,2,CA. 2343,69.55,Southampton,0