# Introdução ao `pandas`

O pandas é a livraria _quasi-standart_ para trabalhar com dados, utiliazando o Python, pois implementa praticamente todas as funções necessárias para trabalhar, analisar e manipular os dados. No site do [pandas](https://pandas.pydata.org/) está a seguinte frase, que resume o conceito da livraria:

> _pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language_.

Antes de se utilizar esta livraria, é necessário fazer a sua importação. A forma normal de importar o pandas é a fazer a importação com o alias `pd`.

In [3]:
import pandas as pd

pd.options.display.max_columns = 999

O `pandas` possui duas estruturas básicas para armazenar a informação: `Series` e `DataFrame`.

## `Series`

No `pandas`, a estrutura `Series` é uma estrutura unidimensional, e o seu conteúdo, apesar de poder ser de tipos diferentes, é normalmente sempre do mesmo tipo.

A forma mais elementar de criar `Series`, é passar uma lista com os valores de cada elemento:

In [12]:
nums = pd.Series([0, 0.25, 0.5, 0.75, 2])
nums

0    0.00
1    0.25
2    0.50
3    0.75
4    2.00
dtype: float64

Pode-se ver que, ao contrário do que foi dito anteriormente, a `Series` parece que é bidimensional, mas é apenas a forma da estrutura ser apresentada, pois para além da sequência de valores, contém também um índice inteiro, entre `0` e `N-1` (onde `N` corresponde ao número de elementos). Pode-se aceder a cada uma destas sequências utilizando os atributos `values` e `index`.

In [8]:
nums.values

array([0.  , 0.25, 0.5 , 0.75, 2.  ])

In [9]:
nums.index

RangeIndex(start=0, stop=5, step=1)

E pode-se aceder aos elementos utilizando a forma normal do Python, através de parênteses retos, apesar de exigir alguma atenção, como veremos adiante.

In [10]:
nums[2]

np.float64(0.5)

In [11]:
nums[1:3]

1    0.25
2    0.50
dtype: float64

In [7]:
nums[4] = 1
nums

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

Mas ao contrário das listas do Python ou dos `arrays` do Numpy, cujos indices são sempre numéricos, nas `Series` os  índices podem ser definidos, passando uma lista com os índices no argumento `index`.

In [8]:
songs = pd.Series([145, 142, 38, 13], index=['Paul', 'John', 'George', 'Ringo'], name='counts')
songs

Paul      145
John      142
George     38
Ringo      13
Name: counts, dtype: int64

E claro que agora podemos utilizar esses índices para aceder aos elementos:

In [9]:
songs['Paul']

np.int64(145)

E eventualmente, adicionar novas linhas aos dados:

In [10]:
songs['Anonymous'] = 0
songs

Paul         145
John         142
George        38
Ringo         13
Anonymous      0
Name: counts, dtype: int64

### `Series` como dicionários especializados

De certa forma, pode-se pensar numa `Series` como se fosse uma forma especializada de um dicionário do Python. Enquanto um dicionário faz o mapeamento entre chaves e valores arbitrários, uma `Series` é uma estrutura que faz o mapeamento entre chaves de um determinado tipo e valores de um determinado tipo. A definição do tipo é importante, pois é isso que permite uma maior eficiência desta estrutura em certas operações.

A analogia entre `Series` e dicionários pode ser ainda mais evidente se se considerar que se pode criar diretamente uma `Series` a partir de um dicionário, sendo as chaves os índices da `Series`.

In [11]:
population_dict = {
    'Nova Iorque': 20201249,
    'Florida': 21538187,
    'Pensilvania': 13002700,
    'California': 39538223,
    'Texas': 29145505,
}

In [12]:
population = pd.Series(population_dict, name='population')
population

Nova Iorque    20201249
Florida        21538187
Pensilvania    13002700
California     39538223
Texas          29145505
Name: population, dtype: int64

Quando se utiliza um dicionário como base, a ordem dos elementos será de acordo com a ordem das chaves no dicionário, que por sua vez depende da ordem de inserção no mesmo. Isso pode ser definido utilizando o parametro `index`, passando quais as chaves que devem ser utilizadas, e em que ordem devem aparecer.

In [13]:
states_list = ['California', 'Florida', 'Ohio', 'Texas']
pop2 = pd.Series(population_dict, index=states_list)
pop2

California    39538223.0
Florida       21538187.0
Ohio                 NaN
Texas         29145505.0
dtype: float64

Três coisas podem-se observar neste exemplo:

1. as chaves que existiam no dicionário, mas que não foram indicadas no `index`, não aparecem na `Series`;
2. as chaves que foram indicadas no `index`, mas não não existem no dicionário vão conter o valor `NaN`;
3. por outro lado, enquanto no primeiro exemplo o tipo de dados foi `int64` porque todos os valores eram inteiros, neste último exemplo, devido à necessidade do pandas utilizar o `NaN`, o tipo é `float64`, pois este tipo suporta `NaN` enquanto `int64` não suporta.

`NaN` (_Not a Number_) é um valor definido no numpy para indicar valores em falta, ou `NA`, ou `None`, sendo que o pandas ignora estes valores em muitas das suas operações. Por exemplo, vamos comparar o método `.count` que conta os valores existentes na `Series`, com a propriedade `.size`, que contém o numero de entradas (incluindo valores em falta):

In [14]:
pop2.size

4

In [15]:
pop2.count()

np.int64(3)

Uma `Series` pode ser transformada num dicionário utilizando o método `.to_dict()`.

In [16]:
pop2.to_dict()

{'California': 39538223.0,
 'Florida': 21538187.0,
 'Ohio': nan,
 'Texas': 29145505.0}

Ou numa lista com o método `.to_list()`, sendo que neste caso apenas os valores serão devolvidos.

In [17]:
population.to_list()

[20201249, 21538187, 13002700, 39538223, 29145505]

In [18]:
population.values

array([20201249, 21538187, 13002700, 39538223, 29145505])

### Filtrar elementos

De forma similar ao Numpy (que o pandas utiliza no _background_), pode-se selecionar os elementos de uma `Series` passando a lista de índices que se pretende:

In [19]:
nums = pd.Series([45, 123, 76, 98, 212])
nums

0     45
1    123
2     76
3     98
4    212
dtype: int64

In [20]:
nums[2]

np.int64(76)

In [21]:
nums[1:3]

1    123
2     76
dtype: int64

In [22]:
nums[[0,3,4]]

0     45
3     98
4    212
dtype: int64

E também se pode selecionar elementos utilizando _arrays_ booleanos, como por exemplo:

In [23]:
nums > 100
mask = nums > 100
mask

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [24]:
nums[mask]

1    123
4    212
dtype: int64

Normalmente, e quando possivel, combina-se estas linhas numa única:

In [25]:
nums[nums > 100]

1    123
4    212
dtype: int64

### Categorias

Quando se sabe que a diversidade dos dados está limitada a apenas uns quantos valores diferentes, pode-se utilizar categorias, que têm alguns beneficios:

* Utilizam menos memória do que _strings_
* Tem maior performance
* Podem ser ordenadas
* Pode-se realizar operações nas categorias
* Impor a pertença aos valores

Para criar uma categoria é preciso passar o argumento `dtype='category'` no construtor da `Series`, ou então utilizar o método `astype` a uma `Series` já criada, passando o valor `'category'`.

In [26]:
sizes_list = ['XS', 'M', 'XL', 'L', 'S']
sizes = pd.Series(sizes_list, dtype='category')
sizes

0    XS
1     M
2    XL
3     L
4     S
dtype: category
Categories (5, str): ['L', 'M', 'S', 'XL', 'XS']

Como se pode ver, a `Series` é uma categoria, com 5 elementos.

Se a categoria representa um tamanho, a ordem pode ser importante, mas por defeito as categorias não têm nenhuma ordem, como se pode ser observando o atributo `.cat`, que contêm algumas propriedades.

In [27]:
sizes.cat.*?

sizes.cat.__annotations__
sizes.cat.__class__
sizes.cat.__delattr__
sizes.cat.__dict__
sizes.cat.__dir__
sizes.cat.__doc__
sizes.cat.__eq__
sizes.cat.__firstlineno__
sizes.cat.__format__
sizes.cat.__frozen
sizes.cat.__ge__
sizes.cat.__getattribute__
sizes.cat.__getstate__
sizes.cat.__gt__
sizes.cat.__hash__
sizes.cat.__init__
sizes.cat.__init_subclass__
sizes.cat.__le__
sizes.cat.__lt__
sizes.cat.__module__
sizes.cat.__ne__
sizes.cat.__new__
sizes.cat.__reduce__
sizes.cat.__reduce_ex__
sizes.cat.__repr__
sizes.cat.__setattr__
sizes.cat.__sizeof__
sizes.cat.__static_attributes__
sizes.cat.__str__
sizes.cat.__subclasshook__
sizes.cat.__weakref__
sizes.cat.add_categories
sizes.cat.as_ordered
sizes.cat.as_unordered
sizes.cat.categories
sizes.cat.codes
sizes.cat.ordered
sizes.cat.remove_categories
sizes.cat.remove_unused_categories
sizes.cat.rename_categories
sizes.cat.reorder_categories
sizes.cat.set_categories

In [28]:
sizes.cat.ordered

False

A forma mais simples de criar categorias ordenadas, em vez de passar o argumento `'category'` na criação da `Series`, é definir um novo tipo, utilizando o tipo `CategoricalDtype`, com `ordered=True`.

In [29]:
sizes_cat = pd.CategoricalDtype(['S', 'M', 'L'], ordered=True)
sizes2 = pd.Series(sizes_list, dtype=sizes_cat)
sizes2

C:\Users\pmguerre\AppData\Local\Temp\ipykernel_27096\4076911138.py:2: Pandas4Warning: Constructing a Categorical with a dtype and values containing non-null entries not in that dtype's categories is deprecated and will raise in a future version.
  sizes2 = pd.Series(sizes_list, dtype=sizes_cat)

0    NaN
1      M
2    NaN
3      L
4      S
dtype: category
Categories (3, str): ['S' < 'M' < 'L']

Quando as categorias têm uma ordem, pode-se efetuar comparações.

In [30]:
sizes2 >= 'M'

0    False
1     True
2    False
3     True
4    False
dtype: bool

Outra forma de criar uma ordem nas categorias é utilizar o método `.reorder_categories()` a uma categoria existente. Mas atenção que desta forma é necessário indicar todos os membros da categoria, caso contrário irá ocorrer um `ValueError`.

In [31]:
sizes3 = sizes.cat.reorder_categories(['XS', 'S', 'M', 'L', 'XL'], ordered=True)
sizes3

0    XS
1     M
2    XL
3     L
4     S
dtype: category
Categories (5, str): ['XS' < 'S' < 'M' < 'L' < 'XL']

In [32]:
sizes3 >= 'L'

0    False
1    False
2     True
3     True
4    False
dtype: bool

## `DataFrame`

O `DataFrame` é a outra estrutura básica do pandas, e pode ser vista como uma tabela rectangular de dados, contendo uma coleção ordenada de colunas com nomes, onde cada coluna pode conter valores de diferentes tipos.

Se uma `Series` é análoga a uma estrutura uni-dimensional com índices explícitos, um `DataFrame` é análogo a uma estrutura bidimensional, com índices para as linhas e para as colunas explícitos.

Um `DataFrame` pode ser vista como uma sequencia de `Series` alinhadas, i.e., todas as `Series` partilham o mesmo índice.

<div class="alert alert-block alert-info">
<p>ℹ️<b>Nota</b></p><p>Olhar para um <code>DataFrame</code> como um conjunto de linhas vai parecer "esquisito", pois a sintaxe de utilização não é muito coerente com essa forma de pensar. Será mais correto pensar num <code>DataFrame</code> como um conjunto de colunas, onde cada coluna é uma <code>Series</code></p>
</div>

Existem várias formas de criar um `DataFrame`, uma das mais comuns é utilizar um dicionário de listas do mesmo tamanho.

In [33]:
data = {
    'nome': ['Ricardo', 'Ana Rita', 'Patricia', 'José', 'Inês', 'João'],
    'alt': [1.78, 1.67, 1.87, 1.74, 1.79, 1.9],
    'num': [1234, 7634, 3433, 4234, 6543, 4321]
}

O `DataFrame` resultante terá o índice automático (como nas `Series`), e as colunas aparecem na ordem das chaves no dicionário.

In [34]:
df = pd.DataFrame(data)
print(df)
df

       nome   alt   num
0   Ricardo  1.78  1234
1  Ana Rita  1.67  7634
2  Patricia  1.87  3433
3      José  1.74  4234
4      Inês  1.79  6543
5      João  1.90  4321

       nome   alt   num
0   Ricardo  1.78  1234
1  Ana Rita  1.67  7634
2  Patricia  1.87  3433
3      José  1.74  4234
4      Inês  1.79  6543
5      João  1.90  4321

Caso de indique uma lista de colunas, elas irão aparecer nessa ordem, e caso o nome indicado não exista no dicionário, irá aparecer como valores em falta.

In [35]:
alunos = pd.DataFrame(data, columns=['num', 'nome', 'alt', 'media'])
alunos

    num      nome   alt media
0  1234   Ricardo  1.78   NaN
1  7634  Ana Rita  1.67   NaN
2  3433  Patricia  1.87   NaN
3  4234      José  1.74   NaN
4  6543      Inês  1.79   NaN
5  4321      João  1.90   NaN

Outra forma de criar `DataFrame` é utilizando uma lista de dicionários.

In [36]:
data2 = [{'x': i, 'y': i**2} for i in range(2,7)]
data2

[{'x': 2, 'y': 4},
 {'x': 3, 'y': 9},
 {'x': 4, 'y': 16},
 {'x': 5, 'y': 25},
 {'x': 6, 'y': 36}]

In [37]:
func = pd.DataFrame(data2)
func

   x   y
0  2   4
1  3   9
2  4  16
3  5  25
4  6  36

Também se podem utilizar dicionários de dicionários, onde as chaves do dicionário exterior serão as colunas, e as chaves do interior serão as linhas.

In [38]:
familia_dict = {
    'filho1' : {
        'name' : 'Emilia',
        'year' : 2004
    },
    'filho2' : {
        'name' : 'Tobias',
        'year' : 2007
    },
    'filho3' : {
        'name' : 'André',
        'year' : 2011
    }
}
familia_dict

{'filho1': {'name': 'Emilia', 'year': 2004},
 'filho2': {'name': 'Tobias', 'year': 2007},
 'filho3': {'name': 'André', 'year': 2011}}

In [39]:
familia = pd.DataFrame(familia_dict)
familia

      filho1  filho2 filho3
name  Emilia  Tobias  André
year    2004    2007   2011

Ou utilizando `Series` previamente definidas.

In [40]:
area_dict = {
    'California': 423967,
    'Texas': 695662,
    'Florida': 170312,
    'Nova Iorque': 141297,
}

In [41]:
area = pd.Series(area_dict, name='area')
area

California     423967
Texas          695662
Florida        170312
Nova Iorque    141297
Name: area, dtype: int64

In [42]:
states = pd.DataFrame({'populacao': population, 'area': area})
states

             populacao      area
California    39538223  423967.0
Florida       21538187  170312.0
Nova Iorque   20201249  141297.0
Pensilvania   13002700       NaN
Texas         29145505  695662.0

Pode-se ver acima que, caso alguma chave não esteja definida, o pandas irá preencher esse valor com `NaN`.

Pode-se ainda concatenar um `DataFrame` com uma `Series` ou com outro `DataFrame`, utilizando a função `concat()` do pandas.

In [43]:
capital_dict = {'California': 'Sacramento',
                'Florida': 'Tallahassee',
                'Nova Iorque': 'Albany',
                'Pensilvania': 'Harrisburg',
                'Texas': 'Austin',
               }

In [44]:
cap = pd.Series(capital_dict, name='capital')
cap

California      Sacramento
Florida        Tallahassee
Nova Iorque         Albany
Pensilvania     Harrisburg
Texas               Austin
Name: capital, dtype: str

In [45]:
pd.concat([states, cap])

              populacao      area      capital
California   39538223.0  423967.0          NaN
Florida      21538187.0  170312.0          NaN
Nova Iorque  20201249.0  141297.0          NaN
Pensilvania  13002700.0       NaN          NaN
Texas        29145505.0  695662.0          NaN
California          NaN       NaN   Sacramento
Florida             NaN       NaN  Tallahassee
Nova Iorque         NaN       NaN       Albany
Pensilvania         NaN       NaN   Harrisburg
Texas               NaN       NaN       Austin

O exemplo acima parece "esquisito"... Isso porque por defeito, a função `concat` faz a concatenação utilizando o eixo (_axis_) 0 (linhas), portanto vai concatenar um objecto e depois o outro "em baixo, de acordo com os índices das colunas.

Outra coisa que o exemplo acima serve para mostrar é que o _label_ dos índices não são "chaves primárias", ou seja não têm a obrigatoriedade de serem únicos, como se pode ver acima, onde o nome de cada estado aparece duas vezes.

Caso se queira fazer a concatenação utilizando o eixo 1 (colunas), é preciso indicar o parâmetro `axis=1`.

In [46]:
states = pd.concat([states, cap], axis=1)
states

             populacao      area      capital
California    39538223  423967.0   Sacramento
Florida       21538187  170312.0  Tallahassee
Nova Iorque   20201249  141297.0       Albany
Pensilvania   13002700       NaN   Harrisburg
Texas         29145505  695662.0       Austin

Já agora, o nome da coluna da `Series` que foi adicionada ao `DataFrame` foi o nome da `Series`, caso a `Series` não tivesse um nome atribuído a coluna seria um valor numérico.

Caso se queira renomear os índices das colunas, podemos alterar a propriedade `.columns` do `DataFrame`, e os índices das linhas alterando a propriedade `.index`.

In [47]:
states.columns
states.columns = ['População', 'Área', 'Capital']
states

             População      Área      Capital
California    39538223  423967.0   Sacramento
Florida       21538187  170312.0  Tallahassee
Nova Iorque   20201249  141297.0       Albany
Pensilvania   13002700       NaN   Harrisburg
Texas         29145505  695662.0       Austin

Caso se queira utilizar uma das colunas como índice das linhas, temos de utilizar o método `.set_index()`, indicado o nome da coluna que ser quer utilizar.

In [48]:
alunos

    num      nome   alt media
0  1234   Ricardo  1.78   NaN
1  7634  Ana Rita  1.67   NaN
2  3433  Patricia  1.87   NaN
3  4234      José  1.74   NaN
4  6543      Inês  1.79   NaN
5  4321      João  1.90   NaN

In [49]:
alunos = alunos.set_index('num')
alunos

          nome   alt media
num
1234   Ricardo  1.78   NaN
7634  Ana Rita  1.67   NaN
3433  Patricia  1.87   NaN
4234      José  1.74   NaN
6543      Inês  1.79   NaN
4321      João  1.90   NaN

o método `.info()` dá-nos informação sobre a estrutura, o indice das colunas, o tipo de dados, a quantidade de elementos não nulos, etc.

In [50]:
alunos.info()

<class 'pandas.DataFrame'>
Index: 6 entries, 1234 to 4321
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nome    6 non-null      str
 1   alt     6 non-null      float64
 2   media   0 non-null      object
dtypes: float64(1), object(1), str(1)
memory usage: 192.0+ bytes

No exemplo acima pode-se ver que o pandas inferiu que quer a coluna `nome`, quer a coluna `media` são do tipo `object`, mas pode-se indicar o tipo de cada coluna com o método `astype`:

In [51]:
tipos = {'nome': 'string', 'alt': 'float64', 'media': 'float64'}
alunos = alunos.astype(tipos)

In [52]:
alunos.info()

<class 'pandas.DataFrame'>
Index: 6 entries, 1234 to 4321
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nome    6 non-null      string
 1   alt     6 non-null      float64
 2   media   0 non-null      float64
dtypes: float64(2), string(1)
memory usage: 192.0 bytes

No caso de `DataFrame` muito grandes, os métodos `.head()` e  `.tail()`, apresentam apenas os 5 (valor por defeito) primeiros ou últimos elementos, respetivamente.

In [53]:
alunos.head(2)

          nome   alt  media
num
1234   Ricardo  1.78    NaN
7634  Ana Rita  1.67    NaN

In [54]:
alunos.tail()

          nome   alt  media
num
7634  Ana Rita  1.67    NaN
3433  Patricia  1.87    NaN
4234      José  1.74    NaN
6543      Inês  1.79    NaN
4321      João  1.90    NaN

Para adicionar uma nova coluna a um `DataFrame` pode-se utilizar uma sintaxe tipo dicionário (`df['nova_coluna']`), podendo passar uma lista de valores (atenção, neste caso é necessário indicar um valor para todos os índices (linhas) existentes, caso contrário irá ocorrer um erro), um valor único para todos os elementos, ou um dicionário, que neste caso pode conter apenas alguns dos índices, ficando os outros como `NaN`.

In [55]:
alunos['curso'] = None
alunos

          nome   alt  media curso
num
1234   Ricardo  1.78    NaN  None
7634  Ana Rita  1.67    NaN  None
3433  Patricia  1.87    NaN  None
4234      José  1.74    NaN  None
6543      Inês  1.79    NaN  None
4321      João  1.90    NaN  None

In [56]:
alunos['curso'] = {1234: 'LESTI', 6543: 'LESTI', 3433: 'LEEC'}
alunos

          nome   alt  media  curso
num
1234   Ricardo  1.78    NaN  LESTI
7634  Ana Rita  1.67    NaN    NaN
3433  Patricia  1.87    NaN   LEEC
4234      José  1.74    NaN    NaN
6543      Inês  1.79    NaN  LESTI
4321      João  1.90    NaN    NaN

A palavra-chave `del` apaga uma coluna de um `DataFrame`, tal como faz num dicionário.

In [57]:
del alunos['media']
alunos

          nome   alt  curso
num
1234   Ricardo  1.78  LESTI
7634  Ana Rita  1.67    NaN
3433  Patricia  1.87   LEEC
4234      José  1.74    NaN
6543      Inês  1.79  LESTI
4321      João  1.90    NaN

## Aceder aos elementos

Como já se viu anteriormente, pode-se aceder aos elementos de uma `Series` utilizando a notação de parênteses retos, como se fosse uma lista do Python, mas não é a forma mais indicada, pois quando os índices são valores inteiros, o pandas irá considerar os índices indicados como _nomes_ (_labels_), e não de forma posicional (como acontece nas listas).

In [58]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])
obj1

2    1
0    2
1    3
dtype: int64

In [59]:
obj2 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
obj2

a    1
b    2
c    3
dtype: int64

In [60]:
obj1[0]

np.int64(2)

In [61]:
obj2[0]

KeyError: 0

<div class="alert alert-block alert-info">
    <p>ℹ️<b>Nota</b></p>
    A partir da versão 3.0, o pandas não permite o acesso posicional (usando parenteses retos) em Series com índice não-numérico, apenas aceita <i>labels</i>.
    </p>
</div>

A forma mais indicada é utilizar os atributos especiais `.loc` e `.iloc`, que veremos adiante.

Como já se viu, para aceder às colunas pode-se utilizar a notação do tipo dicionário (`df['coluna']`), mas também se pode utilizar a notação de ponto (_dot notation_) de um objecto (`df.coluna`). Atenção que esta notação só irá funcionar se o nome da coluna for um nome de variável correto na sintaxe no Python e não existir nenhum conflito com o nome de métodos do `DataFrame`.

In [62]:
nomes = alunos['nome']         # Definir uma Series com o nome dos alunos
nomes

num
1234     Ricardo
7634    Ana Rita
3433    Patricia
4234        José
6543        Inês
4321        João
Name: nome, dtype: string

In [63]:
alunos.nome

num
1234     Ricardo
7634    Ana Rita
3433    Patricia
4234        José
6543        Inês
4321        João
Name: nome, dtype: string

### `.loc` e `.iloc`

Para aceder às linhas, pode-se utilizar os atributos especiais `.loc` e `.iloc`. A diferença entre estes dois atributos é que enquanto o primeiro (`.loc`) utiliza o _nome_ (_labels_) dos índices/colunas, o segundo (`.iloc`) utiliza uma notação _posicional_ (similar aos aos elementos de uma lista).

Estes atributos especiais são válidos quer nas `Series` quer no `DataFrame`. No caso de uma `Series`, devolve o valor correspondente, no caso do `DataFrame`, pode devolve uma `Series` ou um valor, dependendo do que for indicado.

In [64]:
nomes.loc[1234]          # o index é o 1234

'Ricardo'

In [65]:
nomes.iloc[0]           # é a "posição" 0 (a primeira)

'Ricardo'

No caso de um `DataFrame`, caso seja indicado apenas um índice ("linha"), devolve um `Series` (uma "linha" do `DataFrame).

In [66]:
alunos

          nome   alt  curso
num
1234   Ricardo  1.78  LESTI
7634  Ana Rita  1.67    NaN
3433  Patricia  1.87   LEEC
4234      José  1.74    NaN
6543      Inês  1.79  LESTI
4321      João  1.90    NaN

In [67]:
s = alunos.loc[1234]
s

nome     Ricardo
alt         1.78
curso      LESTI
Name: 1234, dtype: object

In [68]:
type(s)

pandas.Series

In [69]:
alunos.iloc[2]

nome     Patricia
alt          1.87
curso        LEEC
Name: 3433, dtype: object

Também se pode indicar dois índices ("linha" e "coluna"), e nesse caso será devolvido um valor, que corresponde ao elemento correspondente. A linha e a coluna pode ser indicada de duas formas: Ou uma notação _recursiva_, (`df.loc[linha][coluna]`) (mais comum no Python) ou uma notação mais _matricial_, através de uma lista de índices separada por uma virgula (`df.loc[linha, coluna]`).

In [70]:
alunos

          nome   alt  curso
num
1234   Ricardo  1.78  LESTI
7634  Ana Rita  1.67    NaN
3433  Patricia  1.87   LEEC
4234      José  1.74    NaN
6543      Inês  1.79  LESTI
4321      João  1.90    NaN

In [71]:
alunos.loc[1234, 'nome']

'Ricardo'

In [72]:
alunos.loc[1234]['nome']

'Ricardo'

In [73]:
alunos.iloc[4, 2]

'LESTI'

In [74]:
alunos.iloc[4].iloc[2]

'LESTI'

O erro acima está relacionado com a forma como o pandas interpreta a sintaxe `[][]`. Primeiro será realizado o `alunos.iloc[4]`, que devolve um `Series` e depois vai fazer `Series[2]`, sem utilizar o `iloc` o que vai provocar o `FutureWarning`, como já vimos anteriormente.

<div class="alert alert-block alert-info">
<p><b>Nota</b></p>
   <p>Um erro comum a quem está a começar é utilizar <code>.loc</code> e <code>.iloc</code> como se fossem métodos (utilizando parênteses), quanto na realidade eles são atributos.</p>
</div>

### _Slices_

Pode-se utilizar a sintaxe de _slices_, para os índices, mas cuidado, o funcionamento é diferente caso se utilize _labels_ ou _posições_.

Quando se utiliza _labels_, o índice final **é incluído** na _slice_, ao contrário do que acontece com as listas no Python, mas se se utilizar _posições_ funciona da forma habitual (o elemento final **não é incluído**)

In [75]:
alunos.loc[1234:3433]

          nome   alt  curso
num
1234   Ricardo  1.78  LESTI
7634  Ana Rita  1.67    NaN
3433  Patricia  1.87   LEEC

In [76]:
alunos.iloc[0:2]

          nome   alt  curso
num
1234   Ricardo  1.78  LESTI
7634  Ana Rita  1.67    NaN

Pode-se utilizar _slices_ nos dois índices:

In [77]:
alunos.loc[1234:3433, 'nome':'curso']

          nome   alt  curso
num
1234   Ricardo  1.78  LESTI
7634  Ana Rita  1.67    NaN
3433  Patricia  1.87   LEEC

In [78]:
alunos.iloc[0:2, 0:2]

          nome   alt
num
1234   Ricardo  1.78
7634  Ana Rita  1.67

Quando se quer aceder a alguns elementos de um eixo, mas a todos os elementos do outro eixo, pode-se utilizar o sinal de dois ponto (`:`) no eixo onde se quer todos os elementos:

In [79]:
alunos.loc[:, 'nome']

num
1234     Ricardo
7634    Ana Rita
3433    Patricia
4234        José
6543        Inês
4321        João
Name: nome, dtype: string

No outro eixo pode-se indicar uma _slice_ para obter um `DataFrame`:

In [80]:
alunos.loc[:, 'nome':'curso']

          nome   alt  curso
num
1234   Ricardo  1.78  LESTI
7634  Ana Rita  1.67    NaN
3433  Patricia  1.87   LEEC
4234      José  1.74    NaN
6543      Inês  1.79  LESTI
4321      João  1.90    NaN

Mas também se pode indicar uma lista de índices a selecionar:

In [81]:
alunos.loc[:, ['nome', 'curso']]

          nome  curso
num
1234   Ricardo  LESTI
7634  Ana Rita    NaN
3433  Patricia   LEEC
4234      José    NaN
6543      Inês  LESTI
4321      João    NaN

In [82]:
alunos.iloc[:, [0, 2]]

          nome  curso
num
1234   Ricardo  LESTI
7634  Ana Rita    NaN
3433  Patricia   LEEC
4234      José    NaN
6543      Inês  LESTI
4321      João    NaN

Tal como nas `Series`, pode-se utilizar _arrays_ booleanos para filtrar valores de um `DataFrame`:

In [83]:
alunos[alunos.alt > 1.75]

          nome   alt  curso
num
1234   Ricardo  1.78  LESTI
3433  Patricia  1.87   LEEC
6543      Inês  1.79  LESTI
4321      João  1.90    NaN

Que também podem ser utilizados com o `.loc`:

In [84]:
alunos.loc[alunos.alt > 1.75]

          nome   alt  curso
num
1234   Ricardo  1.78  LESTI
3433  Patricia  1.87   LEEC
6543      Inês  1.79  LESTI
4321      João  1.90    NaN

E a partir da versão >3.0 também funcionam com o `.iloc`, apesar de não ser recomendado a sua utilização.

In [85]:
alunos.iloc[alunos.alt > 1.75]

          nome   alt  curso
num
1234   Ricardo  1.78  LESTI
3433  Patricia  1.87   LEEC
6543      Inês  1.79  LESTI
4321      João  1.90    NaN

Como se viu, existem muitas forma de selecionar e rearranjar os dados no pandas. Abaixo apresenta-se um breve sumário de algumas delas.

|<div style="width:180px">Sintaxe</div> | Comentário |
|---------------------------------------|------------|
`df[colunas]`              | Seleciona uma coluna ou subconjunto de colunas do `DataFrame`; alguns casos especiais são o uso de _arrays_ booleanos (filtra linhas) ou _slices posicionais_ (filtra linhas)
`df.loc[linhas]`           | Seleciona uma linha ou um subconjunto de linhas do `DataFrame`, utilizando a(s) _label(s)_ indicada
`df.loc[:, colunas]`      | Seleciona uma coluna ou um subconjunto de colunas utilizando a(s) _label(s)_ indicadas
`df.loc[linhas, colunas]` | Seleciona a(s) linha(s) e coluna(s) indicadas pela(s) respetiva(s) _label(s)_
`df.iloc[linhas]`         | Seleciona uma linha ou um subconjunto de linhas indicadas pela respetiva(s) _posição(ões)_
`df.iloc[:, colunas]`     | Seleciona uma coluna ou um sobconjunto de colunas utilizando a(s) _posição(ões)_ indicadas
`df.iloc[linhas, colunas]`| Seleciona a(s) linha(s) e coluna(s) indicadas pela(s) respetiva(s) _posição(ões)_

## Remover entradas

Para remover entradas utiliza-se o método `.drop`, com a ressalva que, por defeito, o método não remove do objecto indicado, mas sim cria e devolve uma cópia do objecto, com as respetivas entradas removidas (praticamente todos os métodos do pandas trabalham desta forma). No caso das `Series`pode-se simplesmente indicar o índice da entrada, ou uma lista de entradas a remover:

In [86]:
nomes = alunos['nome']
nomes

num
1234     Ricardo
7634    Ana Rita
3433    Patricia
4234        José
6543        Inês
4321        João
Name: nome, dtype: string

In [87]:
nomes.drop(1234)

num
7634    Ana Rita
3433    Patricia
4234        José
6543        Inês
4321        João
Name: nome, dtype: string

In [88]:
nomes.drop([4321, 1234, 6543])

num
7634    Ana Rita
3433    Patricia
4234        José
Name: nome, dtype: string

Também se pode utilizar os parâmetros `labels` ou `index` (são sinónimos).

In [89]:
nomes.drop(labels=[1234,4321])

num
7634    Ana Rita
3433    Patricia
4234        José
6543        Inês
Name: nome, dtype: string

In [90]:
nomes

num
1234     Ricardo
7634    Ana Rita
3433    Patricia
4234        José
6543        Inês
4321        João
Name: nome, dtype: string

Nenhuma das operações anteriores alterou o objecto base (`nomes` no caso), foi sempre devolvida uma cópia com as alterações pretendidas. Caso se pretenda alterar o objecto deve-se utilizar o parâmetro `inplace=True`.

In [91]:
nomes.drop(7634, inplace=True)
nomes

num
1234     Ricardo
3433    Patricia
4234        José
6543        Inês
4321        João
Name: nome, dtype: string

Quando aplicado a um `DataFrame`, o método `drop` por defeito irá remover as entradas das "linhas".

In [92]:
alunos.drop(1234)

          nome   alt  curso
num
7634  Ana Rita  1.67    NaN
3433  Patricia  1.87   LEEC
4234      José  1.74    NaN
6543      Inês  1.79  LESTI
4321      João  1.90    NaN

Pode-se indicar a(s) linha(s) e/ou coluna(s) a remover utilizando respetivamente os parâmetros `index` e `columns`.

In [93]:
alunos.drop(index=[1234, 4321, 6543], columns='curso')

          nome   alt
num
7634  Ana Rita  1.67
3433  Patricia  1.87
4234      José  1.74

Também se pode utilizar uma lista de índices, e o parâmatro `axis`, indicado `0` ou `index` (para as linhas) ou `1` ou `columns` (para as colunas).

In [94]:
alunos.drop(['alt','curso'], axis=1)    # ou axis='columns'

          nome
num
1234   Ricardo
7634  Ana Rita
3433  Patricia
4234      José
6543      Inês
4321      João

In [95]:
alunos.drop([1234, 4321], axis='index')

          nome   alt  curso
num
7634  Ana Rita  1.67    NaN
3433  Patricia  1.87   LEEC
4234      José  1.74    NaN
6543      Inês  1.79  LESTI

## Aritmética e alinhamento das entradas

É muito fácil trabalhar com objectos que tenham índices diferentes, pois quando nesse caso o pandas fará a _união_ dos objectos.

In [96]:
s1 = pd.Series(range(1,5), index=list('abcd'))
s1

a    1
b    2
c    3
d    4
dtype: int64

In [97]:
s2 = pd.Series(range(10, 6, -1), index=list('bdfa'))
s2

b    10
d     9
f     8
a     7
dtype: int64

Adicionando estas `Series`, iremos obter:

In [98]:
s1 + s2

a     8.0
b    12.0
c     NaN
d    13.0
f     NaN
dtype: float64

Como se pode ver, o alinhamento interno das entrada irá inserir valores em falta nos índices que não sejam comuns, e esses valores em falta serão propagados para as operações aritméticas seguintes.

O mesmo acontece com os `DataFrame`:

In [99]:
# Criar duas "matrizes" com valores aleatórios
import random
m1 = [[random.randint(1,10) for _ in range(4)] for _ in range(3)]
m2 = [[random.randint(1,10) for _ in range(3)] for _ in range(4)]

In [100]:
df1 = pd.DataFrame(m1, columns=list('abcd'))
df1

   a  b   c  d
0  9  9   3  3
1  8  7  10  3
2  1  9   9  8

In [101]:
df2 = pd.DataFrame(m2, columns=list('bde'))
df2

    b   d  e
0   2   7  4
1   7   2  4
2   6  10  9
3  10  10  4

In [102]:
df1 + df2

    a     b   c     d   e
0 NaN  11.0 NaN  10.0 NaN
1 NaN  14.0 NaN   5.0 NaN
2 NaN  15.0 NaN  18.0 NaN
3 NaN   NaN NaN   NaN NaN

Existem métodos nos objetos do panda equivalentes aos operadores aritméticos. Por exemplo, o método `add` (equivalente ao operador `+`) permite somar dois `DataFrame` (ou duas `Series`):

In [103]:
df1.add(df2)

    a     b   c     d   e
0 NaN  11.0 NaN  10.0 NaN
1 NaN  14.0 NaN   5.0 NaN
2 NaN  15.0 NaN  18.0 NaN
3 NaN   NaN NaN   NaN NaN

A vantagem da utilização destes métodos é que frequentemente o que se pretende é utilizar um valor por defeito (por exemplo o `0`), caso existem valores em falta. Isso pode ser feito passando o argumento `fill_value` com o valor pretendido:

In [104]:
df1.add(df2, fill_value=0)

     a     b     c     d    e
0  9.0  11.0   3.0  10.0  4.0
1  8.0  14.0  10.0   5.0  4.0
2  1.0  15.0   9.0  18.0  9.0
3  NaN  10.0   NaN  10.0  4.0

Para cada método aritmético, existe um semelhante que começa com a letra `r`, em que os argumentos são revertidos. Por exemplo:

In [105]:
df1.sub(df2, fill_value=0)      # df1 - df2

     a     b     c     d    e
0  9.0   7.0   3.0  -4.0 -4.0
1  8.0   0.0  10.0   1.0 -4.0
2  1.0   3.0   9.0  -2.0 -9.0
3  NaN -10.0   NaN -10.0 -4.0

In [106]:
df2.rsub(df1, fill_value=0)     # df1 - df2

     a     b     c     d    e
0  9.0   7.0   3.0  -4.0 -4.0
1  8.0   0.0  10.0   1.0 -4.0
2  1.0   3.0   9.0  -2.0 -9.0
3  NaN -10.0   NaN -10.0 -4.0

Abaixo uma tabela com os métodos aritméticos:

| Método | Descrição |
|--------|-----------|
|`add, radd`           | Métodos para adição (`+`) |
|`sub, rsub`           | Métodos para subtração (`-`) |
|`div, rdiv`           | Métodos para divisão (`/`) |
|`floordiv, rfloordiv` | Métodos para divisão inteira (`//`) |
|`mul, rmul`           | Métodos para multiplicação (`*`) |
|`pow, rpow`           | Métodos para potência (`**`) |

### Operações entre `DataFrame` e `Series`

Por defeito, nas operações aritméticas entre `Series` e `DataFrames`, são combinados os índices da `Series` com as colunas do `DataFrame`, propagando os resultados ao longo das linhas.

In [107]:
df1

   a  b   c  d
0  9  9   3  3
1  8  7  10  3
2  1  9   9  8

In [108]:
s1

a    1
b    2
c    3
d    4
dtype: int64

In [109]:
df1 - s1

   a  b  c  d
0  8  7  0 -1
1  7  5  7 -1
2  0  7  6  4

Caso algum índice não exista na `Series` ou nas colunas do `DataFrame`, os objectos serão reindexados, e serão inseridos valores em falta, como se viu anteriormente.

In [110]:
s2

b    10
d     9
f     8
a     7
dtype: int64

In [111]:
df1 - s2

     a    b   c    d   f
0  2.0 -1.0 NaN -6.0 NaN
1  1.0 -3.0 NaN -6.0 NaN
2 -6.0 -1.0 NaN -1.0 NaN

<div class="alert alert-block alert-info">
<p>ℹ️<b>Nota</b></p>
   <p>No caso de operações entre <code>DataFrame</code> e <code>Series</code>, a utilização do parâmetro <code>fill_value</code> não está implementado nos métodos aritméticos, pelo que a sua utilização irá provocar uma exceção <code>NotImplementedError</code>.</p>
    <p>Por exemplo, o código abaixo iria provocar um erro:</p>
    
```python
df1.sub(s2, fill_value=0)
```
</div>

Caso se queira fazer ao contrário, i.e., combinar os índices da `Series` com as linhas do `DataFrame` e propagar pelas colunas, é necessário utilizar os métodos aritméticos, e indicar que deve ser combinado pelas linhas (`index`).

In [112]:
df1

   a  b   c  d
0  9  9   3  3
1  8  7  10  3
2  1  9   9  8

In [113]:
s3 = df1['d']
s3

0    3
1    3
2    8
Name: d, dtype: int64

In [114]:
df1.sub(s3, axis='index') # axis=0

   a  b  c  d
0  6  6  0  0
1  5  4  7  0
2 -7  1  1  0

## Utilização e mapeamento de funções

É frequente querer-se aplicar uma função uni-dimensional a cada linha/coluna. O método `apply` faz exatamente isso. Por exemplo, vamos calcular a amplitude:

In [115]:
def amplitude(x):
    return x.max() - x.min()

In [116]:
df1

   a  b   c  d
0  9  9   3  3
1  8  7  10  3
2  1  9   9  8

In [117]:
df1.apply(amplitude)

a    8
b    2
c    7
d    5
dtype: int64

Podia-se ter obtido o mesmo resultado utilizando uma função anónima:

In [118]:
df1.apply(lambda x: x.max()-x.min())

a    8
b    2
c    7
d    5
dtype: int64

O resultado é uma `Series`, resultado da aplicação da função a cada coluna do `DataFrame`. O índice da `Series` são as colunas do `DataFrame`.

Caso se pretenda fazer ao contrário (aplicar a função a cada linha do `DataFrame`), deve-se utilizar o parâmetro `axis`, indicado `1` ou `columns`.

In [119]:
df1.apply(amplitude, axis=1)

0    6
1    7
2    8
dtype: int64

As funções a utilizar não estão limitadas à devolução de um único valor, podem devolver multiplos valores:

In [120]:
def minmax(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [121]:
df1.apply(minmax, axis=1)

   min  max
0    3    9
1    3   10
2    1    9

O `DataFrame` implementa métodos que calculam muitas funções estatísticas nesses casos não é necessário utilizar o método `apply`.

In [122]:
df1.apply(sum)     # A função sum (do Python) é o argumento do método apply do DataFrame

a    18
b    25
c    22
d    14
dtype: int64

In [123]:
df1.sum()          # Aplicar diretamente o método sum do DataFrame

a    18
b    25
c    22
d    14
dtype: int64

Caso o objectivo seja aplicar uma função elemento-a-elemento pode-se utilizar o método `map`:

In [124]:
df1.map(lambda x: f'{x:.2f}')

      a     b      c     d
0  9.00  9.00   3.00  3.00
1  8.00  7.00  10.00  3.00
2  1.00  9.00   9.00  8.00

In [125]:
s1.map(lambda x: 5*x)

a     5
b    10
c    15
d    20
dtype: int64

## Ordenação

Por vezes é necessário/útil poder ordenar quer os índices quer os valores. Isso pode ser feito através dos métodos `sort_index` e `sort_values`.

In [126]:
alunos

          nome   alt  curso
num
1234   Ricardo  1.78  LESTI
7634  Ana Rita  1.67    NaN
3433  Patricia  1.87   LEEC
4234      José  1.74    NaN
6543      Inês  1.79  LESTI
4321      João  1.90    NaN

Por defeito, o método `sort_index` ordena o `index` (linhas):

In [127]:
alunos.sort_index()

          nome   alt  curso
num
1234   Ricardo  1.78  LESTI
3433  Patricia  1.87   LEEC
4234      José  1.74    NaN
4321      João  1.90    NaN
6543      Inês  1.79  LESTI
7634  Ana Rita  1.67    NaN

Mas, utilizando o parâmetro `axis` pode-se indicar qual o eixo (linhas/colunas) a utilizar.

In [128]:
alunos.sort_index(axis=1, ascending=False)

          nome  curso   alt
num
1234   Ricardo  LESTI  1.78
7634  Ana Rita    NaN  1.67
3433  Patricia   LEEC  1.87
4234      José    NaN  1.74
6543      Inês  LESTI  1.79
4321      João    NaN  1.90

No exemplo anterior também se pode ser que, por defeito, é feita uma ordenação ascendente, mas utilizando o parâmetro `ascending` pode-se indicar que se pretende uma ordenação descendente.

O método `sort_values` pode ser utilizado diretamente numa `Series`:

In [129]:
s2.sort_values()

a     7
f     8
d     9
b    10
dtype: int64

Mas no caso de um `DataFrame`, é necessário indicar qual/quais a(s) coluna(s) que deve(m) ser utilizada(s) para ordenar os dados. Pode-se passar a _label_ da coluna, ou uma lista de _labels_, ou utilizando o parâmetro `by`.

In [130]:
alunos.sort_values(by='curso')

          nome   alt  curso
num
3433  Patricia  1.87   LEEC
1234   Ricardo  1.78  LESTI
6543      Inês  1.79  LESTI
7634  Ana Rita  1.67    NaN
4234      José  1.74    NaN
4321      João  1.90    NaN

Caso se pretenda ordenar utilizando diferentes subcritérios (diversas colunas), pode-se indicar para cada critério se pretende ordenar de forma ascendente ou descendente.

In [131]:
alunos.sort_values(by=['curso', 'nome'], ascending=False)

          nome   alt  curso
num
1234   Ricardo  1.78  LESTI
6543      Inês  1.79  LESTI
3433  Patricia  1.87   LEEC
4321      João  1.90    NaN
4234      José  1.74    NaN
7634  Ana Rita  1.67    NaN

Pode-se também indicar se se quer que os valores em falta (`NaN`) apareçam no final (`last`, valor por defeito) ou no inicio (`first`) da listagem, utilizando o parâmetro `na_position`:

In [132]:
alunos.sort_values(by='curso', na_position='first')

          nome   alt  curso
num
7634  Ana Rita  1.67    NaN
4234      José  1.74    NaN
4321      João  1.90    NaN
3433  Patricia  1.87   LEEC
1234   Ricardo  1.78  LESTI
6543      Inês  1.79  LESTI

Relembrar que estes método, por defeito, não alteram o objecto sob o qual estão a operar, mas devolvem um cópia do objecto com as alterações. Caso se queira alterar diretamente o objecto deve-se utilizar o parâmetro `inplace=True`.

In [133]:
alunos

          nome   alt  curso
num
1234   Ricardo  1.78  LESTI
7634  Ana Rita  1.67    NaN
3433  Patricia  1.87   LEEC
4234      José  1.74    NaN
6543      Inês  1.79  LESTI
4321      João  1.90    NaN

## Métodos estatísticos

Os objectos do pandas possuem um conjunto de métodos que implementam algumas das funções matemáticas e estatísticas mais comuns, de forma computacionalmente eficiente.

Como se viu anteriormente, pode-se somar as entradas (por defeito percorre as linhas) de um objecto utilizando o método `sum`:

In [134]:
df1 = pd.DataFrame([[5.2, pd.NA],
                    [6.1, 3.2],
                    [pd.NA, pd.NA],
                    [4.5, 3.4]],
                   index=list('abcd'),
                   columns=list('xy'))
df1

      x     y
a   5.2  <NA>
b   6.1   3.2
c  <NA>  <NA>
d   4.5   3.4

In [135]:
df1.sum()

x    15.8
y     6.6
dtype: object

Caso se pretenda a soma percorrendo as colunas, deve-se utilizar o parâmetro `axis`, indicando `1` 
ou `columns`:

In [136]:
df1.sum(axis='columns')  # axis=1

a    5.2
b    9.3
c      0
d    7.9
dtype: object

Por defeito, caso existam valores em falta estes serão ignorados, caso todas as entradas da linha/coluna sejam `NA`, então a soma será `0`. Passar o parâmetro `skipna=False` faz com que seja devolvido o valor `NA` caso alguma das entradas seja `NA`.

In [137]:
df1.sum(axis=1, skipna=False)

a    <NA>
b     9.3
c    <NA>
d     7.9
dtype: object

Alguns dos métodos exigem que pelo um dos valores não seja `NA` para devolver um resultado, um desses métodos é o `mean`:

In [138]:
df1.mean(axis='columns')

a     5.2
b    4.65
c     NaN
d    3.95
dtype: object

Outros métodos devolvem estatísticas indiretas, como os métodos `idxmin` e `idxmax`, que devolvem os índices onde se encontra o valor mínimo/máximo.

In [139]:
df1

      x     y
a   5.2  <NA>
b   6.1   3.2
c  <NA>  <NA>
d   4.5   3.4

In [140]:
df1.idxmax()

x    b
y    d
dtype: str

Existem ainda métodos que são _comulativos_:

In [141]:
df1

      x     y
a   5.2  <NA>
b   6.1   3.2
c  <NA>  <NA>
d   4.5   3.4

In [142]:
df1.cumsum()

      x    y
a   5.2  NaN
b  11.3  3.2
c   NaN  NaN
d  15.8  6.6

Abaixo apresenta-se uma listagem de alguns dos métodos mais utilizados:

| Método | Descrição |
|--------|-----------|
|`count` | Quantidade de valores não `NA` |
|`describe` | Apresenta um sumário estatístico |
|`min`, `max` | Determina o valor minimo e máximo |
|`idxmin`, `idxmax` | Determina o índice onde se encontra o valor mínimo ou o valor máximo, respetivamente |
|`sum` | Soma dos valores |
|`mean` | Média dos valores |
|`median` | Mediana dos valores |
|`prod` | Produto de todos os valores|
|`var` | Variância dos valores |
|`std` | Desvio Padrão dos valores |
|`cumsum` | Soma comulativa dos valores |
|`cumprod` | Produto comulativo dos valores |
|`diff` | Calcula a diferença entre duas entradas (útil para series temporais) |