# Exercícios

## Exercicio 1

Crie uma `Series` chamada `s` com os seguintes dados: `[10, 20, 30, 40, 50]`.

1. Visualize `s`.
4. Acesse o terceiro elemento da `Series`.
2. Atualize o valor do segundo elemento para 25.
3. Some 5 a todos os elementos da `Series`.

In [246]:
import pandas as pd

s = pd.Series([10, 20, 30, 40, 50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [247]:
s[2]

30

In [248]:
s[1] = 25
s

0    10
1    25
2    30
3    40
4    50
dtype: int64

In [249]:
s + 5

0    15
1    30
2    35
3    45
4    55
dtype: int64

## Exercício 2

Crie uma `Series` com os seguintes dados: `[1.5, 2.8, 3.3, 4.1]`. O índice deve ser as letras `['a', 'b', 'c', 'd']`.

1. Converta a `Series` para o tipo inteiro (`int`).
2. Alterne o tipo da `Series` de volta para `float` e adicione 0.5 a todos os elementos.
3. Crie uma nova `Series` onde os valores são representados como strings.

In [250]:
s1 = pd.Series([1.5, 2.8, 3.3, 4.1], index=['a', 'b', 'c', 'd'])

s1

a    1.5
b    2.8
c    3.3
d    4.1
dtype: float64

In [251]:
s1 = s1.astype('int64')
s1

a    1
b    2
c    3
d    4
dtype: int64

In [252]:
s1 = s1.astype('float64') + 0.5
s1

a    1.5
b    2.5
c    3.5
d    4.5
dtype: float64

In [253]:
s1 = s1.astype(str)
s1

a    1.5
b    2.5
c    3.5
d    4.5
dtype: object

## Exercício 3
Crie um `DataFrame` chamado `df3` com os seguintes dados:

| Nome    | Idade | Cidade    |
|---------|-------|-----------|
| Ana     | 23    | Lisboa    |
| Bruno   | 35    | Porto     |
| Carla   | 28    | Coimbra   |
| Daniel  | 42    | Faro      |

1. Apresente o `DataFrame`
2. Visualize os nomes das colunas.
3. Use `loc` para acessar os dados da linha referente a "Carla".
4. Use `iloc` para acessar o valor da célula na segunda linha e primeira coluna.
5. Utilizando `slices`:
    1. Apresente as duas primeiras linhas.
    2. Apresente todas as colunas existentes entre "Nome" e "Cidade", de todas as linhas.
6. Remova a linha referente a "Bruno".
7. Remova a coluna "Idade".

In [254]:
df = {
    'Nome' : ['Ana', 'Bruno', 'Carla', 'Daniel'],
    'Idade' : [23, 35, 28, 42],
    'Cidade' : ['Lisboa','Porto','Coimbra','Faro']
}

df = pd.DataFrame(df)
print(df)
df

     Nome  Idade   Cidade
0     Ana     23   Lisboa
1   Bruno     35    Porto
2   Carla     28  Coimbra
3  Daniel     42     Faro

     Nome  Idade   Cidade
0     Ana     23   Lisboa
1   Bruno     35    Porto
2   Carla     28  Coimbra
3  Daniel     42     Faro

In [255]:
df.loc[df['Nome'] == 'Carla']

    Nome  Idade   Cidade
2  Carla     28  Coimbra

In [256]:
df.iloc[1, 0]

'Bruno'

In [257]:
df.iloc[0:2]

    Nome  Idade  Cidade
0    Ana     23  Lisboa
1  Bruno     35   Porto

In [258]:
df.loc[:, 'Nome':'Cidade']

     Nome  Idade   Cidade
0     Ana     23   Lisboa
1   Bruno     35    Porto
2   Carla     28  Coimbra
3  Daniel     42     Faro

In [259]:
df.drop(1)

     Nome  Idade   Cidade
0     Ana     23   Lisboa
2   Carla     28  Coimbra
3  Daniel     42     Faro

In [260]:
df.drop('Idade', axis=1)

     Nome   Cidade
0     Ana   Lisboa
1   Bruno    Porto
2   Carla  Coimbra
3  Daniel     Faro

## Exercício 4

Crie um `DataFrame` (`df4`) com os seguintes dados:

| Nome    | Salario | Departamento |
|---------|---------|--------------|
| Ana     | 3000    | Marketing    |
| Bruno   | 2500    | Vendas       |
| Carla   | 3500    | RH           |
| Daniel  | 4000    | TI           |

1. Converta a coluna **Salario** para o tipo `float`.
2. Crie uma nova coluna **Bonus**, onde o valor é $5\%$ do salário de cada funcionário.
3. Calcule o salário total (salário + bónus) e adicione-o numa nova coluna.
4. Selecione todos os funcionários com salário acima de 3000.
2. Acesse somente os funcionários que estão no departamento de **TI** ou **Marketing**.
3. Crie um novo `DataFrame`, de nome `df_bempagos`, contendo apenas os funcionários com **Salario Total** superior a 3800.

In [261]:
df4 ={
    'Nome' : ['Ana', 'Bruno', 'Carla', 'Daniel'],
    'Salario': [3000, 2500, 3500, 4000],
    'Departamento': ['Marketing','Vendas','RH','TI']
}

df4 = pd.DataFrame(df4)
df4

     Nome  Salario Departamento
0     Ana     3000    Marketing
1   Bruno     2500       Vendas
2   Carla     3500           RH
3  Daniel     4000           TI

In [262]:
# Converter para float

df4['Salario'] = df4['Salario'].astype('float64')
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Nome          4 non-null      object
 1   Salario       4 non-null      float64
 2   Departamento  4 non-null      object
dtypes: float64(1), object(2)
memory usage: 228.0+ bytes

In [263]:
# Criar coluna nova com o nome de Bonus onde o bonus é +5% do salario de cada empregado

df4['Bonus'] = df4['Salario']*0.05
df4

     Nome  Salario Departamento  Bonus
0     Ana   3000.0    Marketing  150.0
1   Bruno   2500.0       Vendas  125.0
2   Carla   3500.0           RH  175.0
3  Daniel   4000.0           TI  200.0

In [264]:
# Calcular salario + bonus e colocar em nova coluna

df4['Total'] = df4['Salario'] + df4['Bonus']
df4

     Nome  Salario Departamento  Bonus   Total
0     Ana   3000.0    Marketing  150.0  3150.0
1   Bruno   2500.0       Vendas  125.0  2625.0
2   Carla   3500.0           RH  175.0  3675.0
3  Daniel   4000.0           TI  200.0  4200.0

In [265]:
# Acessar somente aos funcionarios que estao em TI e marketing

df4[(df4['Departamento'] == 'Marketing') | (df4['Departamento'] == 'TI')]

     Nome  Salario Departamento  Bonus   Total
0     Ana   3000.0    Marketing  150.0  3150.0
3  Daniel   4000.0           TI  200.0  4200.0

In [266]:
# Selecionar todos os funcionarios com o salario acima de 3000

df4[df4['Salario'] > 3000]

     Nome  Salario Departamento  Bonus   Total
2   Carla   3500.0           RH  175.0  3675.0
3  Daniel   4000.0           TI  200.0  4200.0

In [267]:
# Criar novo dataframe chamado  df_bempagos contendo funcionarios que ganhem mais de 3800

df_bempagos = df4[df4['Total'] > 3800]
df_bempagos = pd.DataFrame(df_bempagos)
df_bempagos

     Nome  Salario Departamento  Bonus   Total
3  Daniel   4000.0           TI  200.0  4200.0

## Exercício 5

Altere o `DataFrame` `df4` criado no exercício anterior, de acordo com o solicitado:

1. Remova a coluna **Departamento**.
2. Altere o índice para ser os valores da coluna **Nome**.
3. Remova a linha associada ao funcionário **Bruno**.
4. Ordene os funcionários pelos salários (coluna **Salario**) de forma decrescente.
5. Ordene o `DataFrame` com uma ordem personalizada: `['Carla', 'Ana', 'Daniel']`.

In [268]:
df5 = df4.drop('Departamento', axis=1)
df5

     Nome  Salario  Bonus   Total
0     Ana   3000.0  150.0  3150.0
1   Bruno   2500.0  125.0  2625.0
2   Carla   3500.0  175.0  3675.0
3  Daniel   4000.0  200.0  4200.0

In [269]:
# altere o indice para ser os valores da coluna nome

df5 = df5.set_index('Nome')
df5

        Salario  Bonus   Total
Nome
Ana      3000.0  150.0  3150.0
Bruno    2500.0  125.0  2625.0
Carla    3500.0  175.0  3675.0
Daniel   4000.0  200.0  4200.0

In [270]:
# Remova a linha associada ao funcionario bruno

df5 = df5.drop('Bruno')
df5

        Salario  Bonus   Total
Nome
Ana      3000.0  150.0  3150.0
Carla    3500.0  175.0  3675.0
Daniel   4000.0  200.0  4200.0

In [271]:
# Ordenar funcionarios pela coluna salario de forma decrescente

df5.sort_values(by = 'Salario', ascending=False)

        Salario  Bonus   Total
Nome
Daniel   4000.0  200.0  4200.0
Carla    3500.0  175.0  3675.0
Ana      3000.0  150.0  3150.0

In [272]:
# Ordenar o dataframe por ordem especifica de Carla Ana Daniel

df5.loc[['Carla','Ana','Daniel']]

        Salario  Bonus   Total
Nome
Carla    3500.0  175.0  3675.0
Ana      3000.0  150.0  3150.0
Daniel   4000.0  200.0  4200.0

## Exercício 6

Com base no `DataFrame` atualizado:

1. Calcule a soma total da coluna "Salario Total".
2. Conte quantos funcionários possuem salários acima de 3000.
3. Calcule o produto dos valores da coluna "Bónus".

In [275]:
# Calcule a soma total da coluna "Total"

soma_total = df5['Total'].sum()
soma_total

11025.0

In [276]:
# Conte quantos funcionarios possuem salarios acima de 3000.

len(df5[df5['Salario'] > 3000])

2

In [277]:
# Calcule o produto dos valores da coluna Bonus

produto = df5['Bonus'].prod()
produto

5250000.0

## Exercício 7

1. Crie uma `Series` com os valores `[200, 500, 250, 100]`, onde o índice representa produtos: `['Produto A', 'Produto B', 'Produto C', 'Produto D']`.
2. Crie um tipo de categorias ordenadas, com os valores "Barato" e "Caro" e "Luxo".
3. Crie outra `Series`, resultado de aplique uma função à primeira `Series` que categorize os produtos como "Barato" se o valor for menor que 180, "Luxo" se for 500 ou mais, e "Caro" todos os outros. Não se esqueça que o tipo deve ser o criado na alínea anterior.
4. Crie um `DataFrame` concatenando as duas `Series`, e altere o nome das colunas para "Preço" e "Categoria".
5. Aplique uma segunda função ao `DataFrame` para atualizar o "Preço", de forma a efetuar um desconto de 10% para da categoria "Caros" ou superior.
6. Calcule a média dos Preços.
7. Calculo o produto dos Preços.
8. Determine quantos produtos têm Preço superior a 150.

In [ ]:
# Crie uma Series com os valores [200, 500, 250, 100], onde o índice representa produtos: ['Prodtudo A', 'Prodtuo B',
# 'Produto C', 'Produto D'].

s7 = pd.Series([200, 500, 250, 100], index=['Produto A', 'Produto B', 'Produto C', 'Produto D'])
s7

Produto A    200
Produto B    500
Produto C    250
Produto D    100
dtype: int64

In [285]:
# Crie um tipo de categorias oredenadas, com os valores "Barato e "Caro" e "Luxo"

qualidade_cat = pd.CategoricalDtype(['Barato','Caro','Luxo'], ordered=True)
qualidade_cat

CategoricalDtype(categories=['Barato', 'Caro', 'Luxo'], ordered=True, categories_dtype=object)

In [287]:
# Crie outra Series, resultado de aplique uma função á primeira Series que categorize os produtos como "Barato" se o 
# valor form menor que 180, "Luxo" se for 500 ou mais e "Caro" todos os outros. 
# Não se esqueça que o tipo dese ser criado na alinea anterior.

def categoriza(valor):
    if valor < 180:
        return "Barato"

    elif valor >= 500:
        return "Luxo"

    else:
        return "Caro"

s7new = s7.apply(categoriza)
s7new = s7new.astype(qualidade_cat)

s7new

Produto A      Caro
Produto B      Luxo
Produto C      Caro
Produto D    Barato
dtype: category
Categories (3, object): ['Barato' < 'Caro' < 'Luxo']

In [292]:
# Crie um DataFrame concatenando as duas Series, e altere o nome para "Preço" e "Categoria"

df7 = pd.concat([s7, s7new], axis=1)
df7.columns = ['Preço','Categoria']
df7

           Preço Categoria
Produto A    200      Caro
Produto B    500      Luxo
Produto C    250      Caro
Produto D    100    Barato

In [296]:
# Aplique uma segunda função ao seu DataFrame para atualizar um "Preço", 
# de forma a efetuar um desconto de 10% para da categoria "Caros" ou superior.

def desconto(row):
    if row['Categoria'] >= 'Caro':
        return row ['Preço'] * 0.9
    else:
        return row ['Preço']

df7['Preço'] = df7.apply(desconto, axis=1)
df7

           Preço Categoria
Produto A  180.0      Caro
Produto B  450.0      Luxo
Produto C  225.0      Caro
Produto D  100.0    Barato

In [297]:
# Calcular media dos preços

df7['Preço'].mean()

238.75

In [300]:
# Calcule o produto dos preços

produto = df7['Preço'].prod()
produto

1822500000.0

In [302]:
# Determine quantos produtos tem o preço superior a 150

len(df7[df7['Preço'] > 150])

3