In [1]:
#!pip install openpyxl
#!pip install lxml beautifulsoup4 html5lib requests
#!pip install sqlalchemy pymysql

# Aquisição de dados

Antes de se poder fazer qualquer análise de dados, é necessário **obter** esses dados, e torná-los acessíveis para posterior análise.

No pandas existem várias funções que permitem efetuar a leitura de dados em vários tipos de formato/ficheiro, desde CSV, até diretamente de uma base de dados, passando por JSON ou Excel.

* Ficheiros CSV
* Ficheiros EXCEL
* Ficheiros JSON
* _Web Scraping_
* Aceder a APIs online
* Bases de Dados

In [2]:
import pandas as pd

pd.options.display.max_columns = 999

## Ficheiros CSV

Ficheiros CSV (_Comma Separated Values_) são ficheiros de texto, em que os dados estão em forma da tabela, podendo ou não existir um cabeçalho. Apesar de CSV indicar que os valores são separados por virgula, isso pode não ocorrer.

### O módulo `csv`

Para ler este tipo de ficheiros podemos utilizar o módulo `csv`, que faz parte os módulos integrantes nas livrarias do Python. Consideremos o seguinte ficheiro:

In [3]:
!type exemplos\ex1.csv

a,b,c,mensagem,idx
1,2,3,ola,first
4,5,6,mundo,second
7,8,9,foo,third
10,11,12,bar,fourth

A função `DictReader` permite ler os dados de um ficheiros `CSV` através de um dicionário. Cada linha lida do ficheiro é transformada num dicionário, onde, por defeito, a chave é o nome da coluna.

In [4]:
import csv

with open(r'exemplos\ex1.csv') as f:           # r'string' - formato raw
    reader = csv.DictReader(f, delimiter=',')  # O parâmetro delimiter aqui é desnecessário, pois por defeito é o ','
    data = [row for row in reader]

data

[{'a': '1', 'b': '2', 'c': '3', 'mensagem': 'ola', 'idx': 'first'},
 {'a': '4', 'b': '5', 'c': '6', 'mensagem': 'mundo', 'idx': 'second'},
 {'a': '7', 'b': '8', 'c': '9', 'mensagem': 'foo', 'idx': 'third'},
 {'a': '10', 'b': '11', 'c': '12', 'mensagem': 'bar', 'idx': 'fourth'}]

> **NOTA:**
> 
> A utilização do `r` (_raw_) na definição da _string_ com o nome do ficheiro tem a ver com a utilização do `\` no nome do ficheiro, o que seria interpretado como um código de escape, e iria provocar um erro. Podia-se ter resolvido de várias formas:
> 
> - Utilizar um duplo _backslash_ (`\\`) em vez apenas um (`exemplos\\exemplo1.csv`)
> - Utilizar o _forward slash_ (`/`) (`exemplos/exemplo1.csv`)
> - Utilizando uma _string_ em formato _raw_ (`r'rawstring'`)
> - Utilizando a livraria `pathlib`

Para criar depois um `DataFrame` com o dicionário lido basta passar esse dicionário para a função `DataFrame`.

In [5]:
df1 = pd.DataFrame(data)
df1

    a   b   c mensagem     idx
0   1   2   3      ola   first
1   4   5   6    mundo  second
2   7   8   9      foo   third
3  10  11  12      bar  fourth

### A função `read_csv(...)`

Apesar da utilização do módulo `csv` não ser muito complicado, o pandas possui funções próprias para ler diversos tipos de ficheiros, incluindo ficheiros `CSV`, através da função `read_csv` que devolve um `DataFrame` com os dados existentes no ficheiro.

Utilizando o mesmo ficheiro lido anteriormente, os valores estão separados por uma virgula, pelo que se pode utilizar a função `read_csv` sem mais argumentos, passando apenas o nome do ficheiro.

In [6]:
!type exemplos\ex1.csv

a,b,c,mensagem,idx
1,2,3,ola,first
4,5,6,mundo,second
7,8,9,foo,third
10,11,12,bar,fourth

In [7]:
df1 = pd.read_csv(r'exemplos\ex1.csv')
df1

    a   b   c mensagem     idx
0   1   2   3      ola   first
1   4   5   6    mundo  second
2   7   8   9      foo   third
3  10  11  12      bar  fourth

Por defeito, o pandas vai atribuir aos valores da primeira linha o nome das colunas, mas nem sempre os ficheiros tem uma indicação do nome das colunas. Por exemplo, considere o seguinte exemplo:

In [8]:
!type exemplos\ex2.csv

1,2,3,ola,first
4,5,6,mundo,second
7,8,9,foo,third
10,11,12,bar,fourth

Caso se leia o ficheiro da mesma forma, a primeira linha será o nome das colunas, o que neste caso estaria incorreto. Para efetuar a leitura deste ficheiro de forma correta, pode-se deixar que o pandas atribua nomes de colunas por defeito:

In [9]:
df2 = pd.read_csv(r'exemplos\ex2.csv', header=None)
df2

    0   1   2      3       4
0   1   2   3    ola   first
1   4   5   6  mundo  second
2   7   8   9    foo   third
3  10  11  12    bar  fourth

Ou utiliza-se o parâmetro `names` com uma lista dos nomes das colunas pretendidas:

In [10]:
df3 = pd.read_csv(r'exemplos\ex2.csv',
                  names=['a', 'b', 'c', 'mensagem', 'idx']
                 )
df3

    a   b   c mensagem     idx
0   1   2   3      ola   first
1   4   5   6    mundo  second
2   7   8   9      foo   third
3  10  11  12      bar  fourth

Caso se pretenda que uma das colunas seja o índice, isso pode ser feito utilizando o parâmetro `index_col`. Suponha que se pretende que a coluna `idx` seja o índice das linhas:

In [11]:
df4 = pd.read_csv(r'exemplos\ex2.csv',
                  names=['a', 'b', 'c', 'mensagem', 'idx'],
                  index_col='idx'
                 )
df4

         a   b   c mensagem
idx
first    1   2   3      ola
second   4   5   6    mundo
third    7   8   9      foo
fourth  10  11  12      bar

No caso de o delimitador (ou separador) ser outro que não a vírgula, devemos utilizar o parâmetro `sep` (_separator_), com o(s) caracter(es) que separem cada coluna.

Considere o seguinte ficheiro:

In [12]:
!type exemplos\ex3.csv

A	B	C
a   0.1232  -1.1332   1.3432
b  -1.2332   0.2323  -0.2323
c   0.4332  -0.2334   1.3434
d   1.3244   1.4334  -0.2323

Para indicar que o delimitador são espaços (`' '`), e como não é sempre o mesmo numero de espaços, deve-se utilizar (`\s+`), que significa um espaço (`\s`) ou mais (`+`).

In [13]:
df5 = pd.read_csv(r'exemplos\ex3.csv', sep=r'\s+')
df5

        A       B       C
a  0.1232 -1.1332  1.3432
b -1.2332  0.2323 -0.2323
c  0.4332 -0.2334  1.3434
d  1.3244  1.4334 -0.2323

In [14]:
df5.shape

(4, 3)

Outra coisa que se pode verificar no exemplo acima é que os nomes para as colunas (na primeira linha) são um menos do que as colunas de dados. Neste caso particular, e de forma automática, o pandas assume que a primeira coluna são os índices das linhas.

In [15]:
!type exemplos\ex4.csv

Numero    Nome                  FQ1   FQ2
12345     "Francisco Martins"   12    14
43212     "Ana Rosa"            NA    12
43231     "Maria Cristina"      15    NA
NaN        NONE                 NA    NA
12334     "AndrÃ© Silva"         --    9

Por defeito, a função read_csv vai considerar uma única _string_ se estiver entre aspas (`"`), mas isso pode ser definido utilizando o parâmetro `quotechar` e indicando qual o caractere que delimita as _strings_.

In [16]:
df6 = pd.read_csv(r'exemplos\ex4.csv', sep=r'\s+',
                  quotechar='"',
                  header=0,     # A primeira linha do ficheiro (0) é o cabeçalho
                  decimal='.'   # O sinal decimal é o ponto (.)
                 )
df6

    Numero               Nome  FQ1   FQ2
0  12345.0  Francisco Martins   12  14.0
1  43212.0           Ana Rosa  NaN  12.0
2  43231.0     Maria Cristina   15   NaN
3      NaN               NONE  NaN   NaN
4  12334.0        André Silva   --   9.0

Pode-se utilizar o método `isna` para verificar quais os elementos vazios num `DataFrame` ou `Series`:

In [17]:
df6.isna()

   Numero   Nome    FQ1    FQ2
0   False  False  False  False
1   False  False   True  False
2   False  False  False   True
3    True  False   True   True
4   False  False  False  False

Acima pode-se verificar que a coluna **Nome** não existe nenhum valor nulo e na coluna **FQ1** foram  identificados apenas 2 valores nulos, quando existem 3. Isto porque o pandas não reconhece `NONE` e `--` como valores nulos. Pode-se utilizar o parâmetro `na_values` passando uma lista de valores que devem ser reconhecidos como `NA`:

In [18]:
df7 = pd.read_csv(r'exemplos\ex4.csv',
                  sep=r'\s+',
                  quotechar='"',
                  na_values=['NONE', '--']
                 )
df7

    Numero               Nome   FQ1   FQ2
0  12345.0  Francisco Martins  12.0  14.0
1  43212.0           Ana Rosa   NaN  12.0
2  43231.0     Maria Cristina  15.0   NaN
3      NaN                NaN   NaN   NaN
4  12334.0        André Silva   NaN   9.0

In [19]:
df7.isna()

   Numero   Nome    FQ1    FQ2
0   False  False  False  False
1   False  False   True  False
2   False  False  False   True
3    True   True   True   True
4   False  False   True  False

A função `read_csv` também permite efetuar uma leitura diretamente a partir de um URL. Por exemplo, os dados de alguns passageiros do Titanic:

In [20]:
URL = 'https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv'
titanic = pd.read_csv(URL)
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

No caso de _datasets_ extremamente grandes, pode ser necessário efetuar a leitura por blocos (_chunks_), de forma a não esgotar a memória. Isso pode ser feito definindo o parâmetro `chucksize`:

In [21]:
pd.read_csv(URL, chunksize=1000)

Vamos, por exemplo, utilizar essa forma de ler e processar de forma "automática" (i.e., sem nunca guardar todos os dados do ficheiro em memória), para determinar a quantidade de sobreviventes do Titanic, lendo blocos de 50 linhas (`chunksize=50`):

In [22]:
URL = 'https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv'
survived = 0

with pd.read_csv(URL, chunksize=100) as chunk:
    for i, data in enumerate(chunk):
        print(i, end=' ')
        survived += data['Survived'].sum()

print(f'\n\nNo total sobreviveram {survived} passageiros')

0 1 2 3 4 5 6 7 8

No total sobreviveram 342 passageiros

> **NOTA**
>
> Pode-se observar na listagem do _dataset_ acima, que a coluna `Survived` é composta por 1 caso o passageiro tenha sobrevivido, e 0 caso contrário.

### O método `to_csv(...)`

Para guardar os dados de uma `Series` ou `DataFrame` para um ficheiro`CSV` podemos utilizar o método `to_csv`, passando o nome do ficheiro a guardar.

In [23]:
titanic.to_csv(r'titanic.csv')

In [24]:
!type titanic.csv

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925,,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.05,,S
5,6,0,3,"Moran, Mr. James",male,,0,0,330877,8.4583,,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.075,,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.55,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.05,,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.275,,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome) ",female,55.0,0,0,248706,16.0,,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.125,,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,,0,0,244373,13.0,,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)",female,31.0,1,0,345763,18.0,,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,,0,0,2649,7.225,,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0,,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.075,,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)",female,38.0,1,5,347077,31.3875,,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,,0,0,2631,7.225,,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0,C23 C25 C27,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,,0,0,330959,7.8792,,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,,0,0,349216,7.8958,,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,,C
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,,1,0,PC 17569,146.5208,B78,C
32,33,1,3,"Glynn, Miss. Mary Agatha",female,,0,0,335677,7.75,,Q
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5,,S
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.0,1,0,PC 17604,82.1708,,C
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0,,S
36,37,1,3,"Mamee, Mr. Hanna",male,,0,0,2677,7.2292,,C
37,38,0,3,"Cann, Mr. Ernest Charles",male,21.0,0,0,A./5. 2152,8.05,,S
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18.0,2,0,345764,18.0,,S
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.0,1,0,2651,11.2417,,C
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.475,,S
41,42,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)",female,27.0,1,0,11668,21.0,,S
42,43,0,3,"Kraeff, Mr. Theodor",male,,0,0,349253,7.8958,,C
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,,C
44,45,1,3,"Devaney, Miss. Margaret Delia",female,19.0,0,0,330958,7.8792,,Q
45,46,0,3,"Rogers, Mr. William John",male,,0,0,S.C./A.4. 23567,8.05,,S
46,47,0,3,"Lennon, Mr. Denis",male,,1,0,370371,15.5,,Q
47,48,1,3,"O'Driscoll, Miss. Bridget",female,,0,0,14311,7.75,,Q
48,49,0,3,"Samaan, Mr. Youssef",male,,2,0,2662,21.6792,,C
49,50,0,3,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18.0,1,0,349237,17.8,,S
50,51,0,3,"Panula, Master. Juha Niilo",male,7.0,4,1,3101295,39.6875,,S
51,52,0,3,"Nosworthy, Mr. Richard Cater",male,21.0,0,0,A/4. 39886,7.8,,S
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
53,54,1,2,"Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)",female,29.0,1,0,2926,26.0,,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
55,56,1,1,"Woolner, Mr. Hugh",male,,0,0,19947,35.5,C52,S
56,57,1,2,"Rugg, Miss. Emily",female,21.0,0,0,C.A. 31026,10.5,,S
57,58,0,3,"Novel, Mr. Mansouer",male,28.5,0,0,2697,7.2292,,C
58,59,1,2,"West, Miss. Constance Mirium",female,5.0,1,2,C.A. 34651,27.75,,S
59,60,0,3,"Goodwin, Master. William Frederick",male,11.0,5,2,CA 2144,46.9,,S
60,61,0,3,"Sirayanian, Mr. Orsen",male,22.0,0,0,2669,7.2292,,C
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,B28,
62,63,0,1,"Harris, Mr. Henry Birkhardt",male,45.0,1,0,36973,83.475,C83,S
63,64,0,3,"Skoog, Master. Harald",male,4.0,3,2,347088,27.9,,S
64,65,0,1,"Stewart, Mr. Albert A",male,,0,0,PC 17605,27.7208,,C
65,66,1,3,"Moubarek, Master. Gerios",male,,1,1,2661,15.2458,,C
66,67,1,2,"Nye, Mrs. (Elizabeth Ramell)",female,29.0,0,0,C.A. 29395,10.5,F33,S
67,68,0,3,"Crease, Mr. Ernest James",male,19.0,0,0,S.P. 3464,8.1583,,S
68,69,1,3,"Andersson, Miss. Erna Alexandra",female,17.0,4,2,3101281,7.925,,S
69,70,0,3,"Kink, Mr. Vincenz",male,26.0,2,0,315151,8.6625,,S
70,71,0,2,"Jenkin, Mr. Stephen Curnow",male,32.0,0,0,C.A. 33111,10.5,,S
71,72,0,3,"Goodwin, Miss. Lillian Amy",female,16.0,5,2,CA 2144,46.9,,S
72,73,0,2,"Hood, Mr. Ambrose Jr",male,21.0,0,0,S.O.C. 14879,73.5,,S
73,74,0,3,"Chronopoulos, Mr. Apostolos",male,26.0,1,0,2680,14.4542,,C
74,75,1,3,"Bing, Mr. Lee",male,32.0,0,0,1601,56.4958,,S
75,76,0,3,"Moen, Mr. Sigurd Hansen",male,25.0,0,0,348123,7.65,F G73,S
76,77,0,3,"Staneff, Mr. Ivan",male,,0,0,349208,7.8958,,S
77,78,0,3,"Moutal, Mr. Rahamin Haim",male,,0,0,374746,8.05,,S
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0,,S
79,80,1,3,"Dowdell, Miss. Elizabeth",female,30.0,0,0,364516,12.475,,S
80,81,0,3,"Waelens, Mr. Achille",male,22.0,0,0,345767,9.0,,S
81,82,1,3,"Sheerlinck, Mr. Jan Baptist",male,29.0,0,0,345779,9.5,,S
82,83,1,3,"McDermott, Miss. Brigdet Delia",female,,0,0,330932,7.7875,,Q
83,84,0,1,"Carrau, Mr. Francisco M",male,28.0,0,0,113059,47.1,,S
84,85,1,2,"Ilett, Miss. Bertha",female,17.0,0,0,SO/C 14885,10.5,,S
85,86,1,3,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)",female,33.0,3,0,3101278,15.85,,S
86,87,0,3,"Ford, Mr. William Neal",male,16.0,1,3,W./C. 6608,34.375,,S
87,88,0,3,"Slocovski, Mr. Selman Francis",male,,0,0,SOTON/OQ 392086,8.05,,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0,C23 C25 C27,S
89,90,0,3,"Celotti, Mr. Francesco",male,24.0,0,0,343275,8.05,,S
90,91,0,3,"Christmann, Mr. Emil",male,29.0,0,0,343276,8.05,,S
91,92,0,3,"Andreasson, Mr. Paul Edvin",male,20.0,0,0,347466,7.8542,,S
92,93,0,1,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.175,E31,S
93,94,0,3,"Dean, Mr. Bertram Frank",male,26.0,1,2,C.A. 2315,20.575,,S
94,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.25,,S
95,96,0,3,"Shorney, Mr. Charles Joseph",male,,0,0,374910,8.05,,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.0,0,1,PC 17759,63.3583,D10 D12,C
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0,,S
99,100,0,2,"Kantor, Mr. Sinai",male,34.0,1,0,244367,26.0,,S
100,101,0,3,"Petranec, Miss. Matilda",female,28.0,0,0,349245,7.8958,,S
101,102,0,3,"Petroff, Mr. Pastcho (""Pentcho"")",male,,0,0,349215,7.8958,,S
102,103,0,1,"White, Mr. Richard Frasar",male,21.0,0,1,35281,77.2875,D26,S
103,104,0,3,"Johansson, Mr. Gustaf Joel",male,33.0,0,0,7540,8.6542,,S
104,105,0,3,"Gustafsson, Mr. Anders Vilhelm",male,37.0,2,0,3101276,7.925,,S
105,106,0,3,"Mionoff, Mr. Stoytcho",male,28.0,0,0,349207,7.8958,,S
106,107,1,3,"Salkjelsvik, Miss. Anna Kristine",female,21.0,0,0,343120,7.65,,S
107,108,1,3,"Moss, Mr. Albert Johan",male,,0,0,312991,7.775,,S
108,109,0,3,"Rekic, Mr. Tido",male,38.0,0,0,349249,7.8958,,S
109,110,1,3,"Moran, Miss. Bertha",female,,1,0,371110,24.15,,Q
110,111,0,1,"Porter, Mr. Walter Chamberlain",male,47.0,0,0,110465,52.0,C110,S
111,112,0,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,,C
112,113,0,3,"Barton, Mr. David John",male,22.0,0,0,324669,8.05,,S
113,114,0,3,"Jussila, Miss. Katriina",female,20.0,1,0,4136,9.825,,S
114,115,0,3,"Attalah, Miss. Malake",female,17.0,0,0,2627,14.4583,,C
115,116,0,3,"Pekoniemi, Mr. Edvard",male,21.0,0,0,STON/O 2. 3101294,7.925,,S
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.75,,Q
117,118,0,2,"Turpin, Mr. William John Robert",male,29.0,1,0,11668,21.0,,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C
119,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.0,4,2,347082,31.275,,S
120,121,0,2,"Hickman, Mr. Stanley George",male,21.0,2,0,S.O.C. 14879,73.5,,S
121,122,0,3,"Moore, Mr. Leonard Charles",male,,0,0,A4. 54510,8.05,,S
122,123,0,2,"Nasser, Mr. Nicholas",male,32.5,1,0,237736,30.0708,,C
123,124,1,2,"Webber, Miss. Susan",female,32.5,0,0,27267,13.0,E101,S
124,125,0,1,"White, Mr. Percival Wayland",male,54.0,0,1,35281,77.2875,D26,S
125,126,1,3,"Nicola-Yarred, Master. Elias",male,12.0,1,0,2651,11.2417,,C
126,127,0,3,"McMahon, Mr. Martin",male,,0,0,370372,7.75,,Q
127,128,1,3,"Madsen, Mr. Fridtjof Arne",male,24.0,0,0,C 17369,7.1417,,S
128,129,1,3,"Peter, Miss. Anna",female,,1,1,2668,22.3583,F E69,C
129,130,0,3,"Ekstrom, Mr. Johan",male,45.0,0,0,347061,6.975,,S
130,131,0,3,"Drazenoic, Mr. Jozef",male,33.0,0,0,349241,7.8958,,C
131,132,0,3,"Coelho, Mr. Domingos Fernandeo",male,20.0,0,0,SOTON/O.Q. 3101307,7.05,,S
132,133,0,3,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47.0,1,0,A/5. 3337,14.5,,S
133,134,1,2,"Weisz, Mrs. Leopold (Mathilde Francoise Pede)",female,29.0,1,0,228414,26.0,,S
134,135,0,2,"Sobey, Mr. Samuel James Hayden",male,25.0,0,0,C.A. 29178,13.0,,S
135,136,0,2,"Richard, Mr. Emile",male,23.0,0,0,SC/PARIS 2133,15.0458,,C
136,137,1,1,"Newsom, Miss. Helen Monypeny",female,19.0,0,2,11752,26.2833,D47,S
137,138,0,1,"Futrelle, Mr. Jacques Heath",male,37.0,1,0,113803,53.1,C123,S
138,139,0,3,"Osen, Mr. Olaf Elon",male,16.0,0,0,7534,9.2167,,S
139,140,0,1,"Giglio, Mr. Victor",male,24.0,0,0,PC 17593,79.2,B86,C
140,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,,0,2,2678,15.2458,,C
141,142,1,3,"Nysten, Miss. Anna Sofia",female,22.0,0,0,347081,7.75,,S
142,143,1,3,"Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)",female,24.0,1,0,STON/O2. 3101279,15.85,,S
143,144,0,3,"Burke, Mr. Jeremiah",male,19.0,0,0,365222,6.75,,Q
144,145,0,2,"Andrew, Mr. Edgardo Samuel",male,18.0,0,0,231945,11.5,,S
145,146,0,2,"Nicholls, Mr. Joseph Charles",male,19.0,1,1,C.A. 33112,36.75,,S
146,147,1,3,"Andersson, Mr. August Edvard (""Wennerstrom"")",male,27.0,0,0,350043,7.7958,,S
147,148,0,3,"Ford, Miss. Robina Maggie ""Ruby""",female,9.0,2,2,W./C. 6608,34.375,,S
148,149,0,2,"Navratil, Mr. Michel (""Louis M Hoffman"")",male,36.5,0,2,230080,26.0,F2,S
149,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0,,S
150,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.525,,S
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.05,,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5,,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,,0,0,Fa 265302,7.3125,,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,,C
156,157,1,3,"Gilnagh, Miss. Katherine ""Katie""",female,16.0,0,0,35851,7.7333,,Q
157,158,0,3,"Corn, Mr. Harry",male,30.0,0,0,SOTON/OQ 392090,8.05,,S
158,159,0,3,"Smiljanic, Mr. Mile",male,,0,0,315037,8.6625,,S
159,160,0,3,"Sage, Master. Thomas Henry",male,,8,2,CA. 2343,69.55,,S
160,161,0,3,"Cribb, Mr. John Hatfield",male,44.0,0,1,371362,16.1,,S
161,162,1,2,"Watt, Mrs. James (Elizabeth ""Bessie"" Inglis Milne)",female,40.0,0,0,C.A. 33595,15.75,,S
162,163,0,3,"Bengtsson, Mr. John Viktor",male,26.0,0,0,347068,7.775,,S
163,164,0,3,"Calic, Mr. Jovo",male,17.0,0,0,315093,8.6625,,S
164,165,0,3,"Panula, Master. Eino Viljami",male,1.0,4,1,3101295,39.6875,,S
165,166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.0,0,2,363291,20.525,,S
166,167,1,1,"Chibnall, Mrs. (Edith Martha Bowerman)",female,,0,1,113505,55.0,E33,S
167,168,0,3,"Skoog, Mrs. William (Anna Bernhardina Karlsson)",female,45.0,1,4,347088,27.9,,S
168,169,0,1,"Baumann, Mr. John D",male,,0,0,PC 17318,25.925,,S
169,170,0,3,"Ling, Mr. Lee",male,28.0,0,0,1601,56.4958,,S
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5,B19,S
171,172,0,3,"Rice, Master. Arthur",male,4.0,4,1,382652,29.125,,Q
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.0,1,1,347742,11.1333,,S
173,174,0,3,"Sivola, Mr. Antti Wilhelm",male,21.0,0,0,STON/O 2. 3101280,7.925,,S
174,175,0,1,"Smith, Mr. James Clinch",male,56.0,0,0,17764,30.6958,A7,C
175,176,0,3,"Klasen, Mr. Klas Albin",male,18.0,1,1,350404,7.8542,,S
176,177,0,3,"Lefebre, Master. Henry Forbes",male,,3,1,4133,25.4667,,S
177,178,0,1,"Isham, Miss. Ann Elizabeth",female,50.0,0,0,PC 17595,28.7125,C49,C
178,179,0,2,"Hale, Mr. Reginald",male,30.0,0,0,250653,13.0,,S
179,180,0,3,"Leonard, Mr. Lionel",male,36.0,0,0,LINE,0.0,,S
180,181,0,3,"Sage, Miss. Constance Gladys",female,,8,2,CA. 2343,69.55,,S
181,182,0,2,"Pernot, Mr. Rene",male,,0,0,SC/PARIS 2131,15.05,,C
182,183,0,3,"Asplund, Master. Clarence Gustaf Hugo",male,9.0,4,2,347077,31.3875,,S
183,184,1,2,"Becker, Master. Richard F",male,1.0,2,1,230136,39.0,F4,S
184,185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4.0,0,2,315153,22.025,,S
185,186,0,1,"Rood, Mr. Hugh Roscoe",male,,0,0,113767,50.0,A32,S
186,187,1,3,"O'Brien, Mrs. Thomas (Johanna ""Hannah"" Godfrey)",female,,1,0,370365,15.5,,Q
187,188,1,1,"Romaine, Mr. Charles Hallace (""Mr C Rolmane"")",male,45.0,0,0,111428,26.55,,S
188,189,0,3,"Bourke, Mr. John",male,40.0,1,1,364849,15.5,,Q
189,190,0,3,"Turcin, Mr. Stjepan",male,36.0,0,0,349247,7.8958,,S
190,191,1,2,"Pinsky, Mrs. (Rosa)",female,32.0,0,0,234604,13.0,,S
191,192,0,2,"Carbines, Mr. William",male,19.0,0,0,28424,13.0,,S
192,193,1,3,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19.0,1,0,350046,7.8542,,S
193,194,1,2,"Navratil, Master. Michel M",male,3.0,1,1,230080,26.0,F2,S
194,195,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44.0,0,0,PC 17610,27.7208,B4,C
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C
196,197,0,3,"Mernagh, Mr. Robert",male,,0,0,368703,7.75,,Q
197,198,0,3,"Olsen, Mr. Karl Siegwart Andreas",male,42.0,0,1,4579,8.4042,,S
198,199,1,3,"Madigan, Miss. Margaret ""Maggie""",female,,0,0,370370,7.75,,Q
199,200,0,2,"Yrois, Miss. Henriette (""Mrs Harbeck"")",female,24.0,0,0,248747,13.0,,S
200,201,0,3,"Vande Walle, Mr. Nestor Cyriel",male,28.0,0,0,345770,9.5,,S
201,202,0,3,"Sage, Mr. Frederick",male,,8,2,CA. 2343,69.55,,S
202,203,0,3,"Johanson, Mr. Jakob Alfred",male,34.0,0,0,3101264,6.4958,,S
203,204,0,3,"Youseff, Mr. Gerious",male,45.5,0,0,2628,7.225,,C
204,205,1,3,"Cohen, Mr. Gurshon ""Gus""",male,18.0,0,0,A/5 3540,8.05,,S
205,206,0,3,"Strom, Miss. Telma Matilda",female,2.0,0,1,347054,10.4625,G6,S
206,207,0,3,"Backstrom, Mr. Karl Alfred",male,32.0,1,0,3101278,15.85,,S
207,208,1,3,"Albimona, Mr. Nassef Cassem",male,26.0,0,0,2699,18.7875,,C
208,209,1,3,"Carr, Miss. Helen ""Ellen""",female,16.0,0,0,367231,7.75,,Q
209,210,1,1,"Blank, Mr. Henry",male,40.0,0,0,112277,31.0,A31,C
210,211,0,3,"Ali, Mr. Ahmed",male,24.0,0,0,SOTON/O.Q. 3101311,7.05,,S
211,212,1,2,"Cameron, Miss. Clear Annie",female,35.0,0,0,F.C.C. 13528,21.0,,S
212,213,0,3,"Perkin, Mr. John Henry",male,22.0,0,0,A/5 21174,7.25,,S
213,214,0,2,"Givard, Mr. Hans Kristensen",male,30.0,0,0,250646,13.0,,S
214,215,0,3,"Kiernan, Mr. Philip",male,,1,0,367229,7.75,,Q
215,216,1,1,"Newell, Miss. Madeleine",female,31.0,1,0,35273,113.275,D36,C
216,217,1,3,"Honkanen, Miss. Eliina",female,27.0,0,0,STON/O2. 3101283,7.925,,S
217,218,0,2,"Jacobsohn, Mr. Sidney Samuel",male,42.0,1,0,243847,27.0,,S
218,219,1,1,"Bazzani, Miss. Albina",female,32.0,0,0,11813,76.2917,D15,C
219,220,0,2,"Harris, Mr. Walter",male,30.0,0,0,W/C 14208,10.5,,S
220,221,1,3,"Sunderland, Mr. Victor Francis",male,16.0,0,0,SOTON/OQ 392089,8.05,,S
221,222,0,2,"Bracken, Mr. James H",male,27.0,0,0,220367,13.0,,S
222,223,0,3,"Green, Mr. George Henry",male,51.0,0,0,21440,8.05,,S
223,224,0,3,"Nenkoff, Mr. Christo",male,,0,0,349234,7.8958,,S
224,225,1,1,"Hoyt, Mr. Frederick Maxfield",male,38.0,1,0,19943,90.0,C93,S
225,226,0,3,"Berglund, Mr. Karl Ivar Sven",male,22.0,0,0,PP 4348,9.35,,S
226,227,1,2,"Mellors, Mr. William John",male,19.0,0,0,SW/PP 751,10.5,,S
227,228,0,3,"Lovell, Mr. John Hall (""Henry"")",male,20.5,0,0,A/5 21173,7.25,,S
228,229,0,2,"Fahlstrom, Mr. Arne Jonas",male,18.0,0,0,236171,13.0,,S
229,230,0,3,"Lefebre, Miss. Mathilde",female,,3,1,4133,25.4667,,S
230,231,1,1,"Harris, Mrs. Henry Birkhardt (Irene Wallach)",female,35.0,1,0,36973,83.475,C83,S
231,232,0,3,"Larsson, Mr. Bengt Edvin",male,29.0,0,0,347067,7.775,,S
232,233,0,2,"Sjostedt, Mr. Ernst Adolf",male,59.0,0,0,237442,13.5,,S
233,234,1,3,"Asplund, Miss. Lillian Gertrud",female,5.0,4,2,347077,31.3875,,S
234,235,0,2,"Leyson, Mr. Robert William Norman",male,24.0,0,0,C.A. 29566,10.5,,S
235,236,0,3,"Harknett, Miss. Alice Phoebe",female,,0,0,W./C. 6609,7.55,,S
236,237,0,2,"Hold, Mr. Stephen",male,44.0,1,0,26707,26.0,,S
237,238,1,2,"Collyer, Miss. Marjorie ""Lottie""",female,8.0,0,2,C.A. 31921,26.25,,S
238,239,0,2,"Pengelly, Mr. Frederick William",male,19.0,0,0,28665,10.5,,S
239,240,0,2,"Hunt, Mr. George Henry",male,33.0,0,0,SCO/W 1585,12.275,,S
240,241,0,3,"Zabour, Miss. Thamine",female,,1,0,2665,14.4542,,C
241,242,1,3,"Murphy, Miss. Katherine ""Kate""",female,,1,0,367230,15.5,,Q
242,243,0,2,"Coleridge, Mr. Reginald Charles",male,29.0,0,0,W./C. 14263,10.5,,S
243,244,0,3,"Maenpaa, Mr. Matti Alexanteri",male,22.0,0,0,STON/O 2. 3101275,7.125,,S
244,245,0,3,"Attalah, Mr. Sleiman",male,30.0,0,0,2694,7.225,,C
245,246,0,1,"Minahan, Dr. William Edward",male,44.0,2,0,19928,90.0,C78,Q
246,247,0,3,"Lindahl, Miss. Agda Thorilda Viktoria",female,25.0,0,0,347071,7.775,,S
247,248,1,2,"Hamalainen, Mrs. William (Anna)",female,24.0,0,2,250649,14.5,,S
248,249,1,1,"Beckwith, Mr. Richard Leonard",male,37.0,1,1,11751,52.5542,D35,S
249,250,0,2,"Carter, Rev. Ernest Courtenay",male,54.0,1,0,244252,26.0,,S
250,251,0,3,"Reed, Mr. James George",male,,0,0,362316,7.25,,S
251,252,0,3,"Strom, Mrs. Wilhelm (Elna Matilda Persson)",female,29.0,1,1,347054,10.4625,G6,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.55,C87,S
253,254,0,3,"Lobb, Mr. William Arthur",male,30.0,1,0,A/5. 3336,16.1,,S
254,255,0,3,"Rosblom, Mrs. Viktor (Helena Wilhelmina)",female,41.0,0,2,370129,20.2125,,S
255,256,1,3,"Touma, Mrs. Darwis (Hanne Youssef Razi)",female,29.0,0,2,2650,15.2458,,C
256,257,1,1,"Thorne, Mrs. Gertrude Maybelle",female,,0,0,PC 17585,79.2,,C
257,258,1,1,"Cherry, Miss. Gladys",female,30.0,0,0,110152,86.5,B77,S
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,,C
259,260,1,2,"Parrish, Mrs. (Lutie Davis)",female,50.0,0,1,230433,26.0,,S
260,261,0,3,"Smith, Mr. Thomas",male,,0,0,384461,7.75,,Q
261,262,1,3,"Asplund, Master. Edvin Rojj Felix",male,3.0,4,2,347077,31.3875,,S
262,263,0,1,"Taussig, Mr. Emil",male,52.0,1,1,110413,79.65,E67,S
263,264,0,1,"Harrison, Mr. William",male,40.0,0,0,112059,0.0,B94,S
264,265,0,3,"Henry, Miss. Delia",female,,0,0,382649,7.75,,Q
265,266,0,2,"Reeves, Mr. David",male,36.0,0,0,C.A. 17248,10.5,,S
266,267,0,3,"Panula, Mr. Ernesti Arvid",male,16.0,4,1,3101295,39.6875,,S
267,268,1,3,"Persson, Mr. Ernst Ulrik",male,25.0,1,0,347083,7.775,,S
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.0,0,1,PC 17582,153.4625,C125,S
269,270,1,1,"Bissette, Miss. Amelia",female,35.0,0,0,PC 17760,135.6333,C99,S
270,271,0,1,"Cairns, Mr. Alexander",male,,0,0,113798,31.0,,S
271,272,1,3,"Tornquist, Mr. William Henry",male,25.0,0,0,LINE,0.0,,S
272,273,1,2,"Mellinger, Mrs. (Elizabeth Anne Maidment)",female,41.0,0,1,250644,19.5,,S

Pode-se definir outro separador (com o parâmetro `sep`), ou como serão representados os valores em falta (com o parâmetro `na_rep`):

In [25]:
df7

    Numero               Nome   FQ1   FQ2
0  12345.0  Francisco Martins  12.0  14.0
1  43212.0           Ana Rosa   NaN  12.0
2  43231.0     Maria Cristina  15.0   NaN
3      NaN                NaN   NaN   NaN
4  12334.0        André Silva   NaN   9.0

In [26]:
import sys

df7.to_csv(sys.stdout, sep=':', na_rep='NULL')

:Numero:Nome:FQ1:FQ2
0:12345.0:Francisco Martins:12.0:14.0
1:43212.0:Ana Rosa:NULL:12.0
2:43231.0:Maria Cristina:15.0:NULL
3:NULL:NULL:NULL:NULL
4:12334.0:André Silva:NULL:9.0

Caso não se queiram guardar os índices das linhas ou das colunas, podem-se passar os parâmetros `index` e/ou `header` com o valor `False` para não serem guardados os índices das linhas e/ou colunas, respetivamente.

In [27]:
df7.to_csv(sys.stdout, sep=':', index=False, header=False)

12345.0:Francisco Martins:12.0:14.0
43212.0:Ana Rosa::12.0
43231.0:Maria Cristina:15.0:
:::
12334.0:André Silva::9.0

Caso se queira guardar apenas algumas colunas, podem-se passar o parâmetro `columns` com a lista de colunas a guardar. Caso se queiram algumas apenas algumas linhas, podem-se filtrar primeiro, e depois utilizar o método `to_csv` ao resultado. O parâmetro `index_label` permite indicar qual o _label_ a utilizar para a coluna do índice (por vezes pode não estar definido nos dados)

In [28]:
titanic.iloc[::100].to_csv(sys.stdout, sep=':',
                           columns=['Name', 'Sex', 'Age'], index_label='idx')

idx:Name:Sex:Age
0:Braund, Mr. Owen Harris:male:22.0
100:Petranec, Miss. Matilda:female:28.0
200:Vande Walle, Mr. Nestor Cyriel:male:28.0
300:"Kelly, Miss. Anna Katherine ""Annie Kate""":female:
400:Niskanen, Mr. Juha:male:39.0
500:Calic, Mr. Petar:male:17.0
600:Jacobsohn, Mrs. Sidney Samuel (Amy Frances Christy):female:24.0
700:Astor, Mrs. John Jacob (Madeleine Talmadge Force):female:18.0
800:Ponesell, Mr. Martin:male:34.0

## Ficheiros EXCEL

O pandas permite ler diretamente ficheiros do EXCEL, utilizando a função `read_excel`, e exportar um `DataFrame` ou uma `Series` para ficheiros EXCEL através do método `to_excel`, mas no _background_ utiliza o módulo `openpyxl`, que precisa de ser instalado previamente utilizando o `conda`:

```bash
> conda install openpyxl
```

ou o `pip`:

```bash
> pip install openpyxl
```

### A função `read_excel(...)`

A função `read_excel` recebe como argumento o nome de um ficheiros EXCEL, e devolve um `DataFrame` com os dados da primeira folha existente no ficheiro.

In [29]:
pd.read_excel(r'exemplos\ex5.xlsx')

,Nome,Sobrenome,Cidade,Profissão,Salário,Data de admissão,Gastos Mensais
0,Alberto,Letão,Evora,Motorista,620.0,1997-09-24,378000.0
1,Ana,Cardoso,Braga,Gerente de marketing,1500.0,1997-08-15,135000.0
2,André,Marques,Coimbra,Caixa,890.0,1989-07-14,650000.0
3,André,Ramos,Sines,Pedreiro,450.0,1995-08-18,100000.0
4,André,Pereira,Setubal,Gerente de marketing,1450.0,1998-12-19,120000.0
5,António,Sobreiro,Matosinhos,Encarregado,1250.0,1997-08-09,75000.0
6,Bartolomeu,Fisga,Lisboa,NaN,NaN,NaT,120000.0
7,Beatriz,Conde,Braga,Caixa,830.0,2001-11-16,120000.0
8,Ben,Hur,Faro,Segurança,750.0,1997-05-15,123000.0
9,Bianca,Marques,Setubal,Empregada Limpeza,500.0,1999-08-27,102500.0
10,Carlos,Santos,Faro,Encarregado,1200.0,1998-05-27,1123400.0
11,Cássio,Nossa,Tavira,Assessor de comunicação,1700.0,2002-04-15,135000.0
12,César,Alves,Portimão,Encarregado,1100.0,2002-03-28,75000.0
13,Cládio,Silva,Leiria,Técnico,460.0,1997-05-17,200000.0
14,Daniel,Barros,Sines,Gerente de marketing,1400.0,NaT,NaN
15,Elton,Teira,Portalegre,Marceneiro,970.0,1998-02-05,450000.0
16,Fábio,Frota,Portimão,Telefonista,610.0,1998-05-01,100000.0
17,Fabrício,Vargas,Matosinhos,Empregada Limpeza,440.0,2001-09-29,120000.0
18,Flávia,Marques,Olhão,Caixa,870.0,1998-05-23,20000.0
19,Geraldo,Sodré,Faro,Técnico,NaN,1994-05-15,500000.0
20,Geraldo,Barcelos,Coimbra,NaN,850.0,1998-11-15,NaN
21,Gusmão,Leve,Lisboa,NaN,860.0,1998-05-27,25000.0
22,Heraldo,Barros,Lisboa,Empregada Limpeza,460.0,2000-07-02,120000.0
23,Jânio,França,Setubal,Gerente financeiro,2300.0,1995-08-21,200000.0
24,Jardel,Carvalho,Portalegre,Telefonista,600.0,2001-12-15,200000.0
25,João,Beirão,Coimbra,Motorista,650.0,1995-03-29,120000.0
26,José,Silva,Evora,Marceneiro,1000.0,1995-08-13,890000.0
27,Julia,França,Almada,Caixa,880.0,1996-08-24,120000.0
28,Júlio,Marcelo,Beja,Contabilista,1600.0,1995-08-15,100000.0
29,Lauro,Zulu,Almada,Telefonista,600.0,1996-08-21,100000.0
30,Leandro,Marcelo,Amadora,Contabilista,1500.0,1996-05-12,75000.0
31,Marcos,Silva,Lisboa,Caixa,900.0,1989-03-12,100000.0
32,Maria,Ferreira,Amadora,Empregada Limpeza,480.0,1999-11-02,35000.0
33,Mario,Ferreira,Lisboa,Técnico,480.0,1996-08-24,120000.0
34,Marlene,Caldas,Evora,Empregada Limpeza,420.0,2001-11-22,123000.0
35,Marta,Silva,Porto,Caixa,820.0,2002-09-15,100000.0
36,Omar,Cetão,Porto,Segurança,675.0,1999-08-10,10000.0
37,Paula,Dona,Elvas,Segurança,625.0,2002-02-02,128500.0
38,Paulo,Carvalho,Sintra,Gerente de vendas,1840.0,1999-11-08,110000.0
39,Paulo,Pereira,Almada,Caixa,840.0,1999-11-14,125000.0
40,Paulo,Massaranduba,Leiria,Segurança,650.0,2001-01-01,10000.0
41,Roberto,Kenzo,Porto,Gerente de vendas,1900.0,1991-09-03,500000.0
42,Rodrigo,Quintanilha,Porto,Encarregado,1150.0,2001-09-17,100000.0
43,Rogério,Silva,Faro,Encarregado,1300.0,1989-07-14,120000.0
44,Rosa,Telão,Elvas,Segurança,725.0,1998-04-12,235000.0
45,Ruben,Barranco,Faro,Motorista,590.0,2000-07-04,75000.0
46,Rui,Derroda,Matosinhos,Motorista,605.0,1999-08-21,40000.0
47,Sandra,Peixoto,Almada,Técnico,400.0,2000-05-14,200000.0
48,Sandro,Cardoso,Porto,Técnico,440.0,1997-06-07,128500.0
49,Sujiro,Kifuja,Olhão,Contabilista,1400.0,2002-08-14,378000.0
50,Tamiro,Vinho,Tavira,Segurança,700.0,1998-05-02,130000.0
51,Tânia,Marcelo,Loulé,Gerente de vendas,1870.0,1994-06-05,250000.0
52,Wesley,Cardoso,Lisboa,Técnico,420.0,1999-08-28,90000.0
53,Yara,Cardoso,Leiria,Telefonista,650.0,1995-08-12,100000.0
54,Yeu,Kon Iço,Sintra,Técnico em eletrónica,870.0,1996-08-05,10000.0

Caso se pretenda outra folha que não a primeira, pode-se utilizar o argumento `sheet_name`,passando o nome da folha:

In [30]:
pd.read_excel(r'exemplos\ex5.xlsx', sheet_name='Folha 2')

,Nome,Sobrenome,Cidade,Profissão,Salário,Data de admissão,Gastos Mensais
0,Marcos,Silva,Lisboa,Caixa,900,1989-03-12,100000
1,Rogério,Silva,Faro,Encarregado,1300,1989-07-14,120000
2,André,Marques,Coimbra,Caixa,890,1989-07-14,650000
3,Roberto,Kenzo,Porto,Gerente de vendas,1900,1991-09-03,500000
4,Geraldo,Sodré,Faro,Técnico,500,1994-05-15,500000
5,Tânia,Marcelo,Loulé,Gerente de vendas,1870,1994-06-05,250000
6,João,Beirão,Coimbra,Motorista,650,1995-03-29,120000
7,Yara,Cardoso,Leiria,Telefonista,650,1995-08-12,100000
8,José,Silva,Evora,Marceneiro,1000,1995-08-13,890000
9,Júlio,Marcelo,Beja,Contabilista,1600,1995-08-15,100000

Ou um índice numérico com o número da folha que se quer (a primeira folha tem o índice `0`):

In [31]:
pd.read_excel(r'exemplos\ex5.xlsx', sheet_name=1)

,Nome,Sobrenome,Cidade,Profissão,Salário,Data de admissão,Gastos Mensais
0,Marcos,Silva,Lisboa,Caixa,900,1989-03-12,100000
1,Rogério,Silva,Faro,Encarregado,1300,1989-07-14,120000
2,André,Marques,Coimbra,Caixa,890,1989-07-14,650000
3,Roberto,Kenzo,Porto,Gerente de vendas,1900,1991-09-03,500000
4,Geraldo,Sodré,Faro,Técnico,500,1994-05-15,500000
5,Tânia,Marcelo,Loulé,Gerente de vendas,1870,1994-06-05,250000
6,João,Beirão,Coimbra,Motorista,650,1995-03-29,120000
7,Yara,Cardoso,Leiria,Telefonista,650,1995-08-12,100000
8,José,Silva,Evora,Marceneiro,1000,1995-08-13,890000
9,Júlio,Marcelo,Beja,Contabilista,1600,1995-08-15,100000

Caso se queira ler várias folhas do ficheiros pode-se passar uma lista com as folhas a ler, e será devolvido um dicionário, onde a chave será o nome da folha e o valor será um `DataFrame` com os dados da respetiva folha.

Caso se queira ler todas as folhas, deve-se indicar `sheet_name=None`:

In [32]:
data3 = pd.read_excel(r'exemplos\ex5.xlsx', sheet_name=None)
type(data3)

dict

In [33]:
data3.keys()

dict_keys(['Folha 1', 'Folha 2'])

In [34]:
data3['Folha 2']

,Nome,Sobrenome,Cidade,Profissão,Salário,Data de admissão,Gastos Mensais
0,Marcos,Silva,Lisboa,Caixa,900,1989-03-12,100000
1,Rogério,Silva,Faro,Encarregado,1300,1989-07-14,120000
2,André,Marques,Coimbra,Caixa,890,1989-07-14,650000
3,Roberto,Kenzo,Porto,Gerente de vendas,1900,1991-09-03,500000
4,Geraldo,Sodré,Faro,Técnico,500,1994-05-15,500000
5,Tânia,Marcelo,Loulé,Gerente de vendas,1870,1994-06-05,250000
6,João,Beirão,Coimbra,Motorista,650,1995-03-29,120000
7,Yara,Cardoso,Leiria,Telefonista,650,1995-08-12,100000
8,José,Silva,Evora,Marceneiro,1000,1995-08-13,890000
9,Júlio,Marcelo,Beja,Contabilista,1600,1995-08-15,100000

### O método `to_excel(...)`

Para guardar um `DataFrame` num ficheiro basta indicar o nome do ficheiro no método `to_excel`:

In [35]:
df7.to_excel('out1.xlsx')

In [36]:
!ls -l out1.xlsx

-rw-r--r-- 1 pmguerre 1049089 5065 set 22 18:26 out1.xlsx

### A classe `ExcelWriter(...)`

Caso se queira guardar vários `DataFrame` no mesmo ficheiros EXCEL, é necessário primeiro criar um objecto `ExcelWriter`:

In [37]:
writer = pd.ExcelWriter('out2.xlsx')

Depois gravar os `DataFrame`/`Series` pretendidos para esse objecto:

In [38]:
df1.to_excel(writer, sheet_name='Folha1')
df4.to_excel(writer, sheet_name='Folha2')
df5.to_excel(writer, sheet_name='Folha3')

Sem esquecer de fechar o ficheiro depois de gravar tudo:

In [39]:
writer.close()

In [40]:
!ls -l out2.xlsx

-rw-r--r-- 1 pmguerre 1049089 6288 set 22 18:26 out2.xlsx

## Ficheiros JSON

O formato JSON (_JavaScript Object Notation_) é atualmente um dos formatos standard para envio de dados via pedidos HTTP entre _browsers_ e outras aplicações.

No entanto, a estrutura de um documento JSON não é uma obrigatoriamente uma tabela, pelo que pode ser necessário algum cuidado ao ler esses ficheiros.

### O módulo `json`

O módulo `json` implementa um conjunto de funções para traduzir JSON para dicionários do Python.

Suponha o seguinte ficheiro JSON:

In [41]:
!type exemplos\persons.json

{"name":{"0":"Margaret","1":"John","2":"Claudia","3":"Mary","4":"Peter","5":"Helga","6":"Heidi","7":"Mary"},"age":{"0":17,"1":13,"2":44,"3":55,"4":71,"5":7,"6":16,"7":70},"gender":{"0":"F","1":"M","2":"F","3":"F","4":"M","5":"F","6":"F","7":"F"},"country":{"0":"PT","1":"PT","2":"PT","3":"PT","4":"PT","5":"PT","6":"PT","7":"PT"},"pet":{"0":"cat","1":"dog","2":"fish","3":"cat","4":"cat","5":"fish","6":"bird","7":"cat"},"height":{"0":170.0,"1":172.0,"2":178.0,"3":160.0,"4":165.0,"5":150.0,"6":151.0,"7":null},"classification":{"0":4,"1":3,"2":2,"3":5,"4":1,"5":7,"6":6,"7":7}}

Vamos ler o ficheiro com a função `load`, que faz a desserialização de um documento JSON para um dicionário do Python:

In [42]:
import json

with open(r'exemplos\persons.json') as file:
    data = json.load(file)

type(data)

dict

A função `dumps` permite serializar um objecto para uma _string_:

In [43]:
print(json.dumps(data, indent=4))

{
    "name": {
        "0": "Margaret",
        "1": "John",
        "2": "Claudia",
        "3": "Mary",
        "4": "Peter",
        "5": "Helga",
        "6": "Heidi",
        "7": "Mary"
    },
    "age": {
        "0": 17,
        "1": 13,
        "2": 44,
        "3": 55,
        "4": 71,
        "5": 7,
        "6": 16,
        "7": 70
    },
    "gender": {
        "0": "F",
        "1": "M",
        "2": "F",
        "3": "F",
        "4": "M",
        "5": "F",
        "6": "F",
        "7": "F"
    },
    "country": {
        "0": "PT",
        "1": "PT",
        "2": "PT",
        "3": "PT",
        "4": "PT",
        "5": "PT",
        "6": "PT",
        "7": "PT"
    },
    "pet": {
        "0": "cat",
        "1": "dog",
        "2": "fish",
        "3": "cat",
        "4": "cat",
        "5": "fish",
        "6": "bird",
        "7": "cat"
    },
    "height": {
        "0": 170.0,
        "1": 172.0,
        "2": 178.0,
        "3": 160.0,
        "4": 165.0,
        "5": 150.0,
        "6": 151.0,
        "7": null
    },
    "classification": {
        "0": 4,
        "1": 3,
        "2": 2,
        "3": 5,
        "4": 1,
        "5": 7,
        "6": 6,
        "7": 7
    }
}

Neste caso, o JSON define um dicionário de dicionários, com uma estrutura de tabela, pelo que pode criar um `DataFrame` com base no dicionário definido com o `json.load`:

In [44]:
pd.DataFrame(data)

       name  age gender country   pet  height  classification
0  Margaret   17      F      PT   cat   170.0               4
1      John   13      M      PT   dog   172.0               3
2   Claudia   44      F      PT  fish   178.0               2
3      Mary   55      F      PT   cat   160.0               5
4     Peter   71      M      PT   cat   165.0               1
5     Helga    7      F      PT  fish   150.0               7
6     Heidi   16      F      PT  bird   151.0               6
7      Mary   70      F      PT   cat     NaN               7

### A função `read_json(...)`

O pandas tem a função `read_json`, que permite ler diretamente um documento JSON para um `DataFrame`:

In [45]:
!type exemplos\persons.json

{"name":{"0":"Margaret","1":"John","2":"Claudia","3":"Mary","4":"Peter","5":"Helga","6":"Heidi","7":"Mary"},"age":{"0":17,"1":13,"2":44,"3":55,"4":71,"5":7,"6":16,"7":70},"gender":{"0":"F","1":"M","2":"F","3":"F","4":"M","5":"F","6":"F","7":"F"},"country":{"0":"PT","1":"PT","2":"PT","3":"PT","4":"PT","5":"PT","6":"PT","7":"PT"},"pet":{"0":"cat","1":"dog","2":"fish","3":"cat","4":"cat","5":"fish","6":"bird","7":"cat"},"height":{"0":170.0,"1":172.0,"2":178.0,"3":160.0,"4":165.0,"5":150.0,"6":151.0,"7":null},"classification":{"0":4,"1":3,"2":2,"3":5,"4":1,"5":7,"6":6,"7":7}}

In [46]:
persons = pd.read_json(r'exemplos\persons.json')
persons

       name  age gender country   pet  height  classification
0  Margaret   17      F      PT   cat   170.0               4
1      John   13      M      PT   dog   172.0               3
2   Claudia   44      F      PT  fish   178.0               2
3      Mary   55      F      PT   cat   160.0               5
4     Peter   71      M      PT   cat   165.0               1
5     Helga    7      F      PT  fish   150.0               7
6     Heidi   16      F      PT  bird   151.0               6
7      Mary   70      F      PT   cat     NaN               7

No entanto, nem sempre um ficheiro JSON tem uma estrutura em forma de tabela de forma a ser facilmente lido para um `DataFrame`. Considere o seguinte ficheiro, com informação sobre filmes:

In [47]:
!type exemplos\movies.json

{
    "movies": [
        {
            "id": 1,
            "title": "Inception",
            "director": "Christopher Nolan",
            "release_year": 2010,
            "genre": [
                "Sci-Fi",
                "Action"
            ],
            "duration": 148,
            "cast": [
                {
                    "actor": "Leonardo DiCaprio",
                    "role": "Cobb"
                },
                {
                    "actor": "Joseph Gordon-Levitt",
                    "role": "Arthur"
                }
            ],
            "ratings": {
                "IMDb": 8.8,
                "Rotten Tomatoes": 87,
                "Metacritic": 74
            },
            "box_office": {
                "budget": 160000000,
                "gross_worldwide": 829895144
            }
        },
        {
            "id": 2,
            "title": "The Matrix",
            "director": "The Wachowskis",
            "release_year": 1999,
            "genre": [
                "Sci-Fi",
                "Action"
            ],
            "duration": 136,
            "cast": [
                {
                    "actor": "Keanu Reeves",
                    "role": "Neo"
                },
                {
                    "actor": "Laurence Fishburne",
                    "role": "Morpheus"
                }
            ],
            "ratings": {
                "IMDb": 8.7,
                "Rotten Tomatoes": 87,
                "Metacritic": 73
            },
            "box_office": {
                "budget": 63000000,
                "gross_worldwide": 463517383
            }
        }
    ]
}

Pode-se observar que a estrutura do ficheiro JSON é a seguinte:

```
documento
└── movies
    ├── filme 1
    │   ├── id
    │   ├── title
    │   ├── director
    │   ├── release_year
    │   ├── genre       → lista de strings
    │   ├── duration
    │   ├── cast        → lista de dicionários
    │   ├── ratings     → dicionário
    │   └── box_office  → dicionário
    ├── filme 2
        ⋮
```

Neste caso, a função `read_json` resulta num `DataFrame` com uma coluna da nome `movies` (a entidade principal do JSON), e duas linhas, que correspondem aos dois dicionários da entidade `movies`:

In [48]:
data = pd.read_json(r'exemplos\movies.json')
data

                                              movies
0  {'id': 1, 'title': 'Inception', 'director': 'C...
1  {'id': 2, 'title': 'The Matrix', 'director': '...

Pode-se ver que na coluna `movies` (a única coluna do `DataFrame`) cada linha é composta de um documento JSON, que pode ser transformado numa tabela utilizando a função `json_normalize` do pandas:

In [49]:
movies = pd.json_normalize(data['movies'])
movies

,id,title,director,release_year,genre,duration,cast,ratings.IMDb,ratings.Rotten Tomatoes,ratings.Metacritic,box_office.budget,box_office.gross_worldwide
0,1,Inception,Christopher Nolan,2010,"[Sci-Fi, Action]",148,"[{'actor': 'Leonardo DiCaprio', 'role': 'Cobb'...",8.8,87,74,160000000,829895144
1,2,The Matrix,The Wachowskis,1999,"[Sci-Fi, Action]",136,"[{'actor': 'Keanu Reeves', 'role': 'Neo'}, {'a...",8.7,87,73,63000000,463517383

De forma mais ou menos automática, e sempre que possivel, a função `json_normalize` tenta transformar as diversas subestruturas do JSON numa tabela, concatenando as "chaves" e "sub-chaves" por defeito com um ponto final. No exemplo acima pode-se ver que foi inserida a coluna `ratings.IMDb`, junção a chave `ratings` com a chave `IMDb` do JSON, e o mesmo para as colunas seguintes (`ratings.Rotten Tomatoes`, `ratings.Metacritic`, `box_office.budget` e `box_office.gross_worldwide`).

No entanto, o mesmo não aconteceu com as chaves `genre` e `cast`, pois cada uma delas define uma lista.

O que acontece com as listas é que para transformar a lista numa tabela é preciso "duplicar" todos os valores para cada elemento da lista (produto cartesiano). Por exemplo, o filme Inception tem dois géneros: Sci-Fi e Action, pelo que iriam aparecer duas linhas com os dados do filme Inception, só variando o coluna `genre`.

Isso pode ser feito com a método `explode` do `DataFrame`:

In [50]:
movies2 = movies.explode('genre')
movies2

,id,title,director,release_year,genre,duration,cast,ratings.IMDb,ratings.Rotten Tomatoes,ratings.Metacritic,box_office.budget,box_office.gross_worldwide
0,1,Inception,Christopher Nolan,2010,Sci-Fi,148,"[{'actor': 'Leonardo DiCaprio', 'role': 'Cobb'...",8.8,87,74,160000000,829895144
0,1,Inception,Christopher Nolan,2010,Action,148,"[{'actor': 'Leonardo DiCaprio', 'role': 'Cobb'...",8.8,87,74,160000000,829895144
1,2,The Matrix,The Wachowskis,1999,Sci-Fi,136,"[{'actor': 'Keanu Reeves', 'role': 'Neo'}, {'a...",8.7,87,73,63000000,463517383
1,2,The Matrix,The Wachowskis,1999,Action,136,"[{'actor': 'Keanu Reeves', 'role': 'Neo'}, {'a...",8.7,87,73,63000000,463517383

Note-se que mesmo o índice foi duplicado, ou seja, se antes existiam duas linhas, cada um com diferentes índices (`0` e `1` no exemplo acima), agora existem 4 linhas (cada filme foi duplicado duas vezes pois cada filme tinha dois géneros), mas o índice de cada filme continua o mesmo.

Caso se queira reindexar as linhas, de forma a todas elas terem um índice diferente, é preciso utilizar o método `reset_index`. Por defeito este método vai criar um novo índice numérico, com valores entre `0` e `N-1`, e o índice antigo passa a uma coluna do `DataFrame`:

In [51]:
movies.explode('genre').reset_index()

,index,id,title,director,release_year,genre,duration,cast,ratings.IMDb,ratings.Rotten Tomatoes,ratings.Metacritic,box_office.budget,box_office.gross_worldwide
0,0,1,Inception,Christopher Nolan,2010,Sci-Fi,148,"[{'actor': 'Leonardo DiCaprio', 'role': 'Cobb'...",8.8,87,74,160000000,829895144
1,0,1,Inception,Christopher Nolan,2010,Action,148,"[{'actor': 'Leonardo DiCaprio', 'role': 'Cobb'...",8.8,87,74,160000000,829895144
2,1,2,The Matrix,The Wachowskis,1999,Sci-Fi,136,"[{'actor': 'Keanu Reeves', 'role': 'Neo'}, {'a...",8.7,87,73,63000000,463517383
3,1,2,The Matrix,The Wachowskis,1999,Action,136,"[{'actor': 'Keanu Reeves', 'role': 'Neo'}, {'a...",8.7,87,73,63000000,463517383

Caso não se queira guardar o índice antigo no `DataFrame`, pode-se utilizar o parâmetro `drop=True`:

In [52]:
movies3 = movies.explode('genre').reset_index(drop=True)
movies3

,id,title,director,release_year,genre,duration,cast,ratings.IMDb,ratings.Rotten Tomatoes,ratings.Metacritic,box_office.budget,box_office.gross_worldwide
0,1,Inception,Christopher Nolan,2010,Sci-Fi,148,"[{'actor': 'Leonardo DiCaprio', 'role': 'Cobb'...",8.8,87,74,160000000,829895144
1,1,Inception,Christopher Nolan,2010,Action,148,"[{'actor': 'Leonardo DiCaprio', 'role': 'Cobb'...",8.8,87,74,160000000,829895144
2,2,The Matrix,The Wachowskis,1999,Sci-Fi,136,"[{'actor': 'Keanu Reeves', 'role': 'Neo'}, {'a...",8.7,87,73,63000000,463517383
3,2,The Matrix,The Wachowskis,1999,Action,136,"[{'actor': 'Keanu Reeves', 'role': 'Neo'}, {'a...",8.7,87,73,63000000,463517383

Pode-se fazer o mesmo com a coluna `cast`, mas ligeiramente diferente, pois a mesmo é uma lista de dicionários. Começa-se por "explodir" os elementos da lista cada um para a sua linha, utilizando o método `explode`:

In [53]:
movies3 = movies3.explode('cast').reset_index(drop=True)
movies3

,id,title,director,release_year,genre,duration,cast,ratings.IMDb,ratings.Rotten Tomatoes,ratings.Metacritic,box_office.budget,box_office.gross_worldwide
0,1,Inception,Christopher Nolan,2010,Sci-Fi,148,"{'actor': 'Leonardo DiCaprio', 'role': 'Cobb'}",8.8,87,74,160000000,829895144
1,1,Inception,Christopher Nolan,2010,Sci-Fi,148,"{'actor': 'Joseph Gordon-Levitt', 'role': 'Art...",8.8,87,74,160000000,829895144
2,1,Inception,Christopher Nolan,2010,Action,148,"{'actor': 'Leonardo DiCaprio', 'role': 'Cobb'}",8.8,87,74,160000000,829895144
3,1,Inception,Christopher Nolan,2010,Action,148,"{'actor': 'Joseph Gordon-Levitt', 'role': 'Art...",8.8,87,74,160000000,829895144
4,2,The Matrix,The Wachowskis,1999,Sci-Fi,136,"{'actor': 'Keanu Reeves', 'role': 'Neo'}",8.7,87,73,63000000,463517383
5,2,The Matrix,The Wachowskis,1999,Sci-Fi,136,"{'actor': 'Laurence Fishburne', 'role': 'Morph...",8.7,87,73,63000000,463517383
6,2,The Matrix,The Wachowskis,1999,Action,136,"{'actor': 'Keanu Reeves', 'role': 'Neo'}",8.7,87,73,63000000,463517383
7,2,The Matrix,The Wachowskis,1999,Action,136,"{'actor': 'Laurence Fishburne', 'role': 'Morph...",8.7,87,73,63000000,463517383

No entanto como as subchaves de `cast` não são valores únicos, mas sim subchaves, é preciso voltar a normalizar esta coluna:

In [54]:
cast = pd.json_normalize(movies3['cast'])
cast

                  actor      role
0     Leonardo DiCaprio      Cobb
1  Joseph Gordon-Levitt    Arthur
2     Leonardo DiCaprio      Cobb
3  Joseph Gordon-Levitt    Arthur
4          Keanu Reeves       Neo
5    Laurence Fishburne  Morpheus
6          Keanu Reeves       Neo
7    Laurence Fishburne  Morpheus

E depois concatenar os dois `DataFrame`:

In [55]:
pd.concat([movies3, cast], axis=1)

,id,title,director,release_year,genre,duration,cast,ratings.IMDb,ratings.Rotten Tomatoes,ratings.Metacritic,box_office.budget,box_office.gross_worldwide,actor,role
0,1,Inception,Christopher Nolan,2010,Sci-Fi,148,"{'actor': 'Leonardo DiCaprio', 'role': 'Cobb'}",8.8,87,74,160000000,829895144,Leonardo DiCaprio,Cobb
1,1,Inception,Christopher Nolan,2010,Sci-Fi,148,"{'actor': 'Joseph Gordon-Levitt', 'role': 'Art...",8.8,87,74,160000000,829895144,Joseph Gordon-Levitt,Arthur
2,1,Inception,Christopher Nolan,2010,Action,148,"{'actor': 'Leonardo DiCaprio', 'role': 'Cobb'}",8.8,87,74,160000000,829895144,Leonardo DiCaprio,Cobb
3,1,Inception,Christopher Nolan,2010,Action,148,"{'actor': 'Joseph Gordon-Levitt', 'role': 'Art...",8.8,87,74,160000000,829895144,Joseph Gordon-Levitt,Arthur
4,2,The Matrix,The Wachowskis,1999,Sci-Fi,136,"{'actor': 'Keanu Reeves', 'role': 'Neo'}",8.7,87,73,63000000,463517383,Keanu Reeves,Neo
5,2,The Matrix,The Wachowskis,1999,Sci-Fi,136,"{'actor': 'Laurence Fishburne', 'role': 'Morph...",8.7,87,73,63000000,463517383,Laurence Fishburne,Morpheus
6,2,The Matrix,The Wachowskis,1999,Action,136,"{'actor': 'Keanu Reeves', 'role': 'Neo'}",8.7,87,73,63000000,463517383,Keanu Reeves,Neo
7,2,The Matrix,The Wachowskis,1999,Action,136,"{'actor': 'Laurence Fishburne', 'role': 'Morph...",8.7,87,73,63000000,463517383,Laurence Fishburne,Morpheus

E apagando em simultâneo a coluna `cast` (pois a informação já aparece nas colunas `actor` e `role`):

In [56]:
movies3 = pd.concat([movies3.drop(columns='cast'), cast], axis=1)
movies3

,id,title,director,release_year,genre,duration,ratings.IMDb,ratings.Rotten Tomatoes,ratings.Metacritic,box_office.budget,box_office.gross_worldwide,actor,role
0,1,Inception,Christopher Nolan,2010,Sci-Fi,148,8.8,87,74,160000000,829895144,Leonardo DiCaprio,Cobb
1,1,Inception,Christopher Nolan,2010,Sci-Fi,148,8.8,87,74,160000000,829895144,Joseph Gordon-Levitt,Arthur
2,1,Inception,Christopher Nolan,2010,Action,148,8.8,87,74,160000000,829895144,Leonardo DiCaprio,Cobb
3,1,Inception,Christopher Nolan,2010,Action,148,8.8,87,74,160000000,829895144,Joseph Gordon-Levitt,Arthur
4,2,The Matrix,The Wachowskis,1999,Sci-Fi,136,8.7,87,73,63000000,463517383,Keanu Reeves,Neo
5,2,The Matrix,The Wachowskis,1999,Sci-Fi,136,8.7,87,73,63000000,463517383,Laurence Fishburne,Morpheus
6,2,The Matrix,The Wachowskis,1999,Action,136,8.7,87,73,63000000,463517383,Keanu Reeves,Neo
7,2,The Matrix,The Wachowskis,1999,Action,136,8.7,87,73,63000000,463517383,Laurence Fishburne,Morpheus

Mas esta forma de "serializar" os dados é a duplicação de valores, o que pode provocar erros nos dados. Vamos supor que queremos obter o total de receitas obtido por todos os filmes. Podemos usar a função `sum`, mas irá dar valores diferentes caso seja usada no DataFrame inicial ou no que foi criado pelos produtos cartesianos (`explode`), pois foram criadas novas linhas para o mesmo filme, adulterando dessa forma os valores obtidos:

In [57]:
movies['box_office.gross_worldwide'].sum()

np.int64(1293412527)

In [58]:
movies2['box_office.gross_worldwide'].sum()

np.int64(2586825054)

No caso dos dados deste ficheiro JSON uma melhor forma da proceder seria criar DataFrames separados para cada "lista", e isso pode ser feito diretamente com a função `json_normalize`.

Vamos ler (novamente) todos os dados do ficheiro para um DataFrame, que, como já foi visto, terá uma única coluna, correspondente ao objecto de primeiro nivel no JSON (`movies`), e tantas linhas quando os elementos exiostentes (dois no exemplo):

In [59]:
data = pd.read_json('exemplos/movies.json')
data

                                              movies
0  {'id': 1, 'title': 'Inception', 'director': 'C...
1  {'id': 2, 'title': 'The Matrix', 'director': '...

Vamos agora criar o primeiro DataFrame, que terá toda a informação relativa aos filmes, usando o `json_normalize`. Neste caso vamos usar o parametro `sep` para indicar o separador a utilizar no caso de dicionários, e vamos remover as listas existentes nos dados (`genre` e `cast`):

In [60]:
movies = pd.json_normalize(
                        data['movies'],
                        sep='_'
         ).drop(
            columns=['genre', 'cast']
         )
movies

,id,title,director,release_year,duration,ratings_IMDb,ratings_Rotten Tomatoes,ratings_Metacritic,box_office_budget,box_office_gross_worldwide
0,1,Inception,Christopher Nolan,2010,148,8.8,87,74,160000000,829895144
1,2,The Matrix,The Wachowskis,1999,136,8.7,87,73,63000000,463517383

Por uma questão de uniformização dos nomes das colunas, vamos renomear a coluna `ratings_Rotten Tomates`, e transformar tudo em minusculas:

In [61]:
movies.rename(
    columns={
        'ratings_Rotten Tomatoes': 'ratings_RottenTomatoes'
    },
    inplace=True
)
movies.columns = movies.columns.str.lower()
movies

,id,title,director,release_year,duration,ratings_imdb,ratings_rottentomatoes,ratings_metacritic,box_office_budget,box_office_gross_worldwide
0,1,Inception,Christopher Nolan,2010,148,8.8,87,74,160000000,829895144
1,2,The Matrix,The Wachowskis,1999,136,8.7,87,73,63000000,463517383

Desta forma temos os dados relativos aos filmes.

Vamos agora criar um DataFrame com os dados relativos aos tipos de filmes, constantes na lista `genre` do JSON.

Para isso vamos usar novamente a função `json_normalize`, as agora devemos usar o parametro `record_path`, que irá indicar onde começar a obter os dados na estrutura do JSON:

In [62]:
pd.json_normalize(
    data['movies'],
    record_path='genre',
)

        0
0  Sci-Fi
0  Action
1  Sci-Fi
1  Action

Como se pode ver, neste caso extrair apenas os dados relativos aos tipos, mas sem qualquer relação com os filmes (falta a "chave estrangeira"). O parametro `meta` permite adicionar campos que estejam "acima" do indicado em `record_path`, permitando criar as "chaves estrangeiras" para depois "ligar" com o DataFrame `movies`:

In [63]:
genres = pd.json_normalize(
                        data['movies'],
                        record_path='genre',
                        meta=['id'],
                        record_prefix='genre_'    # Adicionar prefixo às colunas
         )
genres

  genre_0 id
0  Sci-Fi  1
0  Action  1
1  Sci-Fi  2
1  Action  2

Aproveitamos para renomear a coluna `genre_0` para apenas `genre`:

In [64]:
genres.rename(columns={'genre_0': 'genre'}, inplace=True)
genres

    genre id
0  Sci-Fi  1
0  Action  1
1  Sci-Fi  2
1  Action  2

Vamos fazer um processo análogo para os atores:

In [65]:
cast = pd.json_normalize(
                    data['movies'],
                    record_path='cast',
                    meta=['id']
       )
cast

                  actor      role id
0     Leonardo DiCaprio      Cobb  1
0  Joseph Gordon-Levitt    Arthur  1
1          Keanu Reeves       Neo  2
1    Laurence Fishburne  Morpheus  2

Neste caso não foi necessário usar o `record_prefix` pois como o `cast` é uma lista de dicionários, as colunas do DataFrame serão as chaves dos dicionários.

Posteriormente, quando for necessário "juntar" os diferentes DataFrames pode-se usar o método `merge`, indicando quais as colunas que serão usadas como "chave":

In [66]:
movies.merge(genres, on='id').merge(cast, on='id')

,id,title,director,release_year,duration,ratings_imdb,ratings_rottentomatoes,ratings_metacritic,box_office_budget,box_office_gross_worldwide,genre,actor,role
0,1,Inception,Christopher Nolan,2010,148,8.8,87,74,160000000,829895144,Sci-Fi,Leonardo DiCaprio,Cobb
1,1,Inception,Christopher Nolan,2010,148,8.8,87,74,160000000,829895144,Sci-Fi,Joseph Gordon-Levitt,Arthur
2,1,Inception,Christopher Nolan,2010,148,8.8,87,74,160000000,829895144,Action,Leonardo DiCaprio,Cobb
3,1,Inception,Christopher Nolan,2010,148,8.8,87,74,160000000,829895144,Action,Joseph Gordon-Levitt,Arthur
4,2,The Matrix,The Wachowskis,1999,136,8.7,87,73,63000000,463517383,Sci-Fi,Keanu Reeves,Neo
5,2,The Matrix,The Wachowskis,1999,136,8.7,87,73,63000000,463517383,Sci-Fi,Laurence Fishburne,Morpheus
6,2,The Matrix,The Wachowskis,1999,136,8.7,87,73,63000000,463517383,Action,Keanu Reeves,Neo
7,2,The Matrix,The Wachowskis,1999,136,8.7,87,73,63000000,463517383,Action,Laurence Fishburne,Morpheus

Apesar de parecer igual à obtida anteriormente, este DataFrame é apenas de "visualização", e iremos usar cada DataFrame isoladamente ou "juntando-os", consoante necessário:

In [67]:
movies['box_office_gross_worldwide'].mean()

np.float64(646706263.5)

In [68]:
cast['actor'].count()

np.int64(4)

Pode-se facilmente perceber que apesar de documentos JSON serem uma forma da transferir informação, é preciso cuidado na sua leitura, pois não é um formato que seja uma tabela por defeito.

### O método `to_json(...)`

Para guardar um `DataFrame` para um ficheiro JSON, utiliza-se o método `to_json` indicando o nome do ficheiro que se pretende:

In [69]:
movies.to_json('filmes.json')

In [70]:
!type filmes.json

{"id":{"0":1,"1":2},"title":{"0":"Inception","1":"The Matrix"},"director":{"0":"Christopher Nolan","1":"The Wachowskis"},"release_year":{"0":2010,"1":1999},"duration":{"0":148,"1":136},"ratings_imdb":{"0":8.8,"1":8.7},"ratings_rottentomatoes":{"0":87,"1":87},"ratings_metacritic":{"0":74,"1":73},"box_office_budget":{"0":160000000,"1":63000000},"box_office_gross_worldwide":{"0":829895144,"1":463517383}}

In [71]:
movies.to_json('filmes.json', indent=4)

In [72]:
!type filmes.json

{
    "id":{
        "0":1,
        "1":2
    },
    "title":{
        "0":"Inception",
        "1":"The Matrix"
    },
    "director":{
        "0":"Christopher Nolan",
        "1":"The Wachowskis"
    },
    "release_year":{
        "0":2010,
        "1":1999
    },
    "duration":{
        "0":148,
        "1":136
    },
    "ratings_imdb":{
        "0":8.8,
        "1":8.7
    },
    "ratings_rottentomatoes":{
        "0":87,
        "1":87
    },
    "ratings_metacritic":{
        "0":74,
        "1":73
    },
    "box_office_budget":{
        "0":160000000,
        "1":63000000
    },
    "box_office_gross_worldwide":{
        "0":829895144,
        "1":463517383
    }
}

In [73]:
movies.to_json('filmes.json', indent=4, orient='records')

In [74]:
!type filmes.json

[
    {
        "id":1,
        "title":"Inception",
        "director":"Christopher Nolan",
        "release_year":2010,
        "duration":148,
        "ratings_imdb":8.8,
        "ratings_rottentomatoes":87,
        "ratings_metacritic":74,
        "box_office_budget":160000000,
        "box_office_gross_worldwide":829895144
    },
    {
        "id":2,
        "title":"The Matrix",
        "director":"The Wachowskis",
        "release_year":1999,
        "duration":136,
        "ratings_imdb":8.7,
        "ratings_rottentomatoes":87,
        "ratings_metacritic":73,
        "box_office_budget":63000000,
        "box_office_gross_worldwide":463517383
    }
]

## _Web Scraping_

Outra forma de obter valores é através de _web scraping_, que consiste em ler páginas diretamente da _web_ e processar o seu conteúdo.

O pandas tem a função `read_html` que internamente utiliza as livrarias `lxml`, `BeautifulSoup4` e `html5lib`, e devolve uma lista de `DataFrame`, com todas as tabelas, definidas pelas _tags_ `<table>...</table>`, existentes na página web.

Para garantir o correto funcionamento desta função, é necessário instalar essas livrarias através do `conda`:

```bash
> conda install lxml beautifulsoup4 html5lib
```

ou do `pip`:

```bash
> pip install lxml beautifulsoup4 html5lib
```

### A função `read_html(...)`

Vamos então utilizar a função read_html para ler uma página da web (https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/) e ver as tabelas existentes:

In [75]:
#URL = 'https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue'
URL = 'https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/'
tables = pd.read_html(URL)
type(tables)

list

In [76]:
len(tables)

1

Apesar de apenas existir uma tabela nessa página, o função `read_html` devolve uma lista de `DataFrame`. Para aceder ao mesmo é necessário indicar o elemento pretendido:

In [77]:
tables[0].head()

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Tioga-Franklin Savings Bank,Philadelphia,Pennsylvania,33802,Second Federal Savings and Loan Association of...,"August 21, 2026",10554
1,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
2,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
3,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
4,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550

No entanto, por vezes nem todas as tabelas tem dados úteis, e podemos filtrar as tabelas obtidas utilizando atributos HTML:

In [78]:
# data = pd.read_html(
#     'https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue',
#     attrs={'class': 'wikitable'}
# )

In [79]:
data = pd.read_html(URL, attrs={'class': 'usa-table'})
len(data)

1

In [80]:
data[0].head()

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Tioga-Franklin Savings Bank,Philadelphia,Pennsylvania,33802,Second Federal Savings and Loan Association of...,"August 21, 2026",10554
1,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
2,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
3,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
4,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550

Como os dados já estão num `DataFrame`, podemos utilizar todas as funções e métodos aplicáveis:

In [81]:
data[0].info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Bank Name              25 non-null     str
 1   City                   25 non-null     str
 2   State                  25 non-null     str
 3   Cert                   25 non-null     int64
 4   Acquiring Institution  25 non-null     str
 5   Closing Date           25 non-null     str
 6   Fund  Sort ascending   25 non-null     int64
dtypes: int64(2), str(5)
memory usage: 1.5 KB

In [82]:
data[0]['Fund  Sort ascending'].mean()

np.float64(10540.96)

### Utilizando o módulo `requests`

Atualmente muitos sites apenas permitem aceder à páginas utilizando um _browser_, não permitem aceder diretamente através de código, pelo que não podemos utilizar a função `read_html` para aceder a essas páginas (por exemplo, neste momento a função `read_html` não se consegue ler páginas da Wikipedia).

Para resolver este problema podemos utilizar o módulo `requests` para efetuar a leitura da página HTML, passando o `User-Agent` a utilizar e passar o conteúdo lido para a função `read_html`.

In [83]:
from io import StringIO
import requests

URL = 'https://en.wikipedia.org/wiki/National_Basketball_Association'
headers = {'User-Agent': 'Mozilla/5.0'}

response = requests.get(URL, headers=headers)
response.status_code

200

In [84]:
tables = pd.read_html(StringIO(response.text))

print(f'A página tem {len(tables)} tabelas definidas pelo HTML <table>...')

A página tem 44 tabelas definidas pelo HTML <table>...

In [85]:
tables = pd.read_html(StringIO(response.text), attrs={'class': 'wikitable'})

print(f'Mas apenas {len(tables)} tabelas "reais" com dados.')

Mas apenas 2 tabelas "reais" com dados.

In [86]:
tables[1].head()

,Teams,Win,Loss,Total,Year(s) won,Year(s) runner-up
0,Boston Celtics,18,5,23,"1957, 1959, 1960, 1961, 1962, 1963, 1964, 1965...","1958, 1985, 1987, 2010, 2022"
1,Minneapolis/Los Angeles Lakers,17,15,32,"1949, 1950, 1952, 1953, 1954, 1972, 1980, 1982...","1959, 1962, 1963, 1965, 1966, 1968, 1969, 1970..."
2,Philadelphia/San Francisco/Golden State Warriors,7,5,12,"1947, 1956, 1975, 2015, 2017, 2018, 2022","1948, 1964, 1967, 2016, 2019"
3,Chicago Bulls,6,0,6,"1991, 1992, 1993, 1996, 1997, 1998",—
4,San Antonio Spurs,5,2,7,"1999, 2003, 2005, 2007, 2014","2013, 2026"

## Aceder diretamente a APIs

Atualmente muitos _sites_ web disponibilizam uma API (_Application Programming Interface_) que permite aceder à sua informação, disponibilizada em formado JSON ou noutro formato qualquer.

Para aceder a uma API de um _site_ web, a forma mais fácil é utilizando a livraria `requests`, que pode ser instalada utilizando o `conda`:

```bash
> conda install requests
```

ou o `pip`:

```bash
> pip install requests
```

Vamos exemplificar acedendo a um conjunto de memes do site `imgflip.com`. Primeiro vamos carregar o módulo `requests` e aceder à entrada pretendida da API, através dos métodos `get` ou `post`, dependendo da documentação da API.

In [87]:
import requests

In [88]:
response = requests.get('https://api.imgflip.com/get_memes')

if response.status_code != 200:
    print("Erro no acesso à API!")

É sempre aconselhável verificar a resposta obtida, através do propriedade `status_code` ou `ok`, ou do método `raise_for_status` (que vai provocar uma exceção deliberada), pois pode ter acontecido um erro na leitura. Por exemplo, caso se tente aceder a uma entrada da API que não existe, vai resultar num erro `404` (página não existe).

In [89]:
er = requests.get('https://api.imgflip.com/naoexiste')

if er.status_code != 200:
    print("Erro no acesso à API!")

Erro no acesso à API!

Caso a leitura tenha sido feita corretamente, pode-se então aceder à informação obtida no objecto [`requests.Response`](https://requests.readthedocs.io/en/latest/api/#requests.Response). Na propriedade `text` está todo texto da resposta obtida, cujo processamento, dependendo do formato, pode ser mais ou menos "complicado", e cabe a cada um "resolver" esse problema, consoante o seu objectivo.

In [90]:
# Mostra apenas os primeiros 500 caracteres
print(response.text[:500])

{"success":true,"data":{"memes":[{"id":"181913649","name":"Drake Hotline Bling","url":"https://i.imgflip.com/30b1gx.jpg","width":1200,"height":1200,"box_count":2,"captions":1562750},{"id":"87743020","name":"Two Buttons","url":"https://i.imgflip.com/1g8my4.jpg","width":600,"height":908,"box_count":3,"captions":1213750},{"id":"112126428","name":"Distracted Boyfriend","url":"https://i.imgflip.com/1ur9b0.jpg","width":1200,"height":800,"box_count":3,"captions":1191500},{"id":"222403160","name":"Berni

No caso da API que se está a utilizar, a resposta é um documento no formato JSON, pelo que podemos desserializar o mesmo através do método `json`, transformando-o no dicionário de Python:

In [91]:
data = response.json()
# Mostra apenas os primeiros 500 caracteres
print(json.dumps(data, indent=2)[:500])

{
  "success": true,
  "data": {
    "memes": [
      {
        "id": "181913649",
        "name": "Drake Hotline Bling",
        "url": "https://i.imgflip.com/30b1gx.jpg",
        "width": 1200,
        "height": 1200,
        "box_count": 2,
        "captions": 1562750
      },
      {
        "id": "87743020",
        "name": "Two Buttons",
        "url": "https://i.imgflip.com/1g8my4.jpg",
        "width": 600,
        "height": 908,
        "box_count": 3,
        "captions": 1213750

Os dados que se pretende estão a partir da chave `memes`, pelo que podemos criar o `DataFrame` a partir desta chave:

In [92]:
memes = pd.DataFrame(data['data']['memes'])
memes.head()

,id,name,url,width,height,box_count,captions
0,181913649,Drake Hotline Bling,https://i.imgflip.com/30b1gx.jpg,1200,1200,2,1562750
1,87743020,Two Buttons,https://i.imgflip.com/1g8my4.jpg,600,908,3,1213750
2,112126428,Distracted Boyfriend,https://i.imgflip.com/1ur9b0.jpg,1200,800,3,1191500
3,222403160,Bernie I Am Once Again Asking For Your Support,https://i.imgflip.com/3oevdk.jpg,750,750,2,352000
4,217743513,UNO Draw 25 Cards,https://i.imgflip.com/3lmzyx.jpg,500,494,2,662000

A partir daqui já temos os dados num `DataFrame`, pelo que já podemos trabalhar os dados de forma pretendida.

Vamos, apenas como exemplo, apresentar os primeiros 10 memes. Para isso vamos criar uma lista com os primeiros 10 URLs do `DataFrame`:

In [93]:
images = memes['url'].head(9).tolist()
images

['https://i.imgflip.com/30b1gx.jpg',
 'https://i.imgflip.com/1g8my4.jpg',
 'https://i.imgflip.com/1ur9b0.jpg',
 'https://i.imgflip.com/3oevdk.jpg',
 'https://i.imgflip.com/3lmzyx.jpg',
 'https://i.imgflip.com/22bdq6.jpg',
 'https://i.imgflip.com/46e43q.png',
 'https://i.imgflip.com/5c7lwq.png',
 'https://i.imgflip.com/28j0te.jpg']

E vamos utilizar a livraria `IPython` (livraria que serve de base ao Jupyter e à utilização de forma iterativa do Python), para apresentar um código HTML:

In [94]:
from IPython.display import HTML

images_list = []
for url in images:
    images_list.append(f'<img src="{url}" style="display:inline-block; margin-right: 10px;" width="200">')

images_html = ''.join(images_list)
HTML(images_html)

A construção do código HTML podia ter sido feito de forma "mais simples" através de uma _list comprehension_:

In [95]:
from IPython.display import HTML

images_html = ''.join(f'<img src="{url}" style="display:inline-block; margin-right: 10px;" width="200">' for url in images)

HTML(images_html)

## Bases de Dados

No mundo dos negócios, os dados podem não estar armazenados em ficheiros CSV, JSON ou Excel, mas provavelmente estão num SGBD (Sistema de Gestão de Base de Dados) relacional (SQL Server, MySQL, PostgreSQL, etc.) ou não relacional NoSQL (MongoDB, Redis, Neo4J, etc.).

Dependendo do SGBD utilizado, assim teremos de utilizar um módulo para aceder à base de dados utilizando o Python.

| SGBD        | Módulo de Python                        |
|---------------------|-------------------------------------------|
| SQLite              | `sqlite3`                                 |
| MySQL/MariaDB       | `PyMySQL`    |
| PostgreSQL          | `psycopg2`                                |
| SQL Server          | `pyodbc`                                  |
| Oracle              | `cx_Oracle`                               |
| Firebird            | `firebird-driver`                                     |

### O módulo `SQLite3`

Vamos ilustrar como se pode ler os dados de uma base de dados para um `DataFrame` utilizando o [SQLite](https://sqlite.org), que é um SGDB que não tem utiliza nenhum servidor, mas trabalha diretamente com um ficheiro "normal".

Considere o ficheiro `exemplos\cidades.db`, que contem uma base de dados `SQLite` com uma tabela de nome `cidades` , com a seguinte estrutura:

| Campo         | Tipo    | Descrição                                 |
|---------------|---------|-------------------------------------------|
| `id`          | INTEGER | Chave primária com auto-incremento        |
| `nome_cidade` | TEXT    | Nome da cidade                            |
| `distrito`    | TEXT    | Distrito onde a cidade está localizada    |
| `populacao`   | INTEGER | População da cidade                       |
| `area`        | REAL    | Área da cidade (em quilômetros quadrados) |

Para efetuar a ligação ao `SQLite`, basta importar o módulo `sqlite3`, efetuar a "ligação" ao ficheiro com a função `connect`, e criar um cursor para servir de objecto base para executar os comandos SQL.

In [96]:
import sqlite3

conn = sqlite3.connect(r'exemplos\cidades.db')
cursor = conn.cursor()
cursor

Vamos agora efetuar um query a todos os campos da tabela `cidades` e obter todos os registos:

In [97]:
rows = cursor.execute('SELECT * FROM cidades')
data = rows.fetchall()
data

[(1, 'Lisboa', 'Lisboa', 545923, 100.05),
 (2, 'Porto', 'Porto', 231962, 41.42),
 (3, 'Vila Nova de Gaia', 'Porto', 188443, 56.22),
 (4, 'Amadora', 'Lisboa', 171179, 23.79),
 (5, 'Braga', 'Braga', 148977, 362.0),
 (6, 'Coimbra', 'Coimbra', 106768, 83.1),
 (7, 'Funchal', 'Madeira', 105701, 35.6),
 (8, 'Setúbal', 'Setúbal', 90396, 51.49),
 (9, 'Almada', 'Lisboa', 88202, 13.98),
 (10, 'Cacém', 'Lisboa', 81020, 10.42),
 (11, 'Aveiro', 'Aveiro', 62653, 41.84),
 (12, 'Evora', 'Evora', 46953, 14.3),
 (13, 'Leiria', 'Leiria', 55074, 34.6),
 (14, 'Faro', 'Faro', 41904, 8.34),
 (15, 'Viana do Castelo', 'Viana do Castelo', 25158, 11.86),
 (16, 'Ponta Delgada', 'Açores', 46897, 37.57),
 (17, 'Guimarães', 'Braga', 54178, 20.4),
 (18, 'Bragança', 'Bragança', 24041, 15.4),
 (19, 'Vila Real', 'Vila Real', 29201, 22.0),
 (20, 'Caldas da Rainha', 'Leiria', 30443, 59.2),
 (21, 'Olhão', 'Faro', 29556, 6.46),
 (22, 'Santarém', 'Santarém', 30021, 55.46),
 (23, 'Viseu', 'Viseu', 59469, 64.85)]

Nunca esquecer de terminar a coneção à base de dados.

In [98]:
conn.close()

Pode-se ver que temos os registos, mas não temos os nomes dos campos da base de dados, necessários para criar o `DataFrame`. Para isso é necessário aceder à propriedade `description` do cursor do `SQLite`:

In [99]:
cursor.description

(('id', None, None, None, None, None, None),
 ('nome_cidade', None, None, None, None, None, None),
 ('distrito', None, None, None, None, None, None),
 ('populacao', None, None, None, None, None, None),
 ('area', None, None, None, None, None, None))

Pode-se ver que o nome dos campos é o primeiro elemento de cada tuplo, pelo que podemos criar uma lista com esses nomes:

In [100]:
column_names = [column[0] for column in cursor.description]
column_names

['id', 'nome_cidade', 'distrito', 'populacao', 'area']

Finalmente vamos criar um `DataFrame` para guardar os registos lidos da base de dados:

In [101]:
cidades = pd.DataFrame(data, columns=column_names).set_index('id')
cidades.head()

          nome_cidade distrito  populacao    area
id
1              Lisboa   Lisboa     545923  100.05
2               Porto    Porto     231962   41.42
3   Vila Nova de Gaia    Porto     188443   56.22
4             Amadora   Lisboa     171179   23.79
5               Braga    Braga     148977  362.00

Dependendo do SGBD utilizado, o código pode tornar-se mais ou menos complicado, e caso se pretenda alterar o SGBD a meio do projeto, ainda pode ser mais complicado.

### A função `read_sql(...)`

A assinatura da função `read_sql` é a seguinte:

`pandas.read_sql(sql, con, ...)`

onde:

- `sql` - é uma string com o código SQL a executar
- `con` - é um objecto com a coneção à Base de Dados (apenas alguns tipos de coneções são suportadas)

Vamos exemplificar com uma base da dados do SQLite:

In [102]:
import sqlite3

conn = sqlite3.connect(r'exemplos\cidades.db')

cidades = pd.read_sql('SELECT * FROM cidades', conn)
cidades.head()

   id        nome_cidade distrito  populacao    area
0   1             Lisboa   Lisboa     545923  100.05
1   2              Porto    Porto     231962   41.42
2   3  Vila Nova de Gaia    Porto     188443   56.22
3   4            Amadora   Lisboa     171179   23.79
4   5              Braga    Braga     148977  362.00

Para tornar o código agnóstico à base de dados utilizada, foram desenvolvidos algumas livrarias `ORM` (_Object Relational Mapper_) que servem camada de abstração entre o código e o servidor de base de dados, sendo o mais conhecido e utilizado o [SQLAlchemy](https://www.sqlalchemy.org/), que é utilizado por defeito pelo pandas na sua função `read_sql`, pelo que é necessário instalar este módulo previamente a utilizar esta função, através do `conda`:

```bash
> conda install sqlalchemy
```

ou utilizando o `pip`:

```bash
> pip install sqlalchemy
```

Note-se que apesar da utilização do SQLAlchemy servir de camada de abstração **do código**, as livrarias para aceder a cada um dos SGDB devem estar instalados, caso contrário irá ocorrer um erro quando se utilizar esse SGBD.

Depois, utilizando o SQLAlchemy, vamos criar um _engine_ para ligar à base de dados pretendida:

In [130]:
import sqlalchemy as sqla

engine = sqla.create_engine('sqlite:///exemplos/cidades.db')

Depois podemos utilizar a função `read_sql`, passando a _query_ prentendida (em SQL) e a ligação à base de dados definida acima:

In [131]:
cidades = pd.read_sql('SELECT * FROM cidades', conn).sort_values(by=['distrito', 'nome_cidade'])
cidades.head()

    id    nome_cidade  distrito  populacao    area
10  11         Aveiro    Aveiro      62653   41.84
15  16  Ponta Delgada    Açores      46897   37.57
4    5          Braga     Braga     148977  362.00
16  17      Guimarães     Braga      54178   20.40
17  18       Bragança  Bragança      24041   15.40

In [132]:
pd.read_sql('SELECT * FROM cidades ORDER BY distrito, nome_cidade', conn).head()

   id    nome_cidade  distrito  populacao    area
0  11         Aveiro    Aveiro      62653   41.84
1  16  Ponta Delgada    Açores      46897   37.57
2   5          Braga     Braga     148977  362.00
3  17      Guimarães     Braga      54178   20.40
4  18       Bragança  Bragança      24041   15.40

Pode-se também executar _queries_ parametrizados, definindo o comando SQL, e passando um dicionário com os valores para as chaves utilizadas no SQL:

In [133]:
sql = '''
SELECT nome_cidade AS cidade, 
       populacao AS população,
       area AS área
    FROM cidades
    WHERE populacao > :pop AND area < :area
'''

params = {'pop': 100000, 'area': 50}

grande_densidade = pd.read_sql(sql, engine, params=params)
grande_densidade

    cidade  população   área
0    Porto     231962  41.42
1  Amadora     171179  23.79
2  Funchal     105701  35.60

Muitas vezes não vamos usar o SQLite, mas um servidor com autenticação. No SQLAlchemy isso pode ser feito indicando uma string de coneção com o seguinte formato:

`dialeto+driver://utilizador:palavra-passe@servidor:porta/base_de_dados`

onde o `dialeto` é o tipo de SGBD, e `driver` o modulo que irá ser usado para aceder ao SGBD. Ver a [documentação
do SQLAlchemy](https://docs.sqlalchemy.org/en/20/dialects/index.html) para as diferentes hipóteses de `dialeto+driver`.

Vamos exemplificar acedendo ao servidor **CTU Relational Learning Repository**, da Czech Technical University, usando o driver/módulo `PyMySQL`, que deve ser instalado previamente.

In [148]:
host = 'relational.fel.cvut.cz'
user = 'guest'
passwd = 'ctu-relational'
port = 3306
database = 'employee'

ctu = sqla.create_engine(f'mysql+pymysql://{user}:{passwd}@{host}:{port}/{database}')

In [149]:
pd.read_sql("SHOW TABLES", ctu)

  Tables_in_employee
0        departments
1           dept_emp
2       dept_manager
3          employees
4           salaries
5             titles

A função `read_sql` permite ler toda uma tabela de uma forma fácil, sem ser necessário escrever `SELECT * FROM <tabela>`, bastando indicar o nome da tabela:

In [150]:
emp = pd.read_sql('employees', ctu)
emp.head()

   emp_no birth_date first_name last_name gender  hire_date
0   10001 1953-09-02     Georgi   Facello      M 1986-06-26
1   10002 1964-06-02    Bezalel    Simmel      F 1985-11-21
2   10003 1959-12-03      Parto   Bamford      M 1986-08-28
3   10004 1954-05-01  Chirstian   Koblick      M 1986-12-01
4   10005 1955-01-21    Kyoichi  Maliniak      M 1989-09-12

No final deve-se sempre terminar a ligação aos servidores, sejam eles remotos ou locais, com o método `dispose()`:

In [151]:
ctu.dispose()

### O método `to_sql(...)`

Da mesma forma dos restantes tipos de ficheiros, também se pode guardar um `DataFrame` numa tabela da base de dados utilizando o método `to_sql`, passando o nome da tabela onde se vai guardar o `DataFrame` e a ligação à mesma.

In [144]:
grande_densidade.to_sql('teste.db', engine, if_exists='replace')

3

Caso a tabela já exista, vai ocorrer um erro, a não ser que se utilize o parâmetro `if_exists` que pode ser `fail` (valor por defeito), `replace` (faz o _drop_ da tabela antes de inserir os novos valores), `append` (que insere os dados na tabela existente), ou `delete_rows` (remove todos os registos da tabela antes de inserir os novos).

In [145]:
grande_densidade.to_sql('teste.db', engine, if_exists='append')

3

In [146]:
pd.read_sql('teste.db', engine)

   index   cidade  população   área
0      0    Porto     231962  41.42
1      1  Amadora     171179  23.79
2      2  Funchal     105701  35.60
3      0    Porto     231962  41.42
4      1  Amadora     171179  23.79
5      2  Funchal     105701  35.60

**Nunca** esquecer que é necessário fechar a ligação à base de dados:

In [147]:
engine.dispose()