# Exercícios

## Exercício 1

Leia o arquivo `exercicios\vendas.csv` e apresente as primeiras 5 linhas do `DataFrame`.

In [1]:
import pandas as pd
import csv

pd.options.display.max_columns = 999

In [2]:
df1 = pd.read_csv(r'exercicios\vendas.csv')

df1.head(5)

         data  produto  quantidade  valor_unitario
0  2023-01-01   Laptop           3          1200.0
1  2023-01-02    Mouse          10            25.0
2  2023-01-03  Teclado           5            50.0
3  2023-01-04  Monitor           2           300.0
4  2023-01-05  Headset           8            75.0

## Exercicio 2

Crie um `DataFrame` com informações de 5 livros (título, autor, ano) e guarde esse `DataFrame` num ficheiro CSV chamado `exercicios\livros.csv`. No ficheiro a coluna de índice deve ter o nome `id`.

In [3]:
import pandas as pd

data1 = {
    'titulo': ['Ensaio sobre a Cegueira', 'A Sombra do Vento', 'The Vegan', 'Hunger Games', 'Sobre os Ossos dos Mortos'],
    'autor': ['José Saramago',  'Carlos Ruiz Zafón', 'Han Kang', 'Suzanne Collins', 'Olga Tokarczuk'],
    'ano': [1995, 2001, 2007, 2008, 2009] }


df2 = pd.DataFrame(data1)

df2.to_excel('exercicios/livros.xlsx')

## Exercício 3

Leia o ficheiro `exercicios\temperatura.csv` que usa ponto e vírgula como separador, tem cabeçalho na segunda linha e usa vírgula como separador decimal.

In [4]:
import pandas as pd

pd.read_csv(r'exercicios\temperaturas.csv',
            header = 1,     # Cabeçalho na segunda linha
            sep =';',       # separador
            decimal=','    # Separador decimal
            )

           Data  Temperatura (°C)  Humidade (%)  Pressão (hPa)
0    2023-01-01              25.5            56         1004.6
1    2023-01-02              27.2            57         1002.6
2    2023-01-03              26.0            68         1001.1
3    2023-01-04              25.4            78         1014.5
4    2023-01-05              24.2            61         1000.2
..          ...               ...           ...            ...
195  2023-07-15              24.9            61         1006.2
196  2023-07-16              22.3            70         1007.5
197  2023-07-17              22.5            56         1010.5
198  2023-07-18              20.6            59         1015.0
199  2023-07-19              24.3            78         1006.7

[200 rows x 4 columns]

## Exercicio 4

Leia o ficheiro `exercicios\funcionarios.json` e calcule a média do salário dos funcionários.

In [5]:
# .mean()

import json
import pandas as pd

with open(r'exercicios\funcionarios.json') as file4:
    data4 = json.load(file4)

df4 = pd.DataFrame(data4)

df4['salario'].mean()

np.float64(1486.0)

## Exercicio 5

Crie um `DataFrame` com informações de 3 cidades (nome, população, área) e guarde-o num ficheiro JSON chamado `exercicios\cidades.json`.

In [6]:
import pandas as pd
import json

data5 = {
    'nome':['Lisboa','Porto','Coimbra'],
    'populacao': [545796, 231962, 140796],
    'area': [100.05, 41.42, 319.40],
}

df5 = pd.DataFrame(data5)

df5.to_json('exercicios/cidades.json')

## Exercício 6

No ficheiro `exercicios\escola.db` está uma base de dados do SQLite. Os dados estão na tabela `alunos`.

1. Leia os dados do ficheiro para um DataFrame e apresente a lista de todos os alunos do curso de Medicina.
2. Crie um DataFrame com os alunos de cada curso (um DataFrame por curso), e guarde cada um deles numa tabela da base de dados com o nome do curso.

In [7]:
# 6.1

import pandas as pd
import sqlite3

con = sqlite3.connect(r'exercicios\escola.db')

df6_medicina = pd.read_sql('SELECT * FROM medicina ', con)

df6_medicina

      Curso
0  Medicina
1  Medicina
2  Medicina
3  Medicina
4  Medicina
5  Medicina
6  Medicina
7  Medicina
8  Medicina
9  Medicina

In [9]:
# 6.2

df6_total = pd.read_sql('SELECT Curso from Alunos', con)

df6_cursos = df6_total['Curso'].unique()

df6_cursos

for curso in df6_cursos:
    df_curso = df6_total[df6_total['Curso'] == curso]
    nome_tabela = curso.lower().replace (' ', '_')
    df_curso.to_sql(nome_tabela, con, if_exists='replace', index = False)

## Exercício 7

Utilizando o SQLAlchemy, conecte-se à base de dados MySQL pública `world` da [Universidade Técnica da Republica Checa](https://relational.fel.cvut.cz/)), utilizando os seguintes parâmetros:

- Host: `relational.fel.cvut.cz`
- Database: `world`
- User: `guest`
- Password: `ctu-relational`
- Port: `3306`

1. Leia tabela `Country` para um DataFrame
2. Calcule o total que população que vive nos países do sul da Europa (`Southern Europe`), e o total da área desses paises.

In [ ]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

host = "relational.fel.cvut.cz"
database = "world"
user = "guest"
password = "ctu-relational"
port = 3306

url = URL.create(
    drivername="mysql+pymysql",
    username=user,
    password = password,
    host = host,
    port = port,
    database = database,
)

engine = create_engine(url)

df7 = pd.read_sql("SELECT * FROM Country", engine)

df7_soueur = df7[df7['Region'] == 'Southern Europe']

df7_soueur

total_pop = df7_soueur['Population'].sum()
total_area = df7_soueur['SurfaceArea'].sum()

print(total_area, total_pop)

1316392.4 144674200

## Exercício 8

Use o pandas para ler a página da Wikipedia com a população de cada país ([https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population](https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population))
e crie um DataFrame com essa informação, efetuando uma limpeza muito simples (removendo as linhas/colunas que não façam sentido).

In [50]:
import pandas as pd
import requests
from io import StringIO


url = "https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population"

resposta = requests.get(url, headers={"User-Agent": "Mozzila/5.0"})
tabelas8 = pd.read_html(StringIO(resposta.text))

df8 = tabelas8[0]

df8 = df8.drop(columns =['Notes','% of world', 'Date', 'Source (official or from the United Nations)'])

df8

                                Location    Population
0                                  World  8.232000e+09
1                                  India  1.429404e+09
2                                  China  1.404890e+09
3                          United States  3.417849e+08
4                              Indonesia  2.883151e+08
..                                   ...           ...
236         Christmas Island (Australia)  1.692000e+03
237                   Niue (New Zealand)  1.681000e+03
238                         Vatican City  8.820000e+02
239  Cocos (Keeling) Islands (Australia)  5.930000e+02
240                Pitcairn Islands (UK)  3.500000e+01

[241 rows x 2 columns]

## Exercicio 9

Use a API do [countries.dev](https://countries.dev/docs) para obter informações sobre países que têm o português como língua oficial.

Crie um DataFrame com as seguintes informações: nome do país, capital, população, área e idioma(s) oficiais.

In [ ]:
import requests
import pandas as pd

resposta9 = requests.get('https://countries.dev/lang/pt')

# Ver estrutura de resposta
print(resposta9.json())

# Transformar a reposta para formato json e uma variavel que vou usar para o df
dados9 = resposta9.json()

# Filtrar json pelas colunas que quero
df9 = pd.json_normalize(dados9)[['name', 'capital','population', 'area', 'languages']]

# Limpar os campos das linguas
df9['languages'] = df9['languages'].apply(lambda lista: ', '.join(l['name'] for l in lista))

df9

[{'area': 1246700, 'cioc': 'ANG', 'flag': '🇦🇴', 'gini': 51.3, 'name': 'Angola', 'flags': {'png': 'https://flagcdn.com/w320/ao.png', 'svg': 'https://flagcdn.com/ao.svg'}, 'latlng': [-12.5, 18.5], 'region': 'Africa', 'borders': ['COG', 'COD', 'ZMB', 'NAM'], 'capital': 'Luanda', 'demonym': 'Angolan', 'languages': [{'name': 'Portuguese', 'iso639_1': 'pt', 'iso639_2': 'por', 'nativeName': 'Português'}], 'subregion': 'Middle Africa', 'timezones': ['UTC+01:00'], 'alpha2Code': 'AO', 'alpha3Code': 'AGO', 'currencies': [{'code': 'AOA', 'name': 'Angolan kwanza', 'symbol': 'Kz'}], 'nativeName': 'Angola', 'population': 32866268, 'independent': True, 'numericCode': '024', 'callingCodes': ['244'], 'topLevelDomain': ['.ao'], 'populationDensity': 26.36}, {'area': 8515767, 'cioc': 'BRA', 'flag': '🇧🇷', 'gini': 53.4, 'name': 'Brazil', 'flags': {'png': 'https://flagcdn.com/w320/br.png', 'svg': 'https://flagcdn.com/br.svg'}, 'latlng': [-10, -55], 'region': 'Americas', 'borders': ['ARG', 'BOL', 'COL', 'FRA', 'GUF', 'GUY', 'PRY', 'PER', 'SUR', 'URY', 'VEN'], 'capital': 'Brasília', 'demonym': 'Brazilian', 'languages': [{'name': 'Portuguese', 'iso639_1': 'pt', 'iso639_2': 'por', 'nativeName': 'Português'}], 'subregion': 'South America', 'timezones': ['UTC-05:00', 'UTC-04:00', 'UTC-03:00', 'UTC-02:00'], 'alpha2Code': 'BR', 'alpha3Code': 'BRA', 'currencies': [{'code': 'BRL', 'name': 'Brazilian real', 'symbol': 'R$'}], 'nativeName': 'Brasil', 'population': 212559409, 'independent': True, 'numericCode': '076', 'callingCodes': ['55'], 'topLevelDomain': ['.br'], 'populationDensity': 24.96}, {'area': 4033, 'cioc': 'CPV', 'flag': '🇨🇻', 'gini': 42.4, 'name': 'Cabo Verde', 'flags': {'png': 'https://flagcdn.com/w320/cv.png', 'svg': 'https://flagcdn.com/cv.svg'}, 'latlng': [16, -24], 'region': 'Africa', 'capital': 'Praia', 'demonym': 'Cape Verdian', 'languages': [{'name': 'Portuguese', 'iso639_1': 'pt', 'iso639_2': 'por', 'nativeName': 'Português'}], 'subregion': 'Western Africa', 'timezones': ['UTC-01:00'], 'alpha2Code': 'CV', 'alpha3Code': 'CPV', 'currencies': [{'code': 'CVE', 'name': 'Cape Verdean escudo', 'symbol': 'Esc'}], 'nativeName': 'Cabo Verde', 'population': 555988, 'independent': True, 'numericCode': '132', 'callingCodes': ['238'], 'topLevelDomain': ['.cv'], 'populationDensity': 137.86}, {'area': 28051, 'cioc': 'GEQ', 'flag': '🇬🇶', 'name': 'Equatorial Guinea', 'flags': {'png': 'https://flagcdn.com/w320/gq.png', 'svg': 'https://flagcdn.com/gq.svg'}, 'latlng': [2, 10], 'region': 'Africa', 'borders': ['CMR', 'GAB'], 'capital': 'Malabo', 'demonym': 'Equatorial Guinean', 'languages': [{'name': 'Spanish', 'iso639_1': 'es', 'iso639_2': 'spa', 'nativeName': 'Español'}, {'name': 'French', 'iso639_1': 'fr', 'iso639_2': 'fra', 'nativeName': 'français'}, {'name': 'Portuguese', 'iso639_1': 'pt', 'iso639_2': 'por', 'nativeName': 'Português'}, {'name': 'Fang', 'iso639_2': 'fan', 'nativeName': 'Fang'}], 'subregion': 'Middle Africa', 'timezones': ['UTC+01:00'], 'alpha2Code': 'GQ', 'alpha3Code': 'GNQ', 'currencies': [{'code': 'XAF', 'name': 'Central African CFA franc', 'symbol': 'Fr'}], 'nativeName': 'Guinea Ecuatorial', 'population': 1402985, 'independent': True, 'numericCode': '226', 'callingCodes': ['240'], 'topLevelDomain': ['.gq'], 'populationDensity': 50.02}, {'area': 36125, 'cioc': 'GBS', 'flag': '🇬🇼', 'gini': 50.7, 'name': 'Guinea-Bissau', 'flags': {'png': 'https://flagcdn.com/w320/gw.png', 'svg': 'https://flagcdn.com/gw.svg'}, 'latlng': [12, -15], 'region': 'Africa', 'borders': ['GIN', 'SEN'], 'capital': 'Bissau', 'demonym': 'Guinea-Bissauan', 'languages': [{'name': 'Portuguese', 'iso639_1': 'pt', 'iso639_2': 'por', 'nativeName': 'Português'}], 'subregion': 'Western Africa', 'timezones': ['UTC'], 'alpha2Code': 'GW', 'alpha3Code': 'GNB', 'currencies': [{'code': 'XOF', 'name': 'West African CFA franc', 'symbol': 'Fr'}], 'nativeName': 'Guiné-Bissau', 'population': 1967998, 'independent': True, 'numericCode': '624', 'callingCodes': ['245'], 'topLevelDomain': ['.gw'], 'populationDensity': 54.48}, {'area': 30, 'flag': '🇲🇴', 'name': 'Macao', 'flags': {'png': 'https://flagcdn.com/w320/mo.png', 'svg': 'https://flagcdn.com/mo.svg'}, 'latlng': [22.16666666, 113.55], 'region': 'Asia', 'borders': ['CHN'], 'demonym': 'Chinese', 'languages': [{'name': 'Chinese', 'iso639_1': 'zh', 'iso639_2': 'zho', 'nativeName': '中文 (Zhōngwén)'}, {'name': 'Portuguese', 'iso639_1': 'pt', 'iso639_2': 'por', 'nativeName': 'Português'}], 'subregion': 'Eastern Asia', 'timezones': ['UTC+08:00'], 'alpha2Code': 'MO', 'alpha3Code': 'MAC', 'currencies': [{'code': 'MOP', 'name': 'Macanese pataca', 'symbol': 'P'}], 'nativeName': '澳門', 'population': 649342, 'independent': False, 'numericCode': '446', 'callingCodes': ['853'], 'topLevelDomain': ['.mo'], 'populationDensity': 21644.73}, {'area': 801590, 'cioc': 'MOZ', 'flag': '🇲🇿', 'gini': 54, 'name': 'Mozambique', 'flags': {'png': 'https://flagcdn.com/w320/mz.png', 'svg': 'https://flagcdn.com/mz.svg'}, 'latlng': [-18.25, 35], 'region': 'Africa', 'borders': ['MWI', 'ZAF', 'SWZ', 'TZA', 'ZMB', 'ZWE'], 'capital': 'Maputo', 'demonym': 'Mozambican', 'languages': [{'name': 'Portuguese', 'iso639_1': 'pt', 'iso639_2': 'por', 'nativeName': 'Português'}], 'subregion': 'Eastern Africa', 'timezones': ['UTC+02:00'], 'alpha2Code': 'MZ', 'alpha3Code': 'MOZ', 'currencies': [{'code': 'MZN', 'name': 'Mozambican metical', 'symbol': 'MT'}], 'nativeName': 'Moçambique', 'population': 31255435, 'independent': True, 'numericCode': '508', 'callingCodes': ['258'], 'topLevelDomain': ['.mz'], 'populationDensity': 38.99}, {'area': 92090, 'cioc': 'POR', 'flag': '🇵🇹', 'gini': 33.5, 'name': 'Portugal', 'flags': {'png': 'https://flagcdn.com/w320/pt.png', 'svg': 'https://flagcdn.com/pt.svg'}, 'latlng': [39.5, -8], 'region': 'Europe', 'borders': ['ESP'], 'capital': 'Lisbon', 'demonym': 'Portuguese', 'languages': [{'name': 'Portuguese', 'iso639_1': 'pt', 'iso639_2': 'por', 'nativeName': 'Português'}], 'subregion': 'Southern Europe', 'timezones': ['UTC-01:00', 'UTC'], 'alpha2Code': 'PT', 'alpha3Code': 'PRT', 'currencies': [{'code': 'EUR', 'name': 'Euro', 'symbol': '€'}], 'nativeName': 'Portugal', 'population': 10305564, 'independent': True, 'numericCode': '620', 'callingCodes': ['351'], 'topLevelDomain': ['.pt'], 'populationDensity': 111.91}, {'area': 964, 'cioc': 'STP', 'flag': '🇸🇹', 'gini': 56.3, 'name': 'Sao Tome and Principe', 'flags': {'png': 'https://flagcdn.com/w320/st.png', 'svg': 'https://flagcdn.com/st.svg'}, 'latlng': [1, 7], 'region': 'Africa', 'capital': 'São Tomé', 'demonym': 'Sao Tomean', 'languages': [{'name': 'Portuguese', 'iso639_1': 'pt', 'iso639_2': 'por', 'nativeName': 'Português'}], 'subregion': 'Middle Africa', 'timezones': ['UTC'], 'alpha2Code': 'ST', 'alpha3Code': 'STP', 'currencies': [{'code': 'STD', 'name': 'São Tomé and Príncipe dobra', 'symbol': 'Db'}], 'nativeName': 'São Tomé e Príncipe', 'population': 219161, 'independent': True, 'numericCode': '678', 'callingCodes': ['239'], 'topLevelDomain': ['.st'], 'populationDensity': 227.35}, {'area': 14874, 'cioc': 'TLS', 'flag': '🇹🇱', 'gini': 28.7, 'name': 'Timor-Leste', 'flags': {'png': 'https://flagcdn.com/w320/tl.png', 'svg': 'https://flagcdn.com/tl.svg'}, 'latlng': [-8.83333333, 125.91666666], 'region': 'Asia', 'borders': ['IDN'], 'capital': 'Dili', 'demonym': 'East Timorese', 'languages': [{'name': 'Portuguese', 'iso639_1': 'pt', 'iso639_2': 'por', 'nativeName': 'Português'}], 'subregion': 'South-Eastern Asia', 'timezones': ['UTC+09:00'], 'alpha2Code': 'TL', 'alpha3Code': 'TLS', 'currencies': [{'code': 'USD', 'name': 'United States Dollar', 'symbol': '$'}], 'nativeName': 'Timor-Leste', 'population': 1318442, 'independent': True, 'numericCode': '626', 'callingCodes': ['670'], 'topLevelDomain': ['.tl'], 'populationDensity': 88.64}]

,name,capital,population,area,languages
0,Angola,Luanda,32866268,1246700,Portuguese
1,Brazil,Brasília,212559409,8515767,Portuguese
2,Cabo Verde,Praia,555988,4033,Portuguese
3,Equatorial Guinea,Malabo,1402985,28051,"Spanish, French, Portuguese, Fang"
4,Guinea-Bissau,Bissau,1967998,36125,Portuguese
5,Macao,NaN,649342,30,"Chinese, Portuguese"
6,Mozambique,Maputo,31255435,801590,Portuguese
7,Portugal,Lisbon,10305564,92090,Portuguese
8,Sao Tome and Principe,São Tomé,219161,964,Portuguese
9,Timor-Leste,Dili,1318442,14874,Portuguese

## Exercício 10

Use a API do Open Library ([https://openlibrary.org/developers/api](https://openlibrary.org/developers/api)) para obter informações sobre os livros de um autor específico. Crie um DataFrame contendo o título do livro e o ano em que o livro foi publicado pela primeira vez. Pode usar "George Orwell" como exemplo de autor.

In [84]:
import pandas as pd
import requests

resposta10 = requests.get('https://openlibrary.org/search.json?author=george+orwell&sort=new')

print(resposta10.json())

{'numFound': 8076, 'start': 0, 'numFoundExact': True, 'num_found': 8076, 'documentation_url': 'https://openlibrary.org/dev/docs/api/search', 'q': '', 'offset': None, 'docs': [{'author_key': ['OL16029200A', 'OL6305694A'], 'author_name': ['George Orwell', 'Franco Fracassi'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2026, 'has_fulltext': False, 'key': '/works/OL45923788W', 'language': ['eng'], 'public_scan_b': False, 'title': 'Fattoria Degli Animali'}, {'author_key': ['OL16029200A', 'OL2938196A'], 'author_name': ['George Orwell', 'Kevin Theis'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2026, 'has_fulltext': False, 'key': '/works/OL46002345W', 'language': ['eng'], 'public_scan_b': False, 'title': 'Animal Farm - Unabridged'}, {'author_key': ['OL18319A'], 'author_name': ['Mark Twain'], 'ebook_access': 'no_ebook', 'edition_count': 2, 'first_publish_year': 2025, 'has_fulltext': False, 'key': '/works/OL42550137W', 'language': ['eng'], 'public_scan_b': False, 'title': 'Adventures of Tom Sawyer'}, {'author_key': ['OL18319A'], 'author_name': ['Mark Twain'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2025, 'has_fulltext': False, 'key': '/works/OL42441718W', 'language': ['eng'], 'public_scan_b': False, 'title': 'Adventures of Tom Sawyer and Huckleberry Finn'}, {'author_key': ['OL18319A'], 'author_name': ['Mark Twain'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2025, 'has_fulltext': False, 'key': '/works/OL42450517W', 'language': ['eng'], 'public_scan_b': False, 'title': 'Diary of Adam and Eve'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2025, 'has_fulltext': False, 'key': '/works/OL42416290W', 'language': ['eng'], 'public_scan_b': False, 'title': 'Can Socialists Be Happy?'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2025, 'has_fulltext': False, 'key': '/works/OL42540551W', 'language': ['eng'], 'public_scan_b': False, 'title': 'Literary and Political Essays'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2025, 'has_fulltext': False, 'key': '/works/OL44399901W', 'public_scan_b': False, 'subtitle': 'A fairy story', 'title': 'Animal Farm'}, {'author_key': ['OL16029200A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2025, 'has_fulltext': False, 'key': '/works/OL45151681W', 'language': ['eng'], 'public_scan_b': False, 'title': 'George Orwell 2-Book Boxed Set'}, {'author_key': ['OL18319A', 'OL7508141A'], 'author_name': ['Mark Twain', 'Stephen H. Provost'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2025, 'has_fulltext': False, 'key': '/works/OL44603724W', 'language': ['eng'], 'public_scan_b': False, 'title': 'Dark Twain'}, {'author_key': ['OL16029200A', 'OL14722600A'], 'author_name': ['George Orwell', 'Tranzlaty'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2025, 'has_fulltext': False, 'key': '/works/OL44602704W', 'language': ['rus'], 'public_scan_b': False, 'title': 'Скотный Двор / Farma Zvířat'}, {'author_key': ['OL16029200A', 'OL14722600A'], 'author_name': ['George Orwell', 'Tranzlaty'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2025, 'has_fulltext': False, 'key': '/works/OL44596930W', 'language': ['rus'], 'public_scan_b': False, 'title': 'Скотный Двор / Kammerat Napoleon'}, {'author_key': ['OL16029200A', 'OL14722600A'], 'author_name': ['George Orwell', 'Tranzlaty'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2025, 'has_fulltext': False, 'key': '/works/OL44602702W', 'language': ['rus'], 'public_scan_b': False, 'title': 'Скотный Двор / Zivotinjska Farma'}, {'author_key': ['OL16029200A', 'OL14722600A'], 'author_name': ['George Orwell', 'Tranzlaty'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2025, 'has_fulltext': False, 'key': '/works/OL44604569W', 'language': ['rus'], 'public_scan_b': False, 'title': 'Скотный Двор / Diereplaas'}, {'author_key': ['OL16029200A', 'OL14722600A'], 'author_name': ['George Orwell', 'Tranzlaty'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2025, 'has_fulltext': False, 'key': '/works/OL44600805W', 'language': ['rus'], 'public_scan_b': False, 'title': 'Скотный Двор / Dierenboerderij'}, {'author_key': ['OL16029200A', 'OL14722600A'], 'author_name': ['George Orwell', 'Tranzlaty'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2025, 'has_fulltext': False, 'key': '/works/OL44590012W', 'language': ['rus'], 'public_scan_b': False, 'title': 'Скотный Двор / Animal Farm'}, {'author_key': ['OL16029200A', 'OL14722600A'], 'author_name': ['George Orwell', 'Tranzlaty'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2025, 'has_fulltext': False, 'key': '/works/OL44592426W', 'language': ['rus'], 'public_scan_b': False, 'title': 'Скотный Двор / مزرعة الحيوانات'}, {'author_key': ['OL16029200A', 'OL14722600A'], 'author_name': ['George Orwell', 'Tranzlaty'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2025, 'has_fulltext': False, 'key': '/works/OL44594797W', 'language': ['rus'], 'public_scan_b': False, 'title': 'Скотный Двор / Ферма за животни'}, {'author_key': ['OL16029200A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2025, 'has_fulltext': False, 'key': '/works/OL45609522W', 'language': ['eng'], 'public_scan_b': False, 'title': 'Animal Farm'}, {'author_key': ['OL18319A', 'OL16047492A'], 'author_name': ['Mark Twain', 'Jeremy Mac Dinghinton'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2025, 'has_fulltext': False, 'key': '/works/OL44609420W', 'language': ['eng'], 'public_scan_b': False, 'title': 'Adventures of Huckleberry Finn'}, {'author_key': ['OL16029200A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2025, 'has_fulltext': False, 'key': '/works/OL45985337W', 'public_scan_b': False, 'title': 'Review of Mein Kampf by Adolf Hitler'}, {'author_key': ['OL18319A', 'OL6851855A'], 'author_name': ['Mark Twain', 'Candy Gourlay'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL37857189W', 'language': ['eng'], 'public_scan_b': False, 'title': 'Adventures of Huckleberry Finn'}, {'author_key': ['OL18319A'], 'author_name': ['Mark Twain'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL38041648W', 'language': ['eng'], 'public_scan_b': False, 'title': "Mark Twain's Mysterious Stranger Manuscripts"}, {'author_key': ['OL18319A'], 'author_name': ['Mark Twain'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL38036308W', 'language': ['eng'], 'public_scan_b': False, 'title': 'Adventures of Tom Sawyer'}, {'author_key': ['OL18319A'], 'author_name': ['Mark Twain'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL37576769W', 'language': ['eng'], 'public_scan_b': False, 'title': 'The Adventures of Tom Sawyer'}, {'author_key': ['OL18319A'], 'author_name': ['Mark Twain'], 'ebook_access': 'no_ebook', 'edition_count': 2, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL37570184W', 'language': ['eng'], 'public_scan_b': False, 'title': "Oxford Children's Classics"}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL37581342W', 'language': ['eng'], 'public_scan_b': False, 'title': 'Oxford Bookworms Library : Level 6 :  : 1984 Audio Pack : Level 6'}, {'author_key': ['OL18319A', 'OL2496857A'], 'author_name': ['Mark Twain', 'Benjamin Griffin'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL36872822W', 'public_scan_b': False, 'title': "Pudd'nhead Wilson"}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL37584516W', 'language': ['eng'], 'public_scan_b': False, 'title': 'Oxford Bookworms Library : Level 6 :  : 1984 : Level 6'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL37587352W', 'language': ['eng'], 'public_scan_b': False, 'title': 'Oxford Bookworms Library : Level 3 : Animal Farm'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL37590069W', 'language': ['eng'], 'public_scan_b': False, 'title': 'Oxford Bookworms Library : Level 3 :  : Animal Farm Audio Pack : Level 3'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL39129236W', 'language': ['eng'], 'public_scan_b': False, 'title': "Animal Farm (Collector's Edition)"}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41902456W', 'language': ['ger'], 'public_scan_b': False, 'title': 'Farm der Tiere / la Fattoria Degli Animali'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41902460W', 'language': ['ger'], 'public_scan_b': False, 'title': 'Farm der Tiere / de Boerderij de Dieren'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41888174W', 'language': ['por'], 'public_scan_b': False, 'title': 'Animal Farm a / Fazenda Dos Animais'}, {'author_key': ['OL18319A'], 'author_name': ['Mark Twain'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41893561W', 'language': ['eng'], 'public_scan_b': False, 'title': "Pudd'nhead Wilson"}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41894199W', 'language': ['gle'], 'public_scan_b': False, 'title': 'Feirm Na Nainmhithe / Animal Farm'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41894273W', 'language': ['wel'], 'public_scan_b': False, 'title': 'Fferm Anifeiliaid / Animal Farm'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41894283W', 'language': ['ger'], 'public_scan_b': False, 'title': 'Farm der Tiere / la Ferme des Animaux'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41894289W', 'language': ['ger'], 'public_scan_b': False, 'title': 'Farm der Tiere / Rebelión en la Granja'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41894499W', 'language': ['spa'], 'public_scan_b': False, 'title': 'Rebelión en la Granja / Animal Farm'}, {'author_key': ['OL18319A', 'OL14748551A'], 'author_name': ['Mark Twain', 'Orlando Echeverri Benedetti (Traductor)'], 'cover_edition_key': 'OL56977612M', 'cover_i': 15117392, 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41943514W', 'public_scan_b': False, 'title': 'Aventuras de Huckleberry Finn'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41880594W', 'language': ['dan'], 'public_scan_b': False, 'title': 'Animal Farm / Kammerat Napoleon'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41891320W', 'language': ['may'], 'public_scan_b': False, 'title': 'Animal Farm / Politik Kandang'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41900004W', 'language': ['ger'], 'public_scan_b': False, 'title': 'Farm der Tiere / a Fazenda Dos Animais'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL39662214W', 'language': ['eng'], 'public_scan_b': False, 'title': 'Decline of the English Murder and Raffles and Miss Blandish'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL42444442W', 'language': ['eng'], 'public_scan_b': False, 'title': '1984-1'}, {'author_key': ['OL3097235A', 'OL118077A'], 'author_name': ['Ryan Craig', 'George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL42412073W', 'language': ['eng'], 'public_scan_b': False, 'title': "George Orwell's 1984"}, {'author_key': ['OL18319A'], 'author_name': ['Mark Twain'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL42571039W', 'language': ['eng'], 'public_scan_b': False, 'title': 'Letters from the Earth'}, {'author_key': ['OL18319A', 'OL2496857A'], 'author_name': ['Mark Twain', 'Benjamin Griffin'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL31433575W', 'public_scan_b': False, 'title': "Pudd'nhead Wilson"}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL42431619W', 'language': ['eng'], 'public_scan_b': False, 'title': '1984-2'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL42438562W', 'language': ['eng'], 'public_scan_b': False, 'title': '1984-3'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'cover_edition_key': 'OL60673016M', 'cover_i': 15144726, 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL44412752W', 'language': ['fre'], 'public_scan_b': False, 'title': 'Une bonne tasse de thé Et autres essais'}, {'author_key': ['OL18319A'], 'author_name': ['Mark Twain'], 'cover_edition_key': 'OL59943977M', 'cover_i': 15117266, 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL43953930W', 'public_scan_b': False, 'title': 'Aventuras de Huckleberry Finn'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41891104W', 'language': ['kor'], 'public_scan_b': False, 'title': 'Animal Farm / 동물농장'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41888170W', 'language': ['ger'], 'public_scan_b': False, 'title': 'Farm der Tiere / Folwark Zwierzęcy'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41891313W', 'language': ['ger'], 'public_scan_b': False, 'title': 'Farm der Tiere / Фермата на животните'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41880591W', 'language': ['bul'], 'public_scan_b': False, 'title': 'Animal Farm / Фермата на животните'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41894196W', 'language': ['ger'], 'public_scan_b': False, 'title': 'Farm der Tiere / 动物庄园'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41880598W', 'language': ['ger'], 'public_scan_b': False, 'title': 'Farm der Tiere / مزرعة الحيوان'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41891305W', 'language': ['ger'], 'public_scan_b': False, 'title': 'Farm der Tiere / Скотный двор'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41888165W', 'language': ['ger'], 'public_scan_b': False, 'title': 'Farm der Tiere / Hayvan Çiftliği'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41880589W', 'language': ['ger'], 'public_scan_b': False, 'title': 'Farm der Tiere / Колгосп тварин'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41894270W', 'language': ['pol'], 'public_scan_b': False, 'title': 'Folwark Zwierzęcy / Колгосп Tварин'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41897058W', 'language': ['per'], 'public_scan_b': False, 'title': 'Farm der Tiere / مزرعه حیوانات'}, {'author_key': ['OL118077A'], 'author_name': ['George Orwell'], 'ebook_access': 'no_ebook', 'edition_count': 1, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL41891098W', 'language': ['per'], 'public_scan_b': False, 'title': 'Animal Farm / مزرعه حیوانات'}, {'author_key': ['OL18319A', 'OL15004007A'], 'author_name': ['Mark Twain', 'Adaptive Reader'], 'ebook_access': 'no_ebook', 'edition_count': 4, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL42435685W', 'language': ['eng'], 'public_scan_b': False, 'title': 'Adventures of Huckleberry Finn'}, {'author_key': ['OL18319A', 'OL10973178A'], 'author_name': ['Mark Twain', 'Preston Park'], 'ebook_access': 'no_ebook', 'edition_count': 4, 'first_publish_year': 2024, 'has_fulltext': False, 'key': '/works/OL42436391W', 'language': ['eng'], 'public_scan_b': False, 'title': 'Adventures of Tom Sawyer'}, {'author_key': ['OL18319A'], 'author_name': ['Mark Twain'], 'ebook_access': '

In [86]:

dados10 = resposta10.json()
dados10

{'numFound': 8076,
 'start': 0,
 'numFoundExact': True,
 'num_found': 8076,
 'documentation_url': 'https://openlibrary.org/dev/docs/api/search',
 'q': '',
 'offset': None,
 'docs': [{'author_key': ['OL16029200A', 'OL6305694A'],
   'author_name': ['George Orwell', 'Franco Fracassi'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2026,
   'has_fulltext': False,
   'key': '/works/OL45923788W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': 'Fattoria Degli Animali'},
  {'author_key': ['OL16029200A', 'OL2938196A'],
   'author_name': ['George Orwell', 'Kevin Theis'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2026,
   'has_fulltext': False,
   'key': '/works/OL46002345W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': 'Animal Farm - Unabridged'},
  {'author_key': ['OL18319A'],
   'author_name': ['Mark Twain'],
   'ebook_access': 'no_ebook',
   'edition_count': 2,
   'first_publish_year': 2025,
   'has_fulltext': False,
   'key': '/works/OL42550137W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': 'Adventures of Tom Sawyer'},
  {'author_key': ['OL18319A'],
   'author_name': ['Mark Twain'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2025,
   'has_fulltext': False,
   'key': '/works/OL42441718W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': 'Adventures of Tom Sawyer and Huckleberry Finn'},
  {'author_key': ['OL18319A'],
   'author_name': ['Mark Twain'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2025,
   'has_fulltext': False,
   'key': '/works/OL42450517W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': 'Diary of Adam and Eve'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2025,
   'has_fulltext': False,
   'key': '/works/OL42416290W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': 'Can Socialists Be Happy?'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2025,
   'has_fulltext': False,
   'key': '/works/OL42540551W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': 'Literary and Political Essays'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2025,
   'has_fulltext': False,
   'key': '/works/OL44399901W',
   'public_scan_b': False,
   'subtitle': 'A fairy story',
   'title': 'Animal Farm'},
  {'author_key': ['OL16029200A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2025,
   'has_fulltext': False,
   'key': '/works/OL45151681W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': 'George Orwell 2-Book Boxed Set'},
  {'author_key': ['OL18319A', 'OL7508141A'],
   'author_name': ['Mark Twain', 'Stephen H. Provost'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2025,
   'has_fulltext': False,
   'key': '/works/OL44603724W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': 'Dark Twain'},
  {'author_key': ['OL16029200A', 'OL14722600A'],
   'author_name': ['George Orwell', 'Tranzlaty'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2025,
   'has_fulltext': False,
   'key': '/works/OL44602704W',
   'language': ['rus'],
   'public_scan_b': False,
   'title': 'Скотный Двор / Farma Zvířat'},
  {'author_key': ['OL16029200A', 'OL14722600A'],
   'author_name': ['George Orwell', 'Tranzlaty'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2025,
   'has_fulltext': False,
   'key': '/works/OL44596930W',
   'language': ['rus'],
   'public_scan_b': False,
   'title': 'Скотный Двор / Kammerat Napoleon'},
  {'author_key': ['OL16029200A', 'OL14722600A'],
   'author_name': ['George Orwell', 'Tranzlaty'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2025,
   'has_fulltext': False,
   'key': '/works/OL44602702W',
   'language': ['rus'],
   'public_scan_b': False,
   'title': 'Скотный Двор / Zivotinjska Farma'},
  {'author_key': ['OL16029200A', 'OL14722600A'],
   'author_name': ['George Orwell', 'Tranzlaty'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2025,
   'has_fulltext': False,
   'key': '/works/OL44604569W',
   'language': ['rus'],
   'public_scan_b': False,
   'title': 'Скотный Двор / Diereplaas'},
  {'author_key': ['OL16029200A', 'OL14722600A'],
   'author_name': ['George Orwell', 'Tranzlaty'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2025,
   'has_fulltext': False,
   'key': '/works/OL44600805W',
   'language': ['rus'],
   'public_scan_b': False,
   'title': 'Скотный Двор / Dierenboerderij'},
  {'author_key': ['OL16029200A', 'OL14722600A'],
   'author_name': ['George Orwell', 'Tranzlaty'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2025,
   'has_fulltext': False,
   'key': '/works/OL44590012W',
   'language': ['rus'],
   'public_scan_b': False,
   'title': 'Скотный Двор / Animal Farm'},
  {'author_key': ['OL16029200A', 'OL14722600A'],
   'author_name': ['George Orwell', 'Tranzlaty'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2025,
   'has_fulltext': False,
   'key': '/works/OL44592426W',
   'language': ['rus'],
   'public_scan_b': False,
   'title': 'Скотный Двор / مزرعة الحيوانات'},
  {'author_key': ['OL16029200A', 'OL14722600A'],
   'author_name': ['George Orwell', 'Tranzlaty'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2025,
   'has_fulltext': False,
   'key': '/works/OL44594797W',
   'language': ['rus'],
   'public_scan_b': False,
   'title': 'Скотный Двор / Ферма за животни'},
  {'author_key': ['OL16029200A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2025,
   'has_fulltext': False,
   'key': '/works/OL45609522W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': 'Animal Farm'},
  {'author_key': ['OL18319A', 'OL16047492A'],
   'author_name': ['Mark Twain', 'Jeremy Mac Dinghinton'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2025,
   'has_fulltext': False,
   'key': '/works/OL44609420W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': 'Adventures of Huckleberry Finn'},
  {'author_key': ['OL16029200A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2025,
   'has_fulltext': False,
   'key': '/works/OL45985337W',
   'public_scan_b': False,
   'title': 'Review of Mein Kampf by Adolf Hitler'},
  {'author_key': ['OL18319A', 'OL6851855A'],
   'author_name': ['Mark Twain', 'Candy Gourlay'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL37857189W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': 'Adventures of Huckleberry Finn'},
  {'author_key': ['OL18319A'],
   'author_name': ['Mark Twain'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL38041648W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': "Mark Twain's Mysterious Stranger Manuscripts"},
  {'author_key': ['OL18319A'],
   'author_name': ['Mark Twain'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL38036308W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': 'Adventures of Tom Sawyer'},
  {'author_key': ['OL18319A'],
   'author_name': ['Mark Twain'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL37576769W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': 'The Adventures of Tom Sawyer'},
  {'author_key': ['OL18319A'],
   'author_name': ['Mark Twain'],
   'ebook_access': 'no_ebook',
   'edition_count': 2,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL37570184W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': "Oxford Children's Classics"},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL37581342W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': 'Oxford Bookworms Library : Level 6 :  : 1984 Audio Pack : Level 6'},
  {'author_key': ['OL18319A', 'OL2496857A'],
   'author_name': ['Mark Twain', 'Benjamin Griffin'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL36872822W',
   'public_scan_b': False,
   'title': "Pudd'nhead Wilson"},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL37584516W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': 'Oxford Bookworms Library : Level 6 :  : 1984 : Level 6'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL37587352W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': 'Oxford Bookworms Library : Level 3 : Animal Farm'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL37590069W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': 'Oxford Bookworms Library : Level 3 :  : Animal Farm Audio Pack : Level 3'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL39129236W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': "Animal Farm (Collector's Edition)"},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL41902456W',
   'language': ['ger'],
   'public_scan_b': False,
   'title': 'Farm der Tiere / la Fattoria Degli Animali'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL41902460W',
   'language': ['ger'],
   'public_scan_b': False,
   'title': 'Farm der Tiere / de Boerderij de Dieren'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL41888174W',
   'language': ['por'],
   'public_scan_b': False,
   'title': 'Animal Farm a / Fazenda Dos Animais'},
  {'author_key': ['OL18319A'],
   'author_name': ['Mark Twain'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL41893561W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': "Pudd'nhead Wilson"},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL41894199W',
   'language': ['gle'],
   'public_scan_b': False,
   'title': 'Feirm Na Nainmhithe / Animal Farm'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL41894273W',
   'language': ['wel'],
   'public_scan_b': False,
   'title': 'Fferm Anifeiliaid / Animal Farm'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL41894283W',
   'language': ['ger'],
   'public_scan_b': False,
   'title': 'Farm der Tiere / la Ferme des Animaux'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL41894289W',
   'language': ['ger'],
   'public_scan_b': False,
   'title': 'Farm der Tiere / Rebelión en la Granja'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL41894499W',
   'language': ['spa'],
   'public_scan_b': False,
   'title': 'Rebelión en la Granja / Animal Farm'},
  {'author_key': ['OL18319A', 'OL14748551A'],
   'author_name': ['Mark Twain', 'Orlando Echeverri Benedetti (Traductor)'],
   'cover_edition_key': 'OL56977612M',
   'cover_i': 15117392,
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL41943514W',
   'public_scan_b': False,
   'title': 'Aventuras de Huckleberry Finn'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL41880594W',
   'language': ['dan'],
   'public_scan_b': False,
   'title': 'Animal Farm / Kammerat Napoleon'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL41891320W',
   'language': ['may'],
   'public_scan_b': False,
   'title': 'Animal Farm / Politik Kandang'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL41900004W',
   'language': ['ger'],
   'public_scan_b': False,
   'title': 'Farm der Tiere / a Fazenda Dos Animais'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL39662214W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': 'Decline of the English Murder and Raffles and Miss Blandish'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL42444442W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': '1984-1'},
  {'author_key': ['OL3097235A', 'OL118077A'],
   'author_name': ['Ryan Craig', 'George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL42412073W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': "George Orwell's 1984"},
  {'author_key': ['OL18319A'],
   'author_name': ['Mark Twain'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL42571039W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': 'Letters from the Earth'},
  {'author_key': ['OL18319A', 'OL2496857A'],
   'author_name': ['Mark Twain', 'Benjamin Griffin'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL31433575W',
   'public_scan_b': False,
   'title': "Pudd'nhead Wilson"},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL42431619W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': '1984-2'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL42438562W',
   'language': ['eng'],
   'public_scan_b': False,
   'title': '1984-3'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'cover_edition_key': 'OL60673016M',
   'cover_i': 15144726,
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL44412752W',
   'language': ['fre'],
   'public_scan_b': False,
   'title': 'Une bonne tasse de thé Et autres essais'},
  {'author_key': ['OL18319A'],
   'author_name': ['Mark Twain'],
   'cover_edition_key': 'OL59943977M',
   'cover_i': 15117266,
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL43953930W',
   'public_scan_b': False,
   'title': 'Aventuras de Huckleberry Finn'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL41891104W',
   'language': ['kor'],
   'public_scan_b': False,
   'title': 'Animal Farm / 동물농장'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL41888170W',
   'language': ['ger'],
   'public_scan_b': False,
   'title': 'Farm der Tiere / Folwark Zwierzęcy'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL41891313W',
   'language': ['ger'],
   'public_scan_b': False,
   'title': 'Farm der Tiere / Фермата на животните'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL41880591W',
   'language': ['bul'],
   'public_scan_b': False,
   'title': 'Animal Farm / Фермата на животните'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL41894196W',
   'language': ['ger'],
   'public_scan_b': False,
   'title': 'Farm der Tiere / 动物庄园'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL41880598W',
   'language': ['ger'],
   'public_scan_b': False,
   'title': 'Farm der Tiere / مزرعة الحيوان'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL41891305W',
   'language': ['ger'],
   'public_scan_b': False,
   'title': 'Farm der Tiere / Скотный двор'},
  {'author_key': ['OL118077A'],
   'author_name': ['George Orwell'],
   'ebook_access': 'no_ebook',
   'edition_count': 1,
   'first_publish_year': 2024,
   'has_fulltext': False,
   'key': '/works/OL41888165W',
   'language': ['ger'],
   'public_scan_b': False,
   'title': 'Farm der Tiere / Hayvan Çiftliği'},

In [89]:

df10 = pd.json_normalize(dados10['docs'])[['title', 'author_name', 'first_publish_year']]

df10

,title,author_name,first_publish_year
0,Fattoria Degli Animali,"[George Orwell, Franco Fracassi]",2026
1,Animal Farm - Unabridged,"[George Orwell, Kevin Theis]",2026
2,Adventures of Tom Sawyer,[Mark Twain],2025
3,Adventures of Tom Sawyer and Huckleberry Finn,[Mark Twain],2025
4,Diary of Adam and Eve,[Mark Twain],2025
...,...,...,...
95,Mark Twain's Letters,"[Albert Bigelow Paine, Mark Twain]",2023
96,Writings of Mark Twain [Pseud. ]; Volume 13,[Mark Twain],2023
97,Double Barrelled Detective Story,[Mark Twain],2023
98,Big Book of Graphic Classics,"[Jules Verne, Wim Coleman, Pat Perrin, Robert ...",2023
99,Adventures of Tom Sawyer / Adventures of Huckl...,[Mark Twain],2023

## Exercício 11

Leia os dados do ficheiro `exercicios\comissão_vendedores.xlsx` para um DataFrame e determine o vendedor que vendeu mais e menos e o mês em que isso aconteceu. Faça o mesmo relativamente ao valor das comissões.

## Exercício 12
Use a API do JSONPlaceholder (https://jsonplaceholder.typicode.com/) para obter uma lista de _posts_ e comentários associados.